// Code generated by protoc-gen-go. DO NOT EDIT.
// source: writing/writing.proto

// 内容创作模块

package writing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArticleInfo struct {
	Id                   int64              `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string             `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Summary              string             `protobuf:"bytes,3,opt,name=Summary,proto3" json:"Summary,omitempty"`
	Tags                 []*ArticleTag      `protobuf:"bytes,4,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CreatedAt            int64              `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Status               int64              `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Content              string             `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`
	Category             *Category          `protobuf:"bytes,8,opt,name=Category,proto3" json:"Category,omitempty"`
	ArticleCountInfo     *ArticleCountInfo  `protobuf:"bytes,9,opt,name=ArticleCountInfo,proto3" json:"ArticleCountInfo,omitempty"`
	ArticleAuthorInfo    *ArticleAuthorInfo `protobuf:"bytes,10,opt,name=ArticleAuthorInfo,proto3" json:"ArticleAuthorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ArticleInfo) Reset()         { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()    {}
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{0}
}

func (m *ArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleInfo.Unmarshal(m, b)
}
func (m *ArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleInfo.Marshal(b, m, deterministic)
}
func (m *ArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleInfo.Merge(m, src)
}
func (m *ArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleInfo.Size(m)
}
func (m *ArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleInfo proto.InternalMessageInfo

func (m *ArticleInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleInfo) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ArticleInfo) GetTags() []*ArticleTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ArticleInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ArticleInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ArticleInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ArticleInfo) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *ArticleInfo) GetArticleCountInfo() *ArticleCountInfo {
	if m != nil {
		return m.ArticleCountInfo
	}
	return nil
}

func (m *ArticleInfo) GetArticleAuthorInfo() *ArticleAuthorInfo {
	if m != nil {
		return m.ArticleAuthorInfo
	}
	return nil
}

// Tag解构体
type ArticleTag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleTag) Reset()         { *m = ArticleTag{} }
func (m *ArticleTag) String() string { return proto.CompactTextString(m) }
func (*ArticleTag) ProtoMessage()    {}
func (*ArticleTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{1}
}

func (m *ArticleTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleTag.Unmarshal(m, b)
}
func (m *ArticleTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleTag.Marshal(b, m, deterministic)
}
func (m *ArticleTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleTag.Merge(m, src)
}
func (m *ArticleTag) XXX_Size() int {
	return xxx_messageInfo_ArticleTag.Size(m)
}
func (m *ArticleTag) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleTag.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleTag proto.InternalMessageInfo

func (m *ArticleTag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleTag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type IntRequest struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntRequest) Reset()         { *m = IntRequest{} }
func (m *IntRequest) String() string { return proto.CompactTextString(m) }
func (*IntRequest) ProtoMessage()    {}
func (*IntRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{2}
}

func (m *IntRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntRequest.Unmarshal(m, b)
}
func (m *IntRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntRequest.Marshal(b, m, deterministic)
}
func (m *IntRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntRequest.Merge(m, src)
}
func (m *IntRequest) XXX_Size() int {
	return xxx_messageInfo_IntRequest.Size(m)
}
func (m *IntRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IntRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IntRequest proto.InternalMessageInfo

func (m *IntRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 数据统计信息
type ArticleCountInfo struct {
	Comment              int64    `protobuf:"varint,1,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Like                 int64    `protobuf:"varint,2,opt,name=Like,proto3" json:"Like,omitempty"`
	Collect              int64    `protobuf:"varint,3,opt,name=Collect,proto3" json:"Collect,omitempty"`
	DisLike              int64    `protobuf:"varint,4,opt,name=DisLike,proto3" json:"DisLike,omitempty"`
	PageView             int64    `protobuf:"varint,5,opt,name=PageView,proto3" json:"PageView,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleCountInfo) Reset()         { *m = ArticleCountInfo{} }
func (m *ArticleCountInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleCountInfo) ProtoMessage()    {}
func (*ArticleCountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{3}
}

func (m *ArticleCountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleCountInfo.Unmarshal(m, b)
}
func (m *ArticleCountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleCountInfo.Marshal(b, m, deterministic)
}
func (m *ArticleCountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleCountInfo.Merge(m, src)
}
func (m *ArticleCountInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleCountInfo.Size(m)
}
func (m *ArticleCountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleCountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleCountInfo proto.InternalMessageInfo

func (m *ArticleCountInfo) GetComment() int64 {
	if m != nil {
		return m.Comment
	}
	return 0
}

func (m *ArticleCountInfo) GetLike() int64 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *ArticleCountInfo) GetCollect() int64 {
	if m != nil {
		return m.Collect
	}
	return 0
}

func (m *ArticleCountInfo) GetDisLike() int64 {
	if m != nil {
		return m.DisLike
	}
	return 0
}

func (m *ArticleCountInfo) GetPageView() int64 {
	if m != nil {
		return m.PageView
	}
	return 0
}

// 作者信息
type ArticleAuthorInfo struct {
	AuthorUID            int64    `protobuf:"varint,1,opt,name=AuthorUID,proto3" json:"AuthorUID,omitempty"`
	AuthorNickname       string   `protobuf:"bytes,2,opt,name=AuthorNickname,proto3" json:"AuthorNickname,omitempty"`
	AuthorAvatar         string   `protobuf:"bytes,3,opt,name=AuthorAvatar,proto3" json:"AuthorAvatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleAuthorInfo) Reset()         { *m = ArticleAuthorInfo{} }
func (m *ArticleAuthorInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleAuthorInfo) ProtoMessage()    {}
func (*ArticleAuthorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{4}
}

func (m *ArticleAuthorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleAuthorInfo.Unmarshal(m, b)
}
func (m *ArticleAuthorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleAuthorInfo.Marshal(b, m, deterministic)
}
func (m *ArticleAuthorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleAuthorInfo.Merge(m, src)
}
func (m *ArticleAuthorInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleAuthorInfo.Size(m)
}
func (m *ArticleAuthorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleAuthorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleAuthorInfo proto.InternalMessageInfo

func (m *ArticleAuthorInfo) GetAuthorUID() int64 {
	if m != nil {
		return m.AuthorUID
	}
	return 0
}

func (m *ArticleAuthorInfo) GetAuthorNickname() string {
	if m != nil {
		return m.AuthorNickname
	}
	return ""
}

func (m *ArticleAuthorInfo) GetAuthorAvatar() string {
	if m != nil {
		return m.AuthorAvatar
	}
	return ""
}

// 文章类别
type Category struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CN                   string   `protobuf:"bytes,2,opt,name=CN,proto3" json:"CN,omitempty"`
	EN                   string   `protobuf:"bytes,3,opt,name=EN,proto3" json:"EN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{5}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetCN() string {
	if m != nil {
		return m.CN
	}
	return ""
}

func (m *Category) GetEN() string {
	if m != nil {
		return m.EN
	}
	return ""
}

func init() {
	proto.RegisterType((*ArticleInfo)(nil), "writing.ArticleInfo")
	proto.RegisterType((*ArticleTag)(nil), "writing.ArticleTag")
	proto.RegisterType((*IntRequest)(nil), "writing.IntRequest")
	proto.RegisterType((*ArticleCountInfo)(nil), "writing.ArticleCountInfo")
	proto.RegisterType((*ArticleAuthorInfo)(nil), "writing.ArticleAuthorInfo")
	proto.RegisterType((*Category)(nil), "writing.Category")
}

func init() { proto.RegisterFile("writing/writing.proto", fileDescriptor_db9b9589ec5f9fbc) }

var fileDescriptor_db9b9589ec5f9fbc = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x3d, 0x8f, 0xd3, 0x40,
	0x10, 0xc5, 0x1f, 0x97, 0x8f, 0x09, 0x8a, 0xee, 0x86, 0x03, 0x2d, 0x11, 0x45, 0xe4, 0x02, 0xd2,
	0x10, 0xa4, 0xd0, 0x21, 0x51, 0x04, 0x5f, 0x04, 0x46, 0xc8, 0x42, 0x4e, 0x48, 0xbf, 0x24, 0x8b,
	0xb1, 0xce, 0x1f, 0xe0, 0x8c, 0x39, 0xa5, 0xa0, 0xa5, 0xe6, 0x27, 0x23, 0xef, 0x8e, 0x63, 0x88,
	0xa9, 0xbc, 0xef, 0xcd, 0x9b, 0x99, 0xdd, 0x79, 0x63, 0x78, 0x78, 0x57, 0x26, 0x94, 0xe4, 0xf1,
	0x0b, 0xfe, 0xce, 0xbf, 0x95, 0x05, 0x15, 0xd8, 0x67, 0xe8, 0xfd, 0x72, 0x60, 0xb4, 0x2c, 0x29,
	0xd9, 0xa5, 0x2a, 0xc8, 0xbf, 0x14, 0x38, 0x06, 0x3b, 0xd8, 0x0b, 0x6b, 0x6a, 0xcd, 0x9c, 0xc8,
	0x0e, 0xf6, 0x78, 0x0d, 0x17, 0x9b, 0x84, 0x52, 0x25, 0xec, 0xa9, 0x35, 0x1b, 0x46, 0x06, 0xa0,
	0x80, 0xfe, 0xba, 0xca, 0x32, 0x59, 0x1e, 0x85, 0xa3, 0xf9, 0x06, 0xe2, 0x33, 0x70, 0x37, 0x32,
	0x3e, 0x08, 0x77, 0xea, 0xcc, 0x46, 0x8b, 0x07, 0xf3, 0xa6, 0x2d, 0xf7, 0xd8, 0xc8, 0x38, 0xd2,
	0x02, 0x7c, 0x02, 0x43, 0xbf, 0x54, 0x92, 0xd4, 0x7e, 0x49, 0xe2, 0x42, 0xf7, 0x6b, 0x09, 0x7c,
	0x04, 0xbd, 0x35, 0x49, 0xaa, 0x0e, 0xa2, 0xa7, 0x43, 0x8c, 0xea, 0xc6, 0x7e, 0x91, 0x93, 0xca,
	0x49, 0xf4, 0x4d, 0x63, 0x86, 0xf8, 0x1c, 0x06, 0xbe, 0x24, 0x15, 0x17, 0xe5, 0x51, 0x0c, 0xa6,
	0xd6, 0x6c, 0xb4, 0xb8, 0x3a, 0x35, 0x6f, 0x02, 0xd1, 0x49, 0x82, 0x2b, 0xb8, 0xe4, 0x2b, 0xf9,
	0x45, 0x95, 0x53, 0xfd, 0x76, 0x31, 0xd4, 0x69, 0x8f, 0xcf, 0xef, 0x7c, 0x12, 0x44, 0x9d, 0x14,
	0x7c, 0x07, 0x57, 0xcc, 0x2d, 0x2b, 0xfa, 0x5a, 0x94, 0xba, 0x0e, 0xe8, 0x3a, 0x93, 0xf3, 0x3a,
	0xad, 0x22, 0xea, 0x26, 0x79, 0x73, 0x80, 0x76, 0x46, 0x1d, 0x1b, 0x2e, 0xc1, 0xd9, 0xc8, 0x98,
	0x4d, 0xa8, 0x8f, 0x9e, 0x07, 0x10, 0xe4, 0x14, 0xa9, 0xef, 0x95, 0x3a, 0x50, 0x6d, 0xd3, 0x56,
	0xa6, 0x95, 0xe2, 0x14, 0x03, 0xbc, 0xdf, 0x56, 0xf7, 0x95, 0x66, 0x84, 0x59, 0x56, 0x8f, 0xd0,
	0x88, 0x1b, 0x88, 0x08, 0xee, 0x87, 0xe4, 0xd6, 0x58, 0xed, 0x44, 0xfa, 0x6c, 0xd4, 0x69, 0xaa,
	0x76, 0xa4, 0x9d, 0xd6, 0x6a, 0x0d, 0xeb, 0xc8, 0x4d, 0x72, 0xd0, 0x09, 0xae, 0x89, 0x30, 0xc4,
	0x09, 0x0c, 0x3e, 0xca, 0x58, 0x6d, 0x13, 0x75, 0xc7, 0xce, 0x9e, 0xb0, 0xf7, 0xf3, 0x3f, 0x03,
	0xab, 0x77, 0xc1, 0xa0, 0x4f, 0xc1, 0x0d, 0x5f, 0xaa, 0x25, 0xf0, 0x29, 0x8c, 0x0d, 0x08, 0x93,
	0xdd, 0x6d, 0x2e, 0xb3, 0x66, 0x17, 0xcf, 0x58, 0xf4, 0xe0, 0xbe, 0x61, 0x96, 0x3f, 0x24, 0xc9,
	0x92, 0x37, 0xf3, 0x1f, 0xce, 0x7b, 0xd5, 0x6e, 0xc9, 0x5f, 0x33, 0x76, 0xf5, 0x8c, 0xc7, 0x60,
	0xfb, 0x21, 0xd7, 0xb6, 0xfd, 0xb0, 0xc6, 0xab, 0x90, 0xab, 0xd8, 0xab, 0x70, 0xf1, 0x1e, 0x86,
	0xec, 0xe8, 0x7a, 0x8b, 0xaf, 0x61, 0xfc, 0x56, 0x11, 0x3f, 0xe5, 0xcd, 0x31, 0xd8, 0x63, 0xbb,
	0xeb, 0xad, 0x2f, 0x93, 0xeb, 0xf3, 0x25, 0xd0, 0x5e, 0xdf, 0xfb, 0xdc, 0xd3, 0xbf, 0xe1, 0xcb,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xae, 0xb0, 0xb3, 0xa9, 0x9f, 0x03, 0x00, 0x00,
}
