// Code generated by protoc-gen-go. DO NOT EDIT.
// source: writing/writing.proto

// 内容创作模块

package writing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// --------------------------response  start-----------------------------
type WritingErrors int32

const (
	WritingErrors_None               WritingErrors = 0
	WritingErrors_ArticleNotFound    WritingErrors = 3000001
	WritingErrors_PostArticleFailed  WritingErrors = 3000002
	WritingErrors_PostCategoryFailed WritingErrors = 3000003
)

var WritingErrors_name = map[int32]string{
	0:       "None",
	3000001: "ArticleNotFound",
	3000002: "PostArticleFailed",
	3000003: "PostCategoryFailed",
}

var WritingErrors_value = map[string]int32{
	"None":               0,
	"ArticleNotFound":    3000001,
	"PostArticleFailed":  3000002,
	"PostCategoryFailed": 3000003,
}

func (x WritingErrors) String() string {
	return proto.EnumName(WritingErrors_name, int32(x))
}

func (WritingErrors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{0}
}

type ArticleInfo struct {
	Id                   int64              `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string             `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Summary              string             `protobuf:"bytes,3,opt,name=Summary,proto3" json:"Summary,omitempty"`
	Tags                 []*ArticleTag      `protobuf:"bytes,4,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CreatedAt            int64              `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Status               int64              `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Content              string             `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`
	Category             *Category          `protobuf:"bytes,8,opt,name=Category,proto3" json:"Category,omitempty"`
	ArticleCountInfo     *ArticleCountInfo  `protobuf:"bytes,9,opt,name=ArticleCountInfo,proto3" json:"ArticleCountInfo,omitempty"`
	ArticleAuthorInfo    *ArticleAuthorInfo `protobuf:"bytes,10,opt,name=ArticleAuthorInfo,proto3" json:"ArticleAuthorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ArticleInfo) Reset()         { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()    {}
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{0}
}

func (m *ArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleInfo.Unmarshal(m, b)
}
func (m *ArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleInfo.Marshal(b, m, deterministic)
}
func (m *ArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleInfo.Merge(m, src)
}
func (m *ArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleInfo.Size(m)
}
func (m *ArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleInfo proto.InternalMessageInfo

func (m *ArticleInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleInfo) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ArticleInfo) GetTags() []*ArticleTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ArticleInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ArticleInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ArticleInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ArticleInfo) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *ArticleInfo) GetArticleCountInfo() *ArticleCountInfo {
	if m != nil {
		return m.ArticleCountInfo
	}
	return nil
}

func (m *ArticleInfo) GetArticleAuthorInfo() *ArticleAuthorInfo {
	if m != nil {
		return m.ArticleAuthorInfo
	}
	return nil
}

// Tag解构体
type ArticleTag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleTag) Reset()         { *m = ArticleTag{} }
func (m *ArticleTag) String() string { return proto.CompactTextString(m) }
func (*ArticleTag) ProtoMessage()    {}
func (*ArticleTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{1}
}

func (m *ArticleTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleTag.Unmarshal(m, b)
}
func (m *ArticleTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleTag.Marshal(b, m, deterministic)
}
func (m *ArticleTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleTag.Merge(m, src)
}
func (m *ArticleTag) XXX_Size() int {
	return xxx_messageInfo_ArticleTag.Size(m)
}
func (m *ArticleTag) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleTag.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleTag proto.InternalMessageInfo

func (m *ArticleTag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleTag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// 数据统计信息
type ArticleCountInfo struct {
	Comment              int64    `protobuf:"varint,1,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Like                 int64    `protobuf:"varint,2,opt,name=Like,proto3" json:"Like,omitempty"`
	Collect              int64    `protobuf:"varint,3,opt,name=Collect,proto3" json:"Collect,omitempty"`
	DisLike              int64    `protobuf:"varint,4,opt,name=DisLike,proto3" json:"DisLike,omitempty"`
	PageView             int64    `protobuf:"varint,5,opt,name=PageView,proto3" json:"PageView,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleCountInfo) Reset()         { *m = ArticleCountInfo{} }
func (m *ArticleCountInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleCountInfo) ProtoMessage()    {}
func (*ArticleCountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{2}
}

func (m *ArticleCountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleCountInfo.Unmarshal(m, b)
}
func (m *ArticleCountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleCountInfo.Marshal(b, m, deterministic)
}
func (m *ArticleCountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleCountInfo.Merge(m, src)
}
func (m *ArticleCountInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleCountInfo.Size(m)
}
func (m *ArticleCountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleCountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleCountInfo proto.InternalMessageInfo

func (m *ArticleCountInfo) GetComment() int64 {
	if m != nil {
		return m.Comment
	}
	return 0
}

func (m *ArticleCountInfo) GetLike() int64 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *ArticleCountInfo) GetCollect() int64 {
	if m != nil {
		return m.Collect
	}
	return 0
}

func (m *ArticleCountInfo) GetDisLike() int64 {
	if m != nil {
		return m.DisLike
	}
	return 0
}

func (m *ArticleCountInfo) GetPageView() int64 {
	if m != nil {
		return m.PageView
	}
	return 0
}

// 作者信息
type ArticleAuthorInfo struct {
	AuthorUID            int64    `protobuf:"varint,1,opt,name=AuthorUID,proto3" json:"AuthorUID,omitempty"`
	AuthorNickname       string   `protobuf:"bytes,2,opt,name=AuthorNickname,proto3" json:"AuthorNickname,omitempty"`
	AuthorAvatar         string   `protobuf:"bytes,3,opt,name=AuthorAvatar,proto3" json:"AuthorAvatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleAuthorInfo) Reset()         { *m = ArticleAuthorInfo{} }
func (m *ArticleAuthorInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleAuthorInfo) ProtoMessage()    {}
func (*ArticleAuthorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{3}
}

func (m *ArticleAuthorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleAuthorInfo.Unmarshal(m, b)
}
func (m *ArticleAuthorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleAuthorInfo.Marshal(b, m, deterministic)
}
func (m *ArticleAuthorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleAuthorInfo.Merge(m, src)
}
func (m *ArticleAuthorInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleAuthorInfo.Size(m)
}
func (m *ArticleAuthorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleAuthorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleAuthorInfo proto.InternalMessageInfo

func (m *ArticleAuthorInfo) GetAuthorUID() int64 {
	if m != nil {
		return m.AuthorUID
	}
	return 0
}

func (m *ArticleAuthorInfo) GetAuthorNickname() string {
	if m != nil {
		return m.AuthorNickname
	}
	return ""
}

func (m *ArticleAuthorInfo) GetAuthorAvatar() string {
	if m != nil {
		return m.AuthorAvatar
	}
	return ""
}

// 文章类别
type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CN                   string   `protobuf:"bytes,2,opt,name=CN,proto3" json:"CN,omitempty"`
	EN                   string   `protobuf:"bytes,3,opt,name=EN,proto3" json:"EN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{4}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetCN() string {
	if m != nil {
		return m.CN
	}
	return ""
}

func (m *Category) GetEN() string {
	if m != nil {
		return m.EN
	}
	return ""
}

// --------------------------request  start------------------------------
// int参数请求
type IntRequest struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntRequest) Reset()         { *m = IntRequest{} }
func (m *IntRequest) String() string { return proto.CompactTextString(m) }
func (*IntRequest) ProtoMessage()    {}
func (*IntRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{5}
}

func (m *IntRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntRequest.Unmarshal(m, b)
}
func (m *IntRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntRequest.Marshal(b, m, deterministic)
}
func (m *IntRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntRequest.Merge(m, src)
}
func (m *IntRequest) XXX_Size() int {
	return xxx_messageInfo_IntRequest.Size(m)
}
func (m *IntRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IntRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IntRequest proto.InternalMessageInfo

func (m *IntRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PostArticleRequest struct {
	CategoryID           int64    `protobuf:"varint,1,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	AuthorUID            int64    `protobuf:"varint,4,opt,name=AuthorUID,proto3" json:"AuthorUID,omitempty"`
	Summary              string   `protobuf:"bytes,5,opt,name=Summary,proto3" json:"Summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostArticleRequest) Reset()         { *m = PostArticleRequest{} }
func (m *PostArticleRequest) String() string { return proto.CompactTextString(m) }
func (*PostArticleRequest) ProtoMessage()    {}
func (*PostArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{6}
}

func (m *PostArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostArticleRequest.Unmarshal(m, b)
}
func (m *PostArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostArticleRequest.Marshal(b, m, deterministic)
}
func (m *PostArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostArticleRequest.Merge(m, src)
}
func (m *PostArticleRequest) XXX_Size() int {
	return xxx_messageInfo_PostArticleRequest.Size(m)
}
func (m *PostArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostArticleRequest proto.InternalMessageInfo

func (m *PostArticleRequest) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *PostArticleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostArticleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostArticleRequest) GetAuthorUID() int64 {
	if m != nil {
		return m.AuthorUID
	}
	return 0
}

func (m *PostArticleRequest) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

type GetArticleListRequest struct {
	LimitAriticleID      int64    `protobuf:"varint,1,opt,name=LimitAriticleID,proto3" json:"LimitAriticleID,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	CategoryID           int64    `protobuf:"varint,4,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	OrderType            string   `protobuf:"bytes,5,opt,name=OrderType,proto3" json:"OrderType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleListRequest) Reset()         { *m = GetArticleListRequest{} }
func (m *GetArticleListRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleListRequest) ProtoMessage()    {}
func (*GetArticleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{7}
}

func (m *GetArticleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListRequest.Unmarshal(m, b)
}
func (m *GetArticleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListRequest.Merge(m, src)
}
func (m *GetArticleListRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleListRequest.Size(m)
}
func (m *GetArticleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListRequest proto.InternalMessageInfo

func (m *GetArticleListRequest) GetLimitAriticleID() int64 {
	if m != nil {
		return m.LimitAriticleID
	}
	return 0
}

func (m *GetArticleListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetArticleListRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetArticleListRequest) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *GetArticleListRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

type ErrorResponse struct {
	ErrorInfo            WritingErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=writing.WritingErrors" json:"ErrorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{8}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetErrorInfo() WritingErrors {
	if m != nil {
		return m.ErrorInfo
	}
	return WritingErrors_None
}

func init() {
	proto.RegisterEnum("writing.WritingErrors", WritingErrors_name, WritingErrors_value)
	proto.RegisterType((*ArticleInfo)(nil), "writing.ArticleInfo")
	proto.RegisterType((*ArticleTag)(nil), "writing.ArticleTag")
	proto.RegisterType((*ArticleCountInfo)(nil), "writing.ArticleCountInfo")
	proto.RegisterType((*ArticleAuthorInfo)(nil), "writing.ArticleAuthorInfo")
	proto.RegisterType((*Category)(nil), "writing.Category")
	proto.RegisterType((*IntRequest)(nil), "writing.IntRequest")
	proto.RegisterType((*PostArticleRequest)(nil), "writing.PostArticleRequest")
	proto.RegisterType((*GetArticleListRequest)(nil), "writing.GetArticleListRequest")
	proto.RegisterType((*ErrorResponse)(nil), "writing.ErrorResponse")
}

func init() { proto.RegisterFile("writing/writing.proto", fileDescriptor_db9b9589ec5f9fbc) }

var fileDescriptor_db9b9589ec5f9fbc = []byte{
	// 702 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0x5d, 0x4f, 0xd3, 0x5e,
	0x18, 0xa7, 0x2f, 0xc0, 0xf6, 0x0c, 0xc6, 0x78, 0xfe, 0x40, 0xca, 0xfe, 0x84, 0x2c, 0xbd, 0xd0,
	0xc5, 0x44, 0x4c, 0xa6, 0x37, 0x9a, 0x78, 0x31, 0xc6, 0x90, 0x25, 0xa4, 0x92, 0x6e, 0xe2, 0x75,
	0xa5, 0x87, 0xd9, 0xb0, 0xb5, 0x78, 0x7a, 0x2a, 0x99, 0x89, 0xb7, 0xde, 0x91, 0x98, 0x78, 0xeb,
	0xbd, 0x1f, 0x81, 0x6b, 0xf5, 0x8b, 0x99, 0xf3, 0xd2, 0x76, 0x6b, 0xe1, 0x6a, 0xe7, 0xf7, 0xbc,
	0xbf, 0xfc, 0x9e, 0x0e, 0xb6, 0x6f, 0x68, 0xc0, 0x82, 0x70, 0xfc, 0x4c, 0xfd, 0x1e, 0x5c, 0xd3,
	0x88, 0x45, 0xb8, 0xaa, 0xa0, 0xfd, 0xcd, 0x80, 0x5a, 0x97, 0xb2, 0xe0, 0x62, 0x42, 0x06, 0xe1,
	0x65, 0x84, 0x75, 0xd0, 0x07, 0xbe, 0xa5, 0xb5, 0xb4, 0xb6, 0xe1, 0xea, 0x03, 0x1f, 0xb7, 0x60,
	0x79, 0x14, 0xb0, 0x09, 0xb1, 0xf4, 0x96, 0xd6, 0xae, 0xba, 0x12, 0xa0, 0x05, 0xab, 0xc3, 0x64,
	0x3a, 0xf5, 0xe8, 0xcc, 0x32, 0x84, 0x3c, 0x85, 0xf8, 0x18, 0xcc, 0x91, 0x37, 0x8e, 0x2d, 0xb3,
	0x65, 0xb4, 0x6b, 0x9d, 0xff, 0x0e, 0xd2, 0xb4, 0x2a, 0xc7, 0xc8, 0x1b, 0xbb, 0xc2, 0x00, 0xf7,
	0xa0, 0xda, 0xa3, 0xc4, 0x63, 0xc4, 0xef, 0x32, 0x6b, 0x59, 0xe4, 0xcb, 0x05, 0xb8, 0x03, 0x2b,
	0x43, 0xe6, 0xb1, 0x24, 0xb6, 0x56, 0x84, 0x4a, 0x21, 0x9e, 0xb8, 0x17, 0x85, 0x8c, 0x84, 0xcc,
	0x5a, 0x95, 0x89, 0x15, 0xc4, 0xa7, 0x50, 0xe9, 0x79, 0x8c, 0x8c, 0x23, 0x3a, 0xb3, 0x2a, 0x2d,
	0xad, 0x5d, 0xeb, 0x6c, 0x66, 0xc9, 0x53, 0x85, 0x9b, 0x99, 0x60, 0x1f, 0x1a, 0xaa, 0xa4, 0x5e,
	0x94, 0x84, 0x8c, 0xf7, 0x6e, 0x55, 0x85, 0xdb, 0x6e, 0xb1, 0xe6, 0xcc, 0xc0, 0x2d, 0xb9, 0xe0,
	0x09, 0x6c, 0x2a, 0x59, 0x37, 0x61, 0x1f, 0x23, 0x2a, 0xe2, 0x80, 0x88, 0xd3, 0x2c, 0xc6, 0xc9,
	0x2d, 0xdc, 0xb2, 0x93, 0x7d, 0x00, 0x90, 0xcf, 0xa8, 0xb4, 0x86, 0x06, 0x18, 0x23, 0x6f, 0xac,
	0x96, 0xc0, 0x9f, 0xf6, 0x77, 0xad, 0xdc, 0x81, 0x1c, 0xcf, 0x74, 0xca, 0xc7, 0x23, 0x7d, 0x53,
	0x88, 0x08, 0xe6, 0x69, 0x70, 0x25, 0xd7, 0x68, 0xb8, 0xe2, 0x2d, 0xad, 0x27, 0x13, 0x72, 0xc1,
	0xc4, 0x16, 0x85, 0xb5, 0x80, 0x5c, 0x73, 0x14, 0xc4, 0xc2, 0xc1, 0x94, 0x1a, 0x05, 0xb1, 0x09,
	0x95, 0x33, 0x6f, 0x4c, 0xce, 0x03, 0x72, 0xa3, 0xb6, 0x96, 0x61, 0xfb, 0xeb, 0x3d, 0xc3, 0xe0,
	0x7b, 0x96, 0xe8, 0xdd, 0xe0, 0x48, 0x15, 0x95, 0x0b, 0xf0, 0x11, 0xd4, 0x25, 0x70, 0x82, 0x8b,
	0xab, 0xd0, 0x9b, 0xa6, 0x3c, 0x2b, 0x48, 0xd1, 0x86, 0x35, 0x29, 0xe9, 0x7e, 0xf6, 0x98, 0x47,
	0x15, 0xeb, 0x16, 0x64, 0xf6, 0xab, 0x9c, 0x01, 0xa5, 0xf9, 0xd5, 0x41, 0xef, 0x39, 0x2a, 0xb6,
	0xde, 0x73, 0x38, 0xee, 0x3b, 0x2a, 0x8a, 0xde, 0x77, 0x6c, 0x1b, 0x60, 0x10, 0x32, 0x97, 0x7c,
	0x4a, 0x48, 0xcc, 0x38, 0xe9, 0xcf, 0xbd, 0x49, 0x42, 0x54, 0x00, 0x09, 0xec, 0x9f, 0x1a, 0xe0,
	0x59, 0x14, 0x33, 0xd5, 0x63, 0x6a, 0xbc, 0x0f, 0x90, 0xa6, 0xcd, 0x3a, 0x9c, 0x93, 0x3c, 0x7c,
	0x41, 0x29, 0x91, 0x8d, 0x45, 0x22, 0x2f, 0x0c, 0xcc, 0x2c, 0x0e, 0x6c, 0xee, 0xf2, 0x96, 0x17,
	0x2e, 0xcf, 0xfe, 0xa5, 0xc1, 0xf6, 0x1b, 0x92, 0x56, 0x77, 0x1a, 0xc4, 0x59, 0x3b, 0x6d, 0xd8,
	0x38, 0x0d, 0xa6, 0x01, 0xeb, 0x72, 0x3e, 0xf2, 0x43, 0x4f, 0xcb, 0x2c, 0x8a, 0x39, 0x4b, 0xf8,
	0x36, 0x53, 0x96, 0xf0, 0x37, 0x97, 0x0d, 0x83, 0x2f, 0x44, 0x51, 0x44, 0xbc, 0x0b, 0x3d, 0x9b,
	0xa5, 0x9e, 0xf7, 0xa0, 0xfa, 0x96, 0xfa, 0x84, 0x8e, 0x66, 0xd7, 0x44, 0xd5, 0x99, 0x0b, 0xec,
	0x3e, 0xac, 0xf7, 0x29, 0x8d, 0xa8, 0x4b, 0xe2, 0xeb, 0x28, 0x8c, 0x09, 0xbe, 0x80, 0xaa, 0x10,
	0x88, 0xeb, 0xe1, 0xa5, 0xd5, 0x3b, 0x3b, 0xd9, 0xf5, 0xbc, 0x97, 0xbf, 0xc2, 0x20, 0x76, 0x73,
	0xc3, 0x27, 0x97, 0xb0, 0xbe, 0xa0, 0xc3, 0x0a, 0x98, 0x4e, 0x14, 0x92, 0xc6, 0x12, 0xee, 0xc0,
	0x86, 0x9a, 0x83, 0x13, 0xb1, 0xe3, 0x28, 0x09, 0xfd, 0xc6, 0xef, 0xdb, 0x3b, 0x0d, 0x2d, 0xd8,
	0x9c, 0xdb, 0xe0, 0xb1, 0x17, 0x4c, 0x88, 0xdf, 0xf8, 0xc3, 0x35, 0xbb, 0x72, 0xb7, 0x69, 0x0f,
	0x4a, 0xf5, 0xf7, 0xf6, 0x4e, 0xeb, 0xfc, 0xd0, 0xa1, 0xaa, 0x8a, 0x19, 0x9e, 0xe3, 0x6b, 0xa8,
	0xe7, 0x53, 0x3e, 0x9c, 0x0d, 0x7c, 0xcc, 0x3f, 0x72, 0x39, 0x85, 0x9a, 0x5b, 0xc5, 0xeb, 0x17,
	0x47, 0xbe, 0x84, 0x27, 0xf3, 0xee, 0x7c, 0x49, 0xb8, 0x9f, 0x59, 0xde, 0xbb, 0xbd, 0x07, 0x23,
	0x1d, 0x42, 0x6d, 0xae, 0x17, 0xfc, 0x3f, 0x33, 0x2b, 0x73, 0xb4, 0x99, 0x4f, 0x73, 0x71, 0xf0,
	0x2f, 0x61, 0x6d, 0xbe, 0x6b, 0x2c, 0x7f, 0x32, 0x1f, 0x72, 0xfd, 0xb0, 0x22, 0xfe, 0x48, 0x9e,
	0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x62, 0xb2, 0xcc, 0x82, 0x61, 0x06, 0x00, 0x00,
}
