// Code generated by protoc-gen-go. DO NOT EDIT.
// source: writing/writing.proto

// 内容创作模块

package writing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// --------------------------response  start-----------------------------
type WritingErrors int32

const (
	WritingErrors_None                  WritingErrors = 0
	WritingErrors_ArticleNotFound       WritingErrors = 3000001
	WritingErrors_PostArticleFailed     WritingErrors = 3000002
	WritingErrors_PostCategoryFailed    WritingErrors = 3000003
	WritingErrors_PutArticleFailed      WritingErrors = 3000004
	WritingErrors_OperationNotPermitted WritingErrors = 3000006
	WritingErrors_PostCommentFailed     WritingErrors = 3000007
	WritingErrors_DelCommentFailed      WritingErrors = 3000008
)

var WritingErrors_name = map[int32]string{
	0:       "None",
	3000001: "ArticleNotFound",
	3000002: "PostArticleFailed",
	3000003: "PostCategoryFailed",
	3000004: "PutArticleFailed",
	3000006: "OperationNotPermitted",
	3000007: "PostCommentFailed",
	3000008: "DelCommentFailed",
}

var WritingErrors_value = map[string]int32{
	"None":                  0,
	"ArticleNotFound":       3000001,
	"PostArticleFailed":     3000002,
	"PostCategoryFailed":    3000003,
	"PutArticleFailed":      3000004,
	"OperationNotPermitted": 3000006,
	"PostCommentFailed":     3000007,
	"DelCommentFailed":      3000008,
}

func (x WritingErrors) String() string {
	return proto.EnumName(WritingErrors_name, int32(x))
}

func (WritingErrors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ArticleInfo struct {
	Id                   int64       `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string      `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Summary              string      `protobuf:"bytes,3,opt,name=Summary,proto3" json:"Summary,omitempty"`
	Tags                 []*Tag      `protobuf:"bytes,4,rep,name=Tags,proto3" json:"Tags,omitempty"`
	CreatedAt            int64       `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Status               int64       `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	Content              string      `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`
	Category             *Category   `protobuf:"bytes,8,opt,name=Category,proto3" json:"Category,omitempty"`
	CountInfo            *CountInfo  `protobuf:"bytes,9,opt,name=CountInfo,proto3" json:"CountInfo,omitempty"`
	AuthorInfo           *AuthorInfo `protobuf:"bytes,10,opt,name=AuthorInfo,proto3" json:"AuthorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ArticleInfo) Reset()         { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()    {}
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{1}
}

func (m *ArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleInfo.Unmarshal(m, b)
}
func (m *ArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleInfo.Marshal(b, m, deterministic)
}
func (m *ArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleInfo.Merge(m, src)
}
func (m *ArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleInfo.Size(m)
}
func (m *ArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleInfo proto.InternalMessageInfo

func (m *ArticleInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleInfo) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ArticleInfo) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ArticleInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ArticleInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ArticleInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ArticleInfo) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *ArticleInfo) GetCountInfo() *CountInfo {
	if m != nil {
		return m.CountInfo
	}
	return nil
}

func (m *ArticleInfo) GetAuthorInfo() *AuthorInfo {
	if m != nil {
		return m.AuthorInfo
	}
	return nil
}

// Tag解构体
type Tag struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=Tag,proto3" json:"Tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{2}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// 数据统计信息
type CountInfo struct {
	Comment              int64    `protobuf:"varint,1,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Like                 int64    `protobuf:"varint,2,opt,name=Like,proto3" json:"Like,omitempty"`
	Collect              int64    `protobuf:"varint,3,opt,name=Collect,proto3" json:"Collect,omitempty"`
	DisLike              int64    `protobuf:"varint,4,opt,name=DisLike,proto3" json:"DisLike,omitempty"`
	PageView             int64    `protobuf:"varint,5,opt,name=PageView,proto3" json:"PageView,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountInfo) Reset()         { *m = CountInfo{} }
func (m *CountInfo) String() string { return proto.CompactTextString(m) }
func (*CountInfo) ProtoMessage()    {}
func (*CountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{3}
}

func (m *CountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountInfo.Unmarshal(m, b)
}
func (m *CountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountInfo.Marshal(b, m, deterministic)
}
func (m *CountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountInfo.Merge(m, src)
}
func (m *CountInfo) XXX_Size() int {
	return xxx_messageInfo_CountInfo.Size(m)
}
func (m *CountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CountInfo proto.InternalMessageInfo

func (m *CountInfo) GetComment() int64 {
	if m != nil {
		return m.Comment
	}
	return 0
}

func (m *CountInfo) GetLike() int64 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *CountInfo) GetCollect() int64 {
	if m != nil {
		return m.Collect
	}
	return 0
}

func (m *CountInfo) GetDisLike() int64 {
	if m != nil {
		return m.DisLike
	}
	return 0
}

func (m *CountInfo) GetPageView() int64 {
	if m != nil {
		return m.PageView
	}
	return 0
}

// 作者信息
type AuthorInfo struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorInfo) Reset()         { *m = AuthorInfo{} }
func (m *AuthorInfo) String() string { return proto.CompactTextString(m) }
func (*AuthorInfo) ProtoMessage()    {}
func (*AuthorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{4}
}

func (m *AuthorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorInfo.Unmarshal(m, b)
}
func (m *AuthorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorInfo.Marshal(b, m, deterministic)
}
func (m *AuthorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorInfo.Merge(m, src)
}
func (m *AuthorInfo) XXX_Size() int {
	return xxx_messageInfo_AuthorInfo.Size(m)
}
func (m *AuthorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorInfo proto.InternalMessageInfo

func (m *AuthorInfo) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *AuthorInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AuthorInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

// 文章类别
type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CN                   string   `protobuf:"bytes,2,opt,name=CN,proto3" json:"CN,omitempty"`
	EN                   string   `protobuf:"bytes,3,opt,name=EN,proto3" json:"EN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{5}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetCN() string {
	if m != nil {
		return m.CN
	}
	return ""
}

func (m *Category) GetEN() string {
	if m != nil {
		return m.EN
	}
	return ""
}

// --------------------------request  start------------------------------
// int参数请求
type IntRequest struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntRequest) Reset()         { *m = IntRequest{} }
func (m *IntRequest) String() string { return proto.CompactTextString(m) }
func (*IntRequest) ProtoMessage()    {}
func (*IntRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{6}
}

func (m *IntRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntRequest.Unmarshal(m, b)
}
func (m *IntRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntRequest.Marshal(b, m, deterministic)
}
func (m *IntRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntRequest.Merge(m, src)
}
func (m *IntRequest) XXX_Size() int {
	return xxx_messageInfo_IntRequest.Size(m)
}
func (m *IntRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IntRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IntRequest proto.InternalMessageInfo

func (m *IntRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PostArticleRequest struct {
	CategoryID           int64    `protobuf:"varint,1,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	AuthorUID            int64    `protobuf:"varint,4,opt,name=AuthorUID,proto3" json:"AuthorUID,omitempty"`
	Summary              string   `protobuf:"bytes,5,opt,name=Summary,proto3" json:"Summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostArticleRequest) Reset()         { *m = PostArticleRequest{} }
func (m *PostArticleRequest) String() string { return proto.CompactTextString(m) }
func (*PostArticleRequest) ProtoMessage()    {}
func (*PostArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{7}
}

func (m *PostArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostArticleRequest.Unmarshal(m, b)
}
func (m *PostArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostArticleRequest.Marshal(b, m, deterministic)
}
func (m *PostArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostArticleRequest.Merge(m, src)
}
func (m *PostArticleRequest) XXX_Size() int {
	return xxx_messageInfo_PostArticleRequest.Size(m)
}
func (m *PostArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostArticleRequest proto.InternalMessageInfo

func (m *PostArticleRequest) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *PostArticleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostArticleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostArticleRequest) GetAuthorUID() int64 {
	if m != nil {
		return m.AuthorUID
	}
	return 0
}

func (m *PostArticleRequest) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

type PutArticleRequest struct {
	PostID               int64    `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	AuthorUID            int64    `protobuf:"varint,4,opt,name=AuthorUID,proto3" json:"AuthorUID,omitempty"`
	Summary              string   `protobuf:"bytes,5,opt,name=Summary,proto3" json:"Summary,omitempty"`
	CategoryID           int64    `protobuf:"varint,6,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutArticleRequest) Reset()         { *m = PutArticleRequest{} }
func (m *PutArticleRequest) String() string { return proto.CompactTextString(m) }
func (*PutArticleRequest) ProtoMessage()    {}
func (*PutArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{8}
}

func (m *PutArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutArticleRequest.Unmarshal(m, b)
}
func (m *PutArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutArticleRequest.Marshal(b, m, deterministic)
}
func (m *PutArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutArticleRequest.Merge(m, src)
}
func (m *PutArticleRequest) XXX_Size() int {
	return xxx_messageInfo_PutArticleRequest.Size(m)
}
func (m *PutArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutArticleRequest proto.InternalMessageInfo

func (m *PutArticleRequest) GetPostID() int64 {
	if m != nil {
		return m.PostID
	}
	return 0
}

func (m *PutArticleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PutArticleRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PutArticleRequest) GetAuthorUID() int64 {
	if m != nil {
		return m.AuthorUID
	}
	return 0
}

func (m *PutArticleRequest) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *PutArticleRequest) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

type GetArticleListRequest struct {
	LimitAriticleID      int64    `protobuf:"varint,1,opt,name=LimitAriticleID,proto3" json:"LimitAriticleID,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	CategoryID           int64    `protobuf:"varint,4,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	OrderType            string   `protobuf:"bytes,5,opt,name=OrderType,proto3" json:"OrderType,omitempty"`
	UID                  int64    `protobuf:"varint,6,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleListRequest) Reset()         { *m = GetArticleListRequest{} }
func (m *GetArticleListRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleListRequest) ProtoMessage()    {}
func (*GetArticleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{9}
}

func (m *GetArticleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListRequest.Unmarshal(m, b)
}
func (m *GetArticleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListRequest.Merge(m, src)
}
func (m *GetArticleListRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleListRequest.Size(m)
}
func (m *GetArticleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListRequest proto.InternalMessageInfo

func (m *GetArticleListRequest) GetLimitAriticleID() int64 {
	if m != nil {
		return m.LimitAriticleID
	}
	return 0
}

func (m *GetArticleListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetArticleListRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetArticleListRequest) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *GetArticleListRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *GetArticleListRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type PostCommentToArticleRequest struct {
	PostID               int64    `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	ReplyCommentID       int64    `protobuf:"varint,3,opt,name=ReplyCommentID,proto3" json:"ReplyCommentID,omitempty"`
	CommentUID           int64    `protobuf:"varint,4,opt,name=CommentUID,proto3" json:"CommentUID,omitempty"`
	ReplyCommentUID      int64    `protobuf:"varint,5,opt,name=ReplyCommentUID,proto3" json:"ReplyCommentUID,omitempty"`
	AuthorUID            int64    `protobuf:"varint,6,opt,name=AuthorUID,proto3" json:"AuthorUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCommentToArticleRequest) Reset()         { *m = PostCommentToArticleRequest{} }
func (m *PostCommentToArticleRequest) String() string { return proto.CompactTextString(m) }
func (*PostCommentToArticleRequest) ProtoMessage()    {}
func (*PostCommentToArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{10}
}

func (m *PostCommentToArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCommentToArticleRequest.Unmarshal(m, b)
}
func (m *PostCommentToArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCommentToArticleRequest.Marshal(b, m, deterministic)
}
func (m *PostCommentToArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCommentToArticleRequest.Merge(m, src)
}
func (m *PostCommentToArticleRequest) XXX_Size() int {
	return xxx_messageInfo_PostCommentToArticleRequest.Size(m)
}
func (m *PostCommentToArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCommentToArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostCommentToArticleRequest proto.InternalMessageInfo

func (m *PostCommentToArticleRequest) GetPostID() int64 {
	if m != nil {
		return m.PostID
	}
	return 0
}

func (m *PostCommentToArticleRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *PostCommentToArticleRequest) GetReplyCommentID() int64 {
	if m != nil {
		return m.ReplyCommentID
	}
	return 0
}

func (m *PostCommentToArticleRequest) GetCommentUID() int64 {
	if m != nil {
		return m.CommentUID
	}
	return 0
}

func (m *PostCommentToArticleRequest) GetReplyCommentUID() int64 {
	if m != nil {
		return m.ReplyCommentUID
	}
	return 0
}

func (m *PostCommentToArticleRequest) GetAuthorUID() int64 {
	if m != nil {
		return m.AuthorUID
	}
	return 0
}

type DelCommentToArticleRequest struct {
	PostID               int64    `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	CommentID            int64    `protobuf:"varint,2,opt,name=CommentID,proto3" json:"CommentID,omitempty"`
	UID                  int64    `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCommentToArticleRequest) Reset()         { *m = DelCommentToArticleRequest{} }
func (m *DelCommentToArticleRequest) String() string { return proto.CompactTextString(m) }
func (*DelCommentToArticleRequest) ProtoMessage()    {}
func (*DelCommentToArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{11}
}

func (m *DelCommentToArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCommentToArticleRequest.Unmarshal(m, b)
}
func (m *DelCommentToArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCommentToArticleRequest.Marshal(b, m, deterministic)
}
func (m *DelCommentToArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCommentToArticleRequest.Merge(m, src)
}
func (m *DelCommentToArticleRequest) XXX_Size() int {
	return xxx_messageInfo_DelCommentToArticleRequest.Size(m)
}
func (m *DelCommentToArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCommentToArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelCommentToArticleRequest proto.InternalMessageInfo

func (m *DelCommentToArticleRequest) GetPostID() int64 {
	if m != nil {
		return m.PostID
	}
	return 0
}

func (m *DelCommentToArticleRequest) GetCommentID() int64 {
	if m != nil {
		return m.CommentID
	}
	return 0
}

func (m *DelCommentToArticleRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type GetCommentListOfArticleRequest struct {
	Page                 int64    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	PostID               int64    `protobuf:"varint,3,opt,name=PostID,proto3" json:"PostID,omitempty"`
	AuthorUID            int64    `protobuf:"varint,4,opt,name=AuthorUID,proto3" json:"AuthorUID,omitempty"`
	ReplyCommentUID      int64    `protobuf:"varint,5,opt,name=ReplyCommentUID,proto3" json:"ReplyCommentUID,omitempty"`
	CommentUID           int64    `protobuf:"varint,6,opt,name=CommentUID,proto3" json:"CommentUID,omitempty"`
	OrderType            string   `protobuf:"bytes,7,opt,name=OrderType,proto3" json:"OrderType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentListOfArticleRequest) Reset()         { *m = GetCommentListOfArticleRequest{} }
func (m *GetCommentListOfArticleRequest) String() string { return proto.CompactTextString(m) }
func (*GetCommentListOfArticleRequest) ProtoMessage()    {}
func (*GetCommentListOfArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{12}
}

func (m *GetCommentListOfArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentListOfArticleRequest.Unmarshal(m, b)
}
func (m *GetCommentListOfArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentListOfArticleRequest.Marshal(b, m, deterministic)
}
func (m *GetCommentListOfArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentListOfArticleRequest.Merge(m, src)
}
func (m *GetCommentListOfArticleRequest) XXX_Size() int {
	return xxx_messageInfo_GetCommentListOfArticleRequest.Size(m)
}
func (m *GetCommentListOfArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentListOfArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentListOfArticleRequest proto.InternalMessageInfo

func (m *GetCommentListOfArticleRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetCommentListOfArticleRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetCommentListOfArticleRequest) GetPostID() int64 {
	if m != nil {
		return m.PostID
	}
	return 0
}

func (m *GetCommentListOfArticleRequest) GetAuthorUID() int64 {
	if m != nil {
		return m.AuthorUID
	}
	return 0
}

func (m *GetCommentListOfArticleRequest) GetReplyCommentUID() int64 {
	if m != nil {
		return m.ReplyCommentUID
	}
	return 0
}

func (m *GetCommentListOfArticleRequest) GetCommentUID() int64 {
	if m != nil {
		return m.CommentUID
	}
	return 0
}

func (m *GetCommentListOfArticleRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

type DelCommentListOfArticleRequest struct {
	PostID               int64    `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty"`
	CommentUID           int64    `protobuf:"varint,2,opt,name=CommentUID,proto3" json:"CommentUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCommentListOfArticleRequest) Reset()         { *m = DelCommentListOfArticleRequest{} }
func (m *DelCommentListOfArticleRequest) String() string { return proto.CompactTextString(m) }
func (*DelCommentListOfArticleRequest) ProtoMessage()    {}
func (*DelCommentListOfArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{13}
}

func (m *DelCommentListOfArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCommentListOfArticleRequest.Unmarshal(m, b)
}
func (m *DelCommentListOfArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCommentListOfArticleRequest.Marshal(b, m, deterministic)
}
func (m *DelCommentListOfArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCommentListOfArticleRequest.Merge(m, src)
}
func (m *DelCommentListOfArticleRequest) XXX_Size() int {
	return xxx_messageInfo_DelCommentListOfArticleRequest.Size(m)
}
func (m *DelCommentListOfArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCommentListOfArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelCommentListOfArticleRequest proto.InternalMessageInfo

func (m *DelCommentListOfArticleRequest) GetPostID() int64 {
	if m != nil {
		return m.PostID
	}
	return 0
}

func (m *DelCommentListOfArticleRequest) GetCommentUID() int64 {
	if m != nil {
		return m.CommentUID
	}
	return 0
}

type ErrorResponse struct {
	ErrorInfo            WritingErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=writing.WritingErrors" json:"ErrorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{14}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetErrorInfo() WritingErrors {
	if m != nil {
		return m.ErrorInfo
	}
	return WritingErrors_None
}

type ArticleListResponse struct {
	Articles             []*ArticleInfo `protobuf:"bytes,1,rep,name=Articles,proto3" json:"Articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ArticleListResponse) Reset()         { *m = ArticleListResponse{} }
func (m *ArticleListResponse) String() string { return proto.CompactTextString(m) }
func (*ArticleListResponse) ProtoMessage()    {}
func (*ArticleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{15}
}

func (m *ArticleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleListResponse.Unmarshal(m, b)
}
func (m *ArticleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleListResponse.Marshal(b, m, deterministic)
}
func (m *ArticleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleListResponse.Merge(m, src)
}
func (m *ArticleListResponse) XXX_Size() int {
	return xxx_messageInfo_ArticleListResponse.Size(m)
}
func (m *ArticleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleListResponse proto.InternalMessageInfo

func (m *ArticleListResponse) GetArticles() []*ArticleInfo {
	if m != nil {
		return m.Articles
	}
	return nil
}

type CategoriesResponse struct {
	List                 []*Category `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CategoriesResponse) Reset()         { *m = CategoriesResponse{} }
func (m *CategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*CategoriesResponse) ProtoMessage()    {}
func (*CategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db9b9589ec5f9fbc, []int{16}
}

func (m *CategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoriesResponse.Unmarshal(m, b)
}
func (m *CategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoriesResponse.Marshal(b, m, deterministic)
}
func (m *CategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoriesResponse.Merge(m, src)
}
func (m *CategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_CategoriesResponse.Size(m)
}
func (m *CategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CategoriesResponse proto.InternalMessageInfo

func (m *CategoriesResponse) GetList() []*Category {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("writing.WritingErrors", WritingErrors_name, WritingErrors_value)
	proto.RegisterType((*Empty)(nil), "writing.Empty")
	proto.RegisterType((*ArticleInfo)(nil), "writing.ArticleInfo")
	proto.RegisterType((*Tag)(nil), "writing.Tag")
	proto.RegisterType((*CountInfo)(nil), "writing.CountInfo")
	proto.RegisterType((*AuthorInfo)(nil), "writing.AuthorInfo")
	proto.RegisterType((*Category)(nil), "writing.Category")
	proto.RegisterType((*IntRequest)(nil), "writing.IntRequest")
	proto.RegisterType((*PostArticleRequest)(nil), "writing.PostArticleRequest")
	proto.RegisterType((*PutArticleRequest)(nil), "writing.PutArticleRequest")
	proto.RegisterType((*GetArticleListRequest)(nil), "writing.GetArticleListRequest")
	proto.RegisterType((*PostCommentToArticleRequest)(nil), "writing.PostCommentToArticleRequest")
	proto.RegisterType((*DelCommentToArticleRequest)(nil), "writing.DelCommentToArticleRequest")
	proto.RegisterType((*GetCommentListOfArticleRequest)(nil), "writing.GetCommentListOfArticleRequest")
	proto.RegisterType((*DelCommentListOfArticleRequest)(nil), "writing.DelCommentListOfArticleRequest")
	proto.RegisterType((*ErrorResponse)(nil), "writing.ErrorResponse")
	proto.RegisterType((*ArticleListResponse)(nil), "writing.ArticleListResponse")
	proto.RegisterType((*CategoriesResponse)(nil), "writing.CategoriesResponse")
}

func init() { proto.RegisterFile("writing/writing.proto", fileDescriptor_db9b9589ec5f9fbc) }

var fileDescriptor_db9b9589ec5f9fbc = []byte{
	// 1067 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x49, 0x6f, 0xdb, 0x46,
	0x14, 0x36, 0x29, 0x59, 0x96, 0x9e, 0x62, 0x45, 0x1e, 0x2f, 0x61, 0x65, 0xc1, 0x10, 0xa6, 0x4b,
	0x84, 0x02, 0x4d, 0x03, 0xa7, 0x87, 0xae, 0x40, 0x15, 0x59, 0x31, 0x04, 0x18, 0xb2, 0x40, 0x2b,
	0x6e, 0xd1, 0x1b, 0x6b, 0x4e, 0x54, 0x22, 0x12, 0xa9, 0x92, 0xc3, 0x06, 0xea, 0x3f, 0xe8, 0x21,
	0xff, 0xa0, 0xff, 0xa2, 0x07, 0xa3, 0xc7, 0x2e, 0x68, 0x7b, 0xec, 0xa5, 0xe7, 0xde, 0xfa, 0x3b,
	0x8a, 0x19, 0x0e, 0x67, 0x86, 0x94, 0x68, 0xb8, 0x3d, 0xe4, 0x24, 0xbe, 0x65, 0xde, 0xf2, 0xbd,
	0x6f, 0xde, 0xd8, 0xb0, 0xff, 0x22, 0xf4, 0xa8, 0xe7, 0x4f, 0xdf, 0x15, 0xbf, 0x0f, 0x16, 0x61,
	0x40, 0x03, 0xb4, 0x25, 0x44, 0xbc, 0x05, 0x9b, 0x83, 0xf9, 0x82, 0x2e, 0xf1, 0x5f, 0x26, 0xd4,
	0x7b, 0x21, 0xf5, 0xae, 0x66, 0x64, 0xe8, 0x3f, 0x0b, 0x50, 0x03, 0xcc, 0xa1, 0x6b, 0x19, 0x1d,
	0xa3, 0x5b, 0xb2, 0xcd, 0xa1, 0x8b, 0xf6, 0x60, 0x73, 0xe2, 0xd1, 0x19, 0xb1, 0xcc, 0x8e, 0xd1,
	0xad, 0xd9, 0x89, 0x80, 0x2c, 0xd8, 0xba, 0x88, 0xe7, 0x73, 0x27, 0x5c, 0x5a, 0x25, 0xae, 0x4f,
	0x45, 0xd4, 0x81, 0xf2, 0xc4, 0x99, 0x46, 0x56, 0xb9, 0x53, 0xea, 0xd6, 0x8f, 0xef, 0x3c, 0x48,
	0xf3, 0x4f, 0x9c, 0xa9, 0xcd, 0x2d, 0xa8, 0x0d, 0xb5, 0x7e, 0x48, 0x1c, 0x4a, 0xdc, 0x1e, 0xb5,
	0x36, 0x79, 0x22, 0xa5, 0x40, 0x07, 0x50, 0xb9, 0xa0, 0x0e, 0x8d, 0x23, 0xab, 0xc2, 0x4d, 0x42,
	0x62, 0x19, 0xfb, 0x81, 0x4f, 0x89, 0x4f, 0xad, 0xad, 0x24, 0xa3, 0x10, 0xd1, 0x3b, 0x50, 0xed,
	0x3b, 0x94, 0x4c, 0x83, 0x70, 0x69, 0x55, 0x3b, 0x46, 0xb7, 0x7e, 0xbc, 0x23, 0xb3, 0xa6, 0x06,
	0x5b, 0xba, 0xa0, 0x87, 0x50, 0xeb, 0x07, 0xb1, 0x4f, 0x59, 0xb7, 0x56, 0x8d, 0xfb, 0x23, 0xe5,
	0x9f, 0x5a, 0x6c, 0xe5, 0x84, 0x1e, 0x01, 0xf4, 0x62, 0xfa, 0x55, 0x10, 0xf2, 0x23, 0xc0, 0x8f,
	0xec, 0xca, 0x23, 0xca, 0x64, 0x6b, 0x6e, 0xf8, 0x3e, 0x94, 0x26, 0xce, 0x74, 0x05, 0xce, 0x26,
	0x57, 0x0b, 0x30, 0xd9, 0x27, 0xfe, 0xce, 0xd0, 0x0a, 0x4a, 0xda, 0x9c, 0xcf, 0x59, 0x9b, 0xc9,
	0xa1, 0x54, 0x44, 0x08, 0xca, 0x67, 0xde, 0xf3, 0x64, 0x0e, 0x25, 0x9b, 0x7f, 0x27, 0xde, 0xb3,
	0x19, 0xb9, 0xa2, 0x7c, 0x0c, 0xdc, 0x9b, 0x8b, 0xcc, 0x72, 0xe2, 0x45, 0xfc, 0x40, 0x39, 0xb1,
	0x08, 0x11, 0xb5, 0xa0, 0x3a, 0x76, 0xa6, 0xe4, 0xd2, 0x23, 0x2f, 0x04, 0xfa, 0x52, 0xc6, 0xb6,
	0xde, 0x29, 0xab, 0xf5, 0xe9, 0xf0, 0x44, 0xd4, 0xc1, 0x3e, 0xd9, 0xd9, 0x91, 0x77, 0xf5, 0xdc,
	0x77, 0xe6, 0x29, 0x1f, 0xa4, 0xcc, 0x06, 0xd7, 0xfb, 0xc6, 0xa1, 0x4e, 0x28, 0x18, 0x21, 0x24,
	0xfc, 0xa1, 0x1a, 0xcf, 0x0a, 0x1a, 0x0d, 0x30, 0xfb, 0x23, 0x11, 0xc9, 0xec, 0x8f, 0x98, 0x3c,
	0x18, 0x89, 0xf3, 0xe6, 0x60, 0x84, 0x31, 0xc0, 0xd0, 0xa7, 0x36, 0xf9, 0x3a, 0x26, 0x11, 0x65,
	0x54, 0xbc, 0x74, 0x66, 0x31, 0x11, 0x01, 0x12, 0x01, 0x7f, 0x6f, 0x00, 0x1a, 0x07, 0x11, 0x15,
	0x24, 0x4e, 0x9d, 0x8f, 0x00, 0xd2, 0xb4, 0xb2, 0x07, 0x4d, 0x53, 0xcc, 0xeb, 0x94, 0x65, 0xa5,
	0x2c, 0xcb, 0xda, 0x50, 0x4b, 0xa0, 0x61, 0x90, 0x24, 0x90, 0x2a, 0x85, 0x7e, 0x1f, 0x36, 0x33,
	0xf7, 0x01, 0xff, 0x60, 0xc0, 0xce, 0x38, 0xce, 0x57, 0x77, 0x00, 0x15, 0x56, 0xb3, 0xac, 0x4c,
	0x48, 0xaf, 0xaa, 0xaa, 0x1c, 0x3a, 0x95, 0x3c, 0x3a, 0xf8, 0x47, 0x03, 0xf6, 0x4f, 0x49, 0x5a,
	0xf5, 0x99, 0x17, 0xc9, 0x21, 0x74, 0xe1, 0xee, 0x99, 0x37, 0xf7, 0x68, 0x8f, 0xd1, 0x9f, 0x2d,
	0x8d, 0xb4, 0x85, 0xbc, 0x9a, 0x11, 0x96, 0x11, 0x2b, 0x25, 0x2c, 0xfb, 0x66, 0xba, 0x0b, 0xef,
	0x5b, 0x22, 0xd8, 0xca, 0xbf, 0x73, 0xb5, 0x94, 0x57, 0x26, 0xd5, 0x86, 0xda, 0x79, 0xe8, 0x92,
	0x70, 0xb2, 0x5c, 0x10, 0xd1, 0x87, 0x52, 0xa4, 0x24, 0xad, 0x48, 0x92, 0xe2, 0xbf, 0x0d, 0x38,
	0x64, 0x70, 0x8a, 0x8b, 0x33, 0x09, 0x6e, 0x89, 0xbd, 0x76, 0xf5, 0xcc, 0x14, 0xe5, 0xe4, 0xea,
	0xbd, 0x05, 0x0d, 0x9b, 0x2c, 0x66, 0x4b, 0x21, 0x0f, 0x4f, 0x44, 0xfd, 0x39, 0x2d, 0xef, 0x24,
	0x11, 0x9e, 0x6a, 0x9d, 0x48, 0x0d, 0xc3, 0x4e, 0x3f, 0xc1, 0x9c, 0x92, 0x1b, 0x98, 0x57, 0x67,
	0xe7, 0x5a, 0xc9, 0xcd, 0x15, 0xbb, 0xd0, 0x3a, 0x21, 0xb3, 0xff, 0xda, 0x1f, 0xdb, 0xbb, 0xb2,
	0x01, 0x53, 0xec, 0x5d, 0x59, 0xbb, 0xc0, 0xb1, 0xa4, 0x70, 0xfc, 0xc7, 0x80, 0xa3, 0x53, 0x92,
	0xc2, 0xc8, 0x38, 0x70, 0xfe, 0x2c, 0x97, 0x2a, 0x1d, 0xb1, 0xb1, 0x66, 0xc4, 0xa6, 0x36, 0x62,
	0x55, 0x52, 0x29, 0x5f, 0xd2, 0x0d, 0xf4, 0xbd, 0x3d, 0x5c, 0x59, 0xe0, 0x2b, 0x2b, 0xc0, 0x67,
	0x28, 0xb4, 0x95, 0xa3, 0x10, 0xfe, 0x1c, 0x8e, 0x14, 0x9c, 0x6b, 0xfb, 0x2c, 0x82, 0x34, 0x9b,
	0xd7, 0xcc, 0xe7, 0xc5, 0x03, 0xd8, 0x1e, 0x84, 0x61, 0x10, 0xda, 0x24, 0x5a, 0x04, 0x7e, 0x44,
	0xd0, 0x7b, 0x50, 0xe3, 0x0a, 0xfe, 0x92, 0xb0, 0x58, 0x8d, 0xe3, 0x03, 0xf9, 0x92, 0x7c, 0x96,
	0xfc, 0x72, 0x87, 0xc8, 0x56, 0x8e, 0xf8, 0x14, 0x76, 0x33, 0x37, 0x51, 0x04, 0x7b, 0x08, 0x55,
	0xa1, 0x8e, 0x2c, 0x83, 0x3f, 0xb7, 0x7b, 0xea, 0x55, 0x52, 0x4f, 0xba, 0x2d, 0xbd, 0xf0, 0x47,
	0x80, 0xc4, 0xc5, 0xf2, 0x48, 0x24, 0xe3, 0xbc, 0xc9, 0x5e, 0x96, 0x88, 0x8a, 0x18, 0x6b, 0x1e,
	0x4f, 0x6e, 0x7e, 0xfb, 0x4f, 0x03, 0xb6, 0x33, 0x25, 0xa2, 0x2a, 0x94, 0x47, 0x81, 0x4f, 0x9a,
	0x1b, 0xe8, 0x00, 0xee, 0x8a, 0x24, 0xa3, 0x80, 0x3e, 0x09, 0x62, 0xdf, 0x6d, 0xfe, 0xf4, 0xf2,
	0xda, 0x40, 0x16, 0xec, 0x68, 0xbb, 0xf9, 0x89, 0xe3, 0xcd, 0x88, 0xdb, 0xfc, 0x99, 0x59, 0x5e,
	0x4b, 0xb6, 0x76, 0x9a, 0x43, 0x98, 0x7e, 0x61, 0xa6, 0x7b, 0xd0, 0x54, 0x1b, 0x53, 0x18, 0x7e,
	0x65, 0x86, 0x36, 0xec, 0x9f, 0x2f, 0x48, 0xe8, 0x50, 0x2f, 0xf0, 0x47, 0x01, 0x1d, 0x93, 0x70,
	0xee, 0x51, 0x4a, 0xdc, 0xe6, 0x6f, 0x5a, 0x2e, 0x01, 0xbf, 0x38, 0xf7, 0xbb, 0x08, 0xa8, 0x06,
	0x2c, 0x0c, 0x7f, 0xbc, 0xbc, 0x36, 0x8e, 0xaf, 0x2b, 0x50, 0x13, 0xdd, 0x5e, 0x5c, 0xa2, 0x4f,
	0xa0, 0xa1, 0x76, 0xde, 0xe3, 0xe5, 0xd0, 0x45, 0xea, 0x95, 0x57, 0xcf, 0x50, 0x6b, 0x2d, 0xc8,
	0x78, 0x03, 0x8d, 0xf5, 0xe3, 0x0c, 0x31, 0x74, 0x24, 0x3d, 0xd7, 0xee, 0xd2, 0x56, 0x3b, 0x1f,
	0x49, 0x1f, 0x2f, 0xde, 0x40, 0x8f, 0xa1, 0xae, 0xa1, 0x87, 0x0e, 0xa5, 0xfb, 0xea, 0x7b, 0xd7,
	0x52, 0x34, 0xca, 0x32, 0xee, 0x53, 0x00, 0x05, 0x26, 0x6a, 0xa9, 0x10, 0xf1, 0x6d, 0x23, 0x7c,
	0x00, 0x77, 0xf4, 0x49, 0xa1, 0x55, 0x82, 0x14, 0x1e, 0xfd, 0x18, 0xb6, 0xd9, 0x06, 0x91, 0x94,
	0x43, 0x0d, 0xe5, 0xc8, 0xfe, 0xfa, 0x6c, 0x1d, 0xe6, 0x63, 0xe9, 0xbc, 0x7c, 0x1f, 0xea, 0xe3,
	0xf8, 0x7f, 0xe5, 0x9d, 0xc0, 0xde, 0xba, 0x17, 0x00, 0xbd, 0x91, 0x41, 0xb0, 0x60, 0x81, 0x16,
	0x46, 0xb5, 0x61, 0x77, 0xcd, 0xda, 0x45, 0xaf, 0x4b, 0xf7, 0xe2, 0xa5, 0x5c, 0x18, 0xf3, 0x0b,
	0xb8, 0x57, 0xb0, 0x63, 0xd1, 0x7d, 0x9d, 0x3d, 0x37, 0x6c, 0xa7, 0x9b, 0x62, 0x17, 0xec, 0x35,
	0x2d, 0xf6, 0xcd, 0x9b, 0xaf, 0x28, 0xf6, 0x97, 0x15, 0xfe, 0xff, 0xc4, 0xa3, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x65, 0x92, 0x4b, 0xb7, 0x68, 0x0c, 0x00, 0x00,
}
