// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pay/pay.proto

package pay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayErrors int32

const (
	PayErrors_None        PayErrors = 0
	PayErrors_PayNotFound PayErrors = 2000001
)

var PayErrors_name = map[int32]string{
	0:       "None",
	2000001: "PayNotFound",
}

var PayErrors_value = map[string]int32{
	"None":        0,
	"PayNotFound": 2000001,
}

func (x PayErrors) String() string {
	return proto.EnumName(PayErrors_name, int32(x))
}

func (PayErrors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{0}
}

type UIDInput struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UIDInput) Reset()         { *m = UIDInput{} }
func (m *UIDInput) String() string { return proto.CompactTextString(m) }
func (*UIDInput) ProtoMessage()    {}
func (*UIDInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{0}
}

func (m *UIDInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UIDInput.Unmarshal(m, b)
}
func (m *UIDInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UIDInput.Marshal(b, m, deterministic)
}
func (m *UIDInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UIDInput.Merge(m, src)
}
func (m *UIDInput) XXX_Size() int {
	return xxx_messageInfo_UIDInput.Size(m)
}
func (m *UIDInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UIDInput.DiscardUnknown(m)
}

var xxx_messageInfo_UIDInput proto.InternalMessageInfo

func (m *UIDInput) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type PayWay struct {
	PayWayID             int64    `protobuf:"varint,1,opt,name=PayWayID,proto3" json:"PayWayID,omitempty"`
	PayType              string   `protobuf:"bytes,2,opt,name=PayType,proto3" json:"PayType,omitempty"`
	PayValue             string   `protobuf:"bytes,3,opt,name=PayValue,proto3" json:"PayValue,omitempty"`
	PayDesc              string   `protobuf:"bytes,4,opt,name=PayDesc,proto3" json:"PayDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayWay) Reset()         { *m = PayWay{} }
func (m *PayWay) String() string { return proto.CompactTextString(m) }
func (*PayWay) ProtoMessage()    {}
func (*PayWay) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{1}
}

func (m *PayWay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayWay.Unmarshal(m, b)
}
func (m *PayWay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayWay.Marshal(b, m, deterministic)
}
func (m *PayWay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayWay.Merge(m, src)
}
func (m *PayWay) XXX_Size() int {
	return xxx_messageInfo_PayWay.Size(m)
}
func (m *PayWay) XXX_DiscardUnknown() {
	xxx_messageInfo_PayWay.DiscardUnknown(m)
}

var xxx_messageInfo_PayWay proto.InternalMessageInfo

func (m *PayWay) GetPayWayID() int64 {
	if m != nil {
		return m.PayWayID
	}
	return 0
}

func (m *PayWay) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *PayWay) GetPayValue() string {
	if m != nil {
		return m.PayValue
	}
	return ""
}

func (m *PayWay) GetPayDesc() string {
	if m != nil {
		return m.PayDesc
	}
	return ""
}

type CreateUserPayWayRequest struct {
	PayType              string   `protobuf:"bytes,1,opt,name=PayType,proto3" json:"PayType,omitempty"`
	PayValue             string   `protobuf:"bytes,2,opt,name=PayValue,proto3" json:"PayValue,omitempty"`
	PayDesc              string   `protobuf:"bytes,3,opt,name=PayDesc,proto3" json:"PayDesc,omitempty"`
	UID                  int64    `protobuf:"varint,4,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserPayWayRequest) Reset()         { *m = CreateUserPayWayRequest{} }
func (m *CreateUserPayWayRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserPayWayRequest) ProtoMessage()    {}
func (*CreateUserPayWayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{2}
}

func (m *CreateUserPayWayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserPayWayRequest.Unmarshal(m, b)
}
func (m *CreateUserPayWayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserPayWayRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserPayWayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserPayWayRequest.Merge(m, src)
}
func (m *CreateUserPayWayRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserPayWayRequest.Size(m)
}
func (m *CreateUserPayWayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserPayWayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserPayWayRequest proto.InternalMessageInfo

func (m *CreateUserPayWayRequest) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *CreateUserPayWayRequest) GetPayValue() string {
	if m != nil {
		return m.PayValue
	}
	return ""
}

func (m *CreateUserPayWayRequest) GetPayDesc() string {
	if m != nil {
		return m.PayDesc
	}
	return ""
}

func (m *CreateUserPayWayRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type DeleteUserPayWayRequest struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	PayWayID             int64    `protobuf:"varint,2,opt,name=PayWayID,proto3" json:"PayWayID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserPayWayRequest) Reset()         { *m = DeleteUserPayWayRequest{} }
func (m *DeleteUserPayWayRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserPayWayRequest) ProtoMessage()    {}
func (*DeleteUserPayWayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{3}
}

func (m *DeleteUserPayWayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserPayWayRequest.Unmarshal(m, b)
}
func (m *DeleteUserPayWayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserPayWayRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserPayWayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserPayWayRequest.Merge(m, src)
}
func (m *DeleteUserPayWayRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserPayWayRequest.Size(m)
}
func (m *DeleteUserPayWayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserPayWayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserPayWayRequest proto.InternalMessageInfo

func (m *DeleteUserPayWayRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *DeleteUserPayWayRequest) GetPayWayID() int64 {
	if m != nil {
		return m.PayWayID
	}
	return 0
}

type PutUserPayWayRequest struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	PayWayID             int64    `protobuf:"varint,2,opt,name=PayWayID,proto3" json:"PayWayID,omitempty"`
	PayType              string   `protobuf:"bytes,3,opt,name=PayType,proto3" json:"PayType,omitempty"`
	PayValue             string   `protobuf:"bytes,4,opt,name=PayValue,proto3" json:"PayValue,omitempty"`
	PayDesc              string   `protobuf:"bytes,5,opt,name=PayDesc,proto3" json:"PayDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUserPayWayRequest) Reset()         { *m = PutUserPayWayRequest{} }
func (m *PutUserPayWayRequest) String() string { return proto.CompactTextString(m) }
func (*PutUserPayWayRequest) ProtoMessage()    {}
func (*PutUserPayWayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{4}
}

func (m *PutUserPayWayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUserPayWayRequest.Unmarshal(m, b)
}
func (m *PutUserPayWayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUserPayWayRequest.Marshal(b, m, deterministic)
}
func (m *PutUserPayWayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUserPayWayRequest.Merge(m, src)
}
func (m *PutUserPayWayRequest) XXX_Size() int {
	return xxx_messageInfo_PutUserPayWayRequest.Size(m)
}
func (m *PutUserPayWayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUserPayWayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutUserPayWayRequest proto.InternalMessageInfo

func (m *PutUserPayWayRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *PutUserPayWayRequest) GetPayWayID() int64 {
	if m != nil {
		return m.PayWayID
	}
	return 0
}

func (m *PutUserPayWayRequest) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *PutUserPayWayRequest) GetPayValue() string {
	if m != nil {
		return m.PayValue
	}
	return ""
}

func (m *PutUserPayWayRequest) GetPayDesc() string {
	if m != nil {
		return m.PayDesc
	}
	return ""
}

type UserPayWays struct {
	PayWays              []*PayWay `protobuf:"bytes,1,rep,name=PayWays,proto3" json:"PayWays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserPayWays) Reset()         { *m = UserPayWays{} }
func (m *UserPayWays) String() string { return proto.CompactTextString(m) }
func (*UserPayWays) ProtoMessage()    {}
func (*UserPayWays) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{5}
}

func (m *UserPayWays) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPayWays.Unmarshal(m, b)
}
func (m *UserPayWays) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPayWays.Marshal(b, m, deterministic)
}
func (m *UserPayWays) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPayWays.Merge(m, src)
}
func (m *UserPayWays) XXX_Size() int {
	return xxx_messageInfo_UserPayWays.Size(m)
}
func (m *UserPayWays) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPayWays.DiscardUnknown(m)
}

var xxx_messageInfo_UserPayWays proto.InternalMessageInfo

func (m *UserPayWays) GetPayWays() []*PayWay {
	if m != nil {
		return m.PayWays
	}
	return nil
}

type ErrorResponse struct {
	ErrorInfo            PayErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=pay.PayErrors" json:"ErrorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{6}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetErrorInfo() PayErrors {
	if m != nil {
		return m.ErrorInfo
	}
	return PayErrors_None
}

func init() {
	proto.RegisterEnum("pay.PayErrors", PayErrors_name, PayErrors_value)
	proto.RegisterType((*UIDInput)(nil), "pay.UIDInput")
	proto.RegisterType((*PayWay)(nil), "pay.PayWay")
	proto.RegisterType((*CreateUserPayWayRequest)(nil), "pay.CreateUserPayWayRequest")
	proto.RegisterType((*DeleteUserPayWayRequest)(nil), "pay.DeleteUserPayWayRequest")
	proto.RegisterType((*PutUserPayWayRequest)(nil), "pay.PutUserPayWayRequest")
	proto.RegisterType((*UserPayWays)(nil), "pay.UserPayWays")
	proto.RegisterType((*ErrorResponse)(nil), "pay.ErrorResponse")
}

func init() { proto.RegisterFile("pay/pay.proto", fileDescriptor_587e2c2585dcd479) }

var fileDescriptor_587e2c2585dcd479 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0x6d, 0x3e, 0xda, 0xd7, 0xde, 0x90, 0x92, 0x37, 0x3c, 0x68, 0x5e, 0xe9, 0xa2, 0x04, 0x84,
	0x20, 0xd2, 0x42, 0x75, 0x2b, 0x08, 0xc6, 0x96, 0x6c, 0x4a, 0x88, 0xb6, 0xae, 0x47, 0x1d, 0x57,
	0x25, 0x33, 0x26, 0x93, 0xc5, 0xe8, 0xca, 0xa5, 0xae, 0xfd, 0xc1, 0x92, 0xc9, 0x57, 0x53, 0x9b,
	0x95, 0xbb, 0xb9, 0x73, 0xef, 0x3d, 0x67, 0xce, 0xc9, 0x09, 0x98, 0x0c, 0x8b, 0x39, 0xc3, 0x62,
	0xc6, 0x62, 0xca, 0x29, 0xd2, 0x18, 0x16, 0xce, 0x04, 0xfa, 0x1b, 0xdf, 0xf3, 0x23, 0x96, 0x72,
	0x64, 0x81, 0xb6, 0xf1, 0x3d, 0x5b, 0x99, 0x2a, 0xae, 0x16, 0x66, 0x47, 0x87, 0x43, 0x2f, 0xc0,
	0xe2, 0x1e, 0x0b, 0x34, 0x86, 0x7e, 0x7e, 0xaa, 0x06, 0xaa, 0x1a, 0xd9, 0xf0, 0x27, 0xc0, 0xe2,
	0x4e, 0x30, 0x62, 0xab, 0x53, 0xc5, 0x1d, 0x84, 0x65, 0x59, 0x6c, 0x6d, 0xf1, 0x2e, 0x25, 0xb6,
	0x26, 0x5b, 0x55, 0x5d, 0x6c, 0x79, 0x24, 0x79, 0xb4, 0xf5, 0x6a, 0x2b, 0x2b, 0x9d, 0x37, 0x18,
	0x5d, 0xc7, 0x04, 0x73, 0xb2, 0x49, 0x48, 0x9c, 0xb3, 0x84, 0xe4, 0x25, 0x25, 0x09, 0xdf, 0xa7,
	0x52, 0xda, 0xa9, 0xd4, 0x76, 0x2a, 0xad, 0x41, 0x55, 0x4a, 0xd6, 0x6b, 0xc9, 0x2b, 0x18, 0x79,
	0x64, 0x47, 0x8e, 0x91, 0xff, 0xf0, 0xa7, 0xe1, 0x8a, 0xda, 0x74, 0xc5, 0xf9, 0x52, 0xe0, 0x5f,
	0x90, 0xf2, 0x5f, 0xc2, 0xec, 0x2b, 0xd6, 0xda, 0x15, 0xeb, 0xed, 0x8a, 0xbb, 0x4d, 0x73, 0x2f,
	0xc0, 0xa8, 0x9f, 0x94, 0xa0, 0x13, 0x39, 0x98, 0x1d, 0x6d, 0x65, 0xaa, 0xb9, 0xc6, 0xc2, 0x98,
	0x65, 0x09, 0x29, 0x5e, 0x5c, 0xf6, 0x9c, 0x4b, 0x30, 0x6f, 0xe2, 0x98, 0xc6, 0x21, 0x49, 0x18,
	0x8d, 0x12, 0x82, 0xce, 0x60, 0x20, 0x2f, 0xfc, 0xe8, 0x99, 0x4a, 0x29, 0xc3, 0xc5, 0xb0, 0xdc,
	0x94, 0x8d, 0x24, 0xac, 0x07, 0x4e, 0x5d, 0x18, 0x54, 0xf7, 0xa8, 0x0f, 0xfa, 0x9a, 0x46, 0xc4,
	0xea, 0xa0, 0xbf, 0x60, 0x04, 0x58, 0xac, 0x29, 0x5f, 0xd2, 0x34, 0x7a, 0xb2, 0xde, 0x3f, 0x5e,
	0x17, 0x9f, 0x2a, 0x74, 0x19, 0x16, 0xb7, 0x5b, 0x34, 0x07, 0x58, 0x11, 0x1e, 0x60, 0x91, 0x21,
	0x20, 0x53, 0x82, 0x97, 0x51, 0x1d, 0x5b, 0x79, 0x59, 0x0b, 0x71, 0x3a, 0x68, 0x09, 0xd6, 0x61,
	0x6c, 0xd0, 0x44, 0xce, 0xb5, 0xa4, 0x69, 0x8c, 0x64, 0xb7, 0x21, 0x2c, 0xc7, 0x39, 0x4c, 0x40,
	0x81, 0xd3, 0x12, 0x8c, 0x16, 0x9c, 0x2b, 0x30, 0x1b, 0xdf, 0x1f, 0xfd, 0xcf, 0x0d, 0x3a, 0x92,
	0x89, 0xe3, 0x08, 0x0f, 0x3d, 0xf9, 0xa3, 0x9e, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x1c,
	0x7d, 0x18, 0xb9, 0x03, 0x00, 0x00,
}
