// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pay/pay.proto

package pay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayErrors int32

const (
	PayErrors_None                  PayErrors = 0
	PayErrors_PayWayNotFound        PayErrors = 2000001
	PayErrors_PayWayOperationFailed PayErrors = 2000002
	PayErrors_CreateOrderFailed     PayErrors = 2000003
	PayErrors_UpdateOrderFailed     PayErrors = 2000004
)

var PayErrors_name = map[int32]string{
	0:       "None",
	2000001: "PayWayNotFound",
	2000002: "PayWayOperationFailed",
	2000003: "CreateOrderFailed",
	2000004: "UpdateOrderFailed",
}

var PayErrors_value = map[string]int32{
	"None":                  0,
	"PayWayNotFound":        2000001,
	"PayWayOperationFailed": 2000002,
	"CreateOrderFailed":     2000003,
	"UpdateOrderFailed":     2000004,
}

func (x PayErrors) String() string {
	return proto.EnumName(PayErrors_name, int32(x))
}

func (PayErrors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{0}
}

type UIDInput struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UIDInput) Reset()         { *m = UIDInput{} }
func (m *UIDInput) String() string { return proto.CompactTextString(m) }
func (*UIDInput) ProtoMessage()    {}
func (*UIDInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{0}
}

func (m *UIDInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UIDInput.Unmarshal(m, b)
}
func (m *UIDInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UIDInput.Marshal(b, m, deterministic)
}
func (m *UIDInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UIDInput.Merge(m, src)
}
func (m *UIDInput) XXX_Size() int {
	return xxx_messageInfo_UIDInput.Size(m)
}
func (m *UIDInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UIDInput.DiscardUnknown(m)
}

var xxx_messageInfo_UIDInput proto.InternalMessageInfo

func (m *UIDInput) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type PayWay struct {
	PayWayID             int64    `protobuf:"varint,1,opt,name=PayWayID,proto3" json:"PayWayID,omitempty"`
	PayType              string   `protobuf:"bytes,2,opt,name=PayType,proto3" json:"PayType,omitempty"`
	PayValue             string   `protobuf:"bytes,3,opt,name=PayValue,proto3" json:"PayValue,omitempty"`
	PayDesc              string   `protobuf:"bytes,4,opt,name=PayDesc,proto3" json:"PayDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayWay) Reset()         { *m = PayWay{} }
func (m *PayWay) String() string { return proto.CompactTextString(m) }
func (*PayWay) ProtoMessage()    {}
func (*PayWay) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{1}
}

func (m *PayWay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayWay.Unmarshal(m, b)
}
func (m *PayWay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayWay.Marshal(b, m, deterministic)
}
func (m *PayWay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayWay.Merge(m, src)
}
func (m *PayWay) XXX_Size() int {
	return xxx_messageInfo_PayWay.Size(m)
}
func (m *PayWay) XXX_DiscardUnknown() {
	xxx_messageInfo_PayWay.DiscardUnknown(m)
}

var xxx_messageInfo_PayWay proto.InternalMessageInfo

func (m *PayWay) GetPayWayID() int64 {
	if m != nil {
		return m.PayWayID
	}
	return 0
}

func (m *PayWay) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *PayWay) GetPayValue() string {
	if m != nil {
		return m.PayValue
	}
	return ""
}

func (m *PayWay) GetPayDesc() string {
	if m != nil {
		return m.PayDesc
	}
	return ""
}

type CreateUserPayWayRequest struct {
	PayType              string   `protobuf:"bytes,1,opt,name=PayType,proto3" json:"PayType,omitempty"`
	PayValue             string   `protobuf:"bytes,2,opt,name=PayValue,proto3" json:"PayValue,omitempty"`
	PayDesc              string   `protobuf:"bytes,3,opt,name=PayDesc,proto3" json:"PayDesc,omitempty"`
	UID                  int64    `protobuf:"varint,4,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserPayWayRequest) Reset()         { *m = CreateUserPayWayRequest{} }
func (m *CreateUserPayWayRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserPayWayRequest) ProtoMessage()    {}
func (*CreateUserPayWayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{2}
}

func (m *CreateUserPayWayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserPayWayRequest.Unmarshal(m, b)
}
func (m *CreateUserPayWayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserPayWayRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserPayWayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserPayWayRequest.Merge(m, src)
}
func (m *CreateUserPayWayRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserPayWayRequest.Size(m)
}
func (m *CreateUserPayWayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserPayWayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserPayWayRequest proto.InternalMessageInfo

func (m *CreateUserPayWayRequest) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *CreateUserPayWayRequest) GetPayValue() string {
	if m != nil {
		return m.PayValue
	}
	return ""
}

func (m *CreateUserPayWayRequest) GetPayDesc() string {
	if m != nil {
		return m.PayDesc
	}
	return ""
}

func (m *CreateUserPayWayRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type DeleteUserPayWayRequest struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	PayWayID             int64    `protobuf:"varint,2,opt,name=PayWayID,proto3" json:"PayWayID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserPayWayRequest) Reset()         { *m = DeleteUserPayWayRequest{} }
func (m *DeleteUserPayWayRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserPayWayRequest) ProtoMessage()    {}
func (*DeleteUserPayWayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{3}
}

func (m *DeleteUserPayWayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserPayWayRequest.Unmarshal(m, b)
}
func (m *DeleteUserPayWayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserPayWayRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserPayWayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserPayWayRequest.Merge(m, src)
}
func (m *DeleteUserPayWayRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserPayWayRequest.Size(m)
}
func (m *DeleteUserPayWayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserPayWayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserPayWayRequest proto.InternalMessageInfo

func (m *DeleteUserPayWayRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *DeleteUserPayWayRequest) GetPayWayID() int64 {
	if m != nil {
		return m.PayWayID
	}
	return 0
}

type PutUserPayWayRequest struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	PayWayID             int64    `protobuf:"varint,2,opt,name=PayWayID,proto3" json:"PayWayID,omitempty"`
	PayType              string   `protobuf:"bytes,3,opt,name=PayType,proto3" json:"PayType,omitempty"`
	PayValue             string   `protobuf:"bytes,4,opt,name=PayValue,proto3" json:"PayValue,omitempty"`
	PayDesc              string   `protobuf:"bytes,5,opt,name=PayDesc,proto3" json:"PayDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUserPayWayRequest) Reset()         { *m = PutUserPayWayRequest{} }
func (m *PutUserPayWayRequest) String() string { return proto.CompactTextString(m) }
func (*PutUserPayWayRequest) ProtoMessage()    {}
func (*PutUserPayWayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{4}
}

func (m *PutUserPayWayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUserPayWayRequest.Unmarshal(m, b)
}
func (m *PutUserPayWayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUserPayWayRequest.Marshal(b, m, deterministic)
}
func (m *PutUserPayWayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUserPayWayRequest.Merge(m, src)
}
func (m *PutUserPayWayRequest) XXX_Size() int {
	return xxx_messageInfo_PutUserPayWayRequest.Size(m)
}
func (m *PutUserPayWayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUserPayWayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutUserPayWayRequest proto.InternalMessageInfo

func (m *PutUserPayWayRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *PutUserPayWayRequest) GetPayWayID() int64 {
	if m != nil {
		return m.PayWayID
	}
	return 0
}

func (m *PutUserPayWayRequest) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *PutUserPayWayRequest) GetPayValue() string {
	if m != nil {
		return m.PayValue
	}
	return ""
}

func (m *PutUserPayWayRequest) GetPayDesc() string {
	if m != nil {
		return m.PayDesc
	}
	return ""
}

type UserPayWays struct {
	PayWays              []*PayWay `protobuf:"bytes,1,rep,name=PayWays,proto3" json:"PayWays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserPayWays) Reset()         { *m = UserPayWays{} }
func (m *UserPayWays) String() string { return proto.CompactTextString(m) }
func (*UserPayWays) ProtoMessage()    {}
func (*UserPayWays) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{5}
}

func (m *UserPayWays) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPayWays.Unmarshal(m, b)
}
func (m *UserPayWays) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPayWays.Marshal(b, m, deterministic)
}
func (m *UserPayWays) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPayWays.Merge(m, src)
}
func (m *UserPayWays) XXX_Size() int {
	return xxx_messageInfo_UserPayWays.Size(m)
}
func (m *UserPayWays) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPayWays.DiscardUnknown(m)
}

var xxx_messageInfo_UserPayWays proto.InternalMessageInfo

func (m *UserPayWays) GetPayWays() []*PayWay {
	if m != nil {
		return m.PayWays
	}
	return nil
}

type ErrorResponse struct {
	ErrorInfo            PayErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=pay.PayErrors" json:"ErrorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{6}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetErrorInfo() PayErrors {
	if m != nil {
		return m.ErrorInfo
	}
	return PayErrors_None
}

type CreateAliPayOrderRequest struct {
	CreateUserID         int64    `protobuf:"varint,1,opt,name=CreateUserID,proto3" json:"CreateUserID,omitempty"`
	OrderType            string   `protobuf:"bytes,2,opt,name=OrderType,proto3" json:"OrderType,omitempty"`
	CreateForUserID      int64    `protobuf:"varint,3,opt,name=CreateForUserID,proto3" json:"CreateForUserID,omitempty"`
	TotalAmount          string   `protobuf:"bytes,4,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=Subject,proto3" json:"Subject,omitempty"`
	OrderExtends         string   `protobuf:"bytes,6,opt,name=OrderExtends,proto3" json:"OrderExtends,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAliPayOrderRequest) Reset()         { *m = CreateAliPayOrderRequest{} }
func (m *CreateAliPayOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAliPayOrderRequest) ProtoMessage()    {}
func (*CreateAliPayOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{7}
}

func (m *CreateAliPayOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAliPayOrderRequest.Unmarshal(m, b)
}
func (m *CreateAliPayOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAliPayOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateAliPayOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAliPayOrderRequest.Merge(m, src)
}
func (m *CreateAliPayOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAliPayOrderRequest.Size(m)
}
func (m *CreateAliPayOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAliPayOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAliPayOrderRequest proto.InternalMessageInfo

func (m *CreateAliPayOrderRequest) GetCreateUserID() int64 {
	if m != nil {
		return m.CreateUserID
	}
	return 0
}

func (m *CreateAliPayOrderRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *CreateAliPayOrderRequest) GetCreateForUserID() int64 {
	if m != nil {
		return m.CreateForUserID
	}
	return 0
}

func (m *CreateAliPayOrderRequest) GetTotalAmount() string {
	if m != nil {
		return m.TotalAmount
	}
	return ""
}

func (m *CreateAliPayOrderRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CreateAliPayOrderRequest) GetOrderExtends() string {
	if m != nil {
		return m.OrderExtends
	}
	return ""
}

type PayOrderResultRequest struct {
	OutTradeNo           string   `protobuf:"bytes,1,opt,name=OutTradeNo,proto3" json:"OutTradeNo,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	RawData              string   `protobuf:"bytes,3,opt,name=RawData,proto3" json:"RawData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayOrderResultRequest) Reset()         { *m = PayOrderResultRequest{} }
func (m *PayOrderResultRequest) String() string { return proto.CompactTextString(m) }
func (*PayOrderResultRequest) ProtoMessage()    {}
func (*PayOrderResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{8}
}

func (m *PayOrderResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOrderResultRequest.Unmarshal(m, b)
}
func (m *PayOrderResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOrderResultRequest.Marshal(b, m, deterministic)
}
func (m *PayOrderResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOrderResultRequest.Merge(m, src)
}
func (m *PayOrderResultRequest) XXX_Size() int {
	return xxx_messageInfo_PayOrderResultRequest.Size(m)
}
func (m *PayOrderResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOrderResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayOrderResultRequest proto.InternalMessageInfo

func (m *PayOrderResultRequest) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

func (m *PayOrderResultRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PayOrderResultRequest) GetRawData() string {
	if m != nil {
		return m.RawData
	}
	return ""
}

type OrderResultResponse struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	OutTradeNo           string   `protobuf:"bytes,3,opt,name=OutTradeNo,proto3" json:"OutTradeNo,omitempty"`
	QRCode               string   `protobuf:"bytes,4,opt,name=QRCode,proto3" json:"QRCode,omitempty"`
	Sign                 string   `protobuf:"bytes,5,opt,name=Sign,proto3" json:"Sign,omitempty"`
	TradeStatus          string   `protobuf:"bytes,6,opt,name=TradeStatus,proto3" json:"TradeStatus,omitempty"`
	TradeNo              string   `protobuf:"bytes,7,opt,name=TradeNo,proto3" json:"TradeNo,omitempty"`
	TotalAmount          string   `protobuf:"bytes,8,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	BuyerLogonID         string   `protobuf:"bytes,9,opt,name=BuyerLogonID,proto3" json:"BuyerLogonID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResultResponse) Reset()         { *m = OrderResultResponse{} }
func (m *OrderResultResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResultResponse) ProtoMessage()    {}
func (*OrderResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{9}
}

func (m *OrderResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResultResponse.Unmarshal(m, b)
}
func (m *OrderResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResultResponse.Marshal(b, m, deterministic)
}
func (m *OrderResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResultResponse.Merge(m, src)
}
func (m *OrderResultResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResultResponse.Size(m)
}
func (m *OrderResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResultResponse proto.InternalMessageInfo

func (m *OrderResultResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OrderResultResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *OrderResultResponse) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

func (m *OrderResultResponse) GetQRCode() string {
	if m != nil {
		return m.QRCode
	}
	return ""
}

func (m *OrderResultResponse) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *OrderResultResponse) GetTradeStatus() string {
	if m != nil {
		return m.TradeStatus
	}
	return ""
}

func (m *OrderResultResponse) GetTradeNo() string {
	if m != nil {
		return m.TradeNo
	}
	return ""
}

func (m *OrderResultResponse) GetTotalAmount() string {
	if m != nil {
		return m.TotalAmount
	}
	return ""
}

func (m *OrderResultResponse) GetBuyerLogonID() string {
	if m != nil {
		return m.BuyerLogonID
	}
	return ""
}

type GetOrderListRequest struct {
	OrderCreateByUID     int64    `protobuf:"varint,1,opt,name=OrderCreateByUID,proto3" json:"OrderCreateByUID,omitempty"`
	OrderType            string   `protobuf:"bytes,2,opt,name=OrderType,proto3" json:"OrderType,omitempty"`
	OrdercreateForUID    int64    `protobuf:"varint,3,opt,name=OrdercreateForUID,proto3" json:"OrdercreateForUID,omitempty"`
	Page                 int64    `protobuf:"varint,4,opt,name=Page,proto3" json:"Page,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	OrderPlatForm        string   `protobuf:"bytes,7,opt,name=OrderPlatForm,proto3" json:"OrderPlatForm,omitempty"`
	OrderExtends         string   `protobuf:"bytes,9,opt,name=OrderExtends,proto3" json:"OrderExtends,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderListRequest) Reset()         { *m = GetOrderListRequest{} }
func (m *GetOrderListRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderListRequest) ProtoMessage()    {}
func (*GetOrderListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{10}
}

func (m *GetOrderListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderListRequest.Unmarshal(m, b)
}
func (m *GetOrderListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderListRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderListRequest.Merge(m, src)
}
func (m *GetOrderListRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderListRequest.Size(m)
}
func (m *GetOrderListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderListRequest proto.InternalMessageInfo

func (m *GetOrderListRequest) GetOrderCreateByUID() int64 {
	if m != nil {
		return m.OrderCreateByUID
	}
	return 0
}

func (m *GetOrderListRequest) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *GetOrderListRequest) GetOrdercreateForUID() int64 {
	if m != nil {
		return m.OrdercreateForUID
	}
	return 0
}

func (m *GetOrderListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetOrderListRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetOrderListRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetOrderListRequest) GetOrderPlatForm() string {
	if m != nil {
		return m.OrderPlatForm
	}
	return ""
}

func (m *GetOrderListRequest) GetOrderExtends() string {
	if m != nil {
		return m.OrderExtends
	}
	return ""
}

type OrderInfo struct {
	OutTradeNo           string   `protobuf:"bytes,1,opt,name=OutTradeNo,proto3" json:"OutTradeNo,omitempty"`
	OrderStatus          string   `protobuf:"bytes,2,opt,name=OrderStatus,proto3" json:"OrderStatus,omitempty"`
	OrderPlatForm        string   `protobuf:"bytes,3,opt,name=OrderPlatForm,proto3" json:"OrderPlatForm,omitempty"`
	OrderType            string   `protobuf:"bytes,4,opt,name=OrderType,proto3" json:"OrderType,omitempty"`
	OrderCreateByUID     string   `protobuf:"bytes,5,opt,name=OrderCreateByUID,proto3" json:"OrderCreateByUID,omitempty"`
	OrdercreateForUID    string   `protobuf:"bytes,6,opt,name=OrdercreateForUID,proto3" json:"OrdercreateForUID,omitempty"`
	OrderExtends         string   `protobuf:"bytes,7,opt,name=OrderExtends,proto3" json:"OrderExtends,omitempty"`
	OrderAmount          string   `protobuf:"bytes,8,opt,name=OrderAmount,proto3" json:"OrderAmount,omitempty"`
	CreatedAt            int64    `protobuf:"varint,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Expired              bool     `protobuf:"varint,10,opt,name=Expired,proto3" json:"Expired,omitempty"`
	QRCode               string   `protobuf:"bytes,11,opt,name=QRCode,proto3" json:"QRCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{11}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetOutTradeNo() string {
	if m != nil {
		return m.OutTradeNo
	}
	return ""
}

func (m *OrderInfo) GetOrderStatus() string {
	if m != nil {
		return m.OrderStatus
	}
	return ""
}

func (m *OrderInfo) GetOrderPlatForm() string {
	if m != nil {
		return m.OrderPlatForm
	}
	return ""
}

func (m *OrderInfo) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *OrderInfo) GetOrderCreateByUID() string {
	if m != nil {
		return m.OrderCreateByUID
	}
	return ""
}

func (m *OrderInfo) GetOrdercreateForUID() string {
	if m != nil {
		return m.OrdercreateForUID
	}
	return ""
}

func (m *OrderInfo) GetOrderExtends() string {
	if m != nil {
		return m.OrderExtends
	}
	return ""
}

func (m *OrderInfo) GetOrderAmount() string {
	if m != nil {
		return m.OrderAmount
	}
	return ""
}

func (m *OrderInfo) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *OrderInfo) GetExpired() bool {
	if m != nil {
		return m.Expired
	}
	return false
}

func (m *OrderInfo) GetQRCode() string {
	if m != nil {
		return m.QRCode
	}
	return ""
}

type OrderListResponse struct {
	List                 []*OrderInfo `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OrderListResponse) Reset()         { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()    {}
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_587e2c2585dcd479, []int{12}
}

func (m *OrderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderListResponse.Unmarshal(m, b)
}
func (m *OrderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderListResponse.Marshal(b, m, deterministic)
}
func (m *OrderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderListResponse.Merge(m, src)
}
func (m *OrderListResponse) XXX_Size() int {
	return xxx_messageInfo_OrderListResponse.Size(m)
}
func (m *OrderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderListResponse proto.InternalMessageInfo

func (m *OrderListResponse) GetList() []*OrderInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("pay.PayErrors", PayErrors_name, PayErrors_value)
	proto.RegisterType((*UIDInput)(nil), "pay.UIDInput")
	proto.RegisterType((*PayWay)(nil), "pay.PayWay")
	proto.RegisterType((*CreateUserPayWayRequest)(nil), "pay.CreateUserPayWayRequest")
	proto.RegisterType((*DeleteUserPayWayRequest)(nil), "pay.DeleteUserPayWayRequest")
	proto.RegisterType((*PutUserPayWayRequest)(nil), "pay.PutUserPayWayRequest")
	proto.RegisterType((*UserPayWays)(nil), "pay.UserPayWays")
	proto.RegisterType((*ErrorResponse)(nil), "pay.ErrorResponse")
	proto.RegisterType((*CreateAliPayOrderRequest)(nil), "pay.CreateAliPayOrderRequest")
	proto.RegisterType((*PayOrderResultRequest)(nil), "pay.PayOrderResultRequest")
	proto.RegisterType((*OrderResultResponse)(nil), "pay.OrderResultResponse")
	proto.RegisterType((*GetOrderListRequest)(nil), "pay.GetOrderListRequest")
	proto.RegisterType((*OrderInfo)(nil), "pay.OrderInfo")
	proto.RegisterType((*OrderListResponse)(nil), "pay.OrderListResponse")
}

func init() { proto.RegisterFile("pay/pay.proto", fileDescriptor_587e2c2585dcd479) }

var fileDescriptor_587e2c2585dcd479 = []byte{
	// 924 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5b, 0x8f, 0xdb, 0x44,
	0x14, 0xae, 0x63, 0x37, 0x9b, 0x9c, 0x6c, 0x96, 0x74, 0xba, 0x74, 0x4d, 0x58, 0x50, 0x64, 0x81,
	0x14, 0x55, 0x55, 0x2b, 0x2d, 0x48, 0x3c, 0x21, 0xb1, 0x6d, 0x36, 0x51, 0x44, 0xc9, 0x06, 0x67,
	0xd3, 0x3e, 0x4f, 0xd7, 0x43, 0x14, 0x94, 0x7a, 0x8c, 0x3d, 0x16, 0x75, 0x78, 0x2a, 0xf0, 0x92,
	0x77, 0x24, 0x7e, 0x0b, 0x7f, 0x88, 0xdf, 0x81, 0xe6, 0xe2, 0xcb, 0xf8, 0xc2, 0x0a, 0xf1, 0x36,
	0xe7, 0x9c, 0x99, 0x73, 0xf9, 0xce, 0xe7, 0x73, 0x0c, 0xfd, 0x00, 0x27, 0xcf, 0x02, 0x9c, 0x3c,
	0x0d, 0x42, 0xca, 0x28, 0x32, 0x03, 0x9c, 0x38, 0xe7, 0xd0, 0x59, 0xcf, 0x27, 0x73, 0x3f, 0x88,
	0x19, 0x1a, 0x80, 0xb9, 0x9e, 0x4f, 0x6c, 0x63, 0x64, 0x8c, 0x4d, 0x97, 0x1f, 0x1d, 0x06, 0xed,
	0x25, 0x4e, 0x5e, 0xe3, 0x04, 0x0d, 0xa1, 0x23, 0x4f, 0xd9, 0x85, 0x4c, 0x46, 0x36, 0x1c, 0x2d,
	0x71, 0x72, 0x93, 0x04, 0xc4, 0x6e, 0x8d, 0x8c, 0x71, 0xd7, 0x4d, 0x45, 0xf5, 0xea, 0x15, 0xde,
	0xc5, 0xc4, 0x36, 0x85, 0x29, 0x93, 0xd5, 0xab, 0x09, 0x89, 0x6e, 0x6d, 0x2b, 0x7b, 0xc5, 0x45,
	0xe7, 0x17, 0x38, 0x7b, 0x11, 0x12, 0xcc, 0xc8, 0x3a, 0x22, 0xa1, 0x8c, 0xe2, 0x92, 0x9f, 0x62,
	0x12, 0xb1, 0x62, 0x28, 0xa3, 0x39, 0x54, 0xab, 0x39, 0x94, 0xa9, 0x85, 0x4a, 0x4b, 0xb6, 0xf2,
	0x92, 0x67, 0x70, 0x36, 0x21, 0x3b, 0x52, 0x17, 0xbc, 0x82, 0x8f, 0x86, 0x4a, 0x4b, 0x47, 0xc5,
	0xf9, 0xc3, 0x80, 0xd3, 0x65, 0xcc, 0xfe, 0xa7, 0x9b, 0x62, 0xc5, 0x66, 0x73, 0xc5, 0x56, 0x73,
	0xc5, 0xf7, 0x75, 0x70, 0xbf, 0x84, 0x5e, 0x9e, 0x52, 0x84, 0x3e, 0x17, 0x17, 0xf9, 0xd1, 0x36,
	0x46, 0xe6, 0xb8, 0x77, 0xd1, 0x7b, 0xca, 0x19, 0xa2, 0x32, 0x4e, 0x6d, 0xce, 0xd7, 0xd0, 0xbf,
	0x0a, 0x43, 0x1a, 0xba, 0x24, 0x0a, 0xa8, 0x1f, 0x11, 0xf4, 0x04, 0xba, 0x42, 0x31, 0xf7, 0x7f,
	0xa0, 0xa2, 0x94, 0x93, 0x8b, 0x93, 0xf4, 0xa5, 0x30, 0x44, 0x6e, 0x7e, 0xc1, 0xf9, 0xdb, 0x00,
	0x5b, 0xb6, 0xf4, 0x72, 0xb7, 0x5d, 0xe2, 0xe4, 0x3a, 0xf4, 0x48, 0x98, 0xe2, 0xe1, 0xc0, 0x71,
	0xde, 0xee, 0x0c, 0x18, 0x4d, 0x87, 0xce, 0xa1, 0x2b, 0xde, 0x14, 0x48, 0x96, 0x2b, 0xd0, 0x18,
	0x3e, 0x90, 0xb7, 0xa7, 0x34, 0x54, 0x4e, 0x4c, 0xe1, 0xa4, 0xac, 0x46, 0x23, 0xe8, 0xdd, 0x50,
	0x86, 0x77, 0x97, 0x6f, 0x69, 0xec, 0x33, 0x05, 0x5b, 0x51, 0xc5, 0x91, 0x5b, 0xc5, 0x6f, 0x7e,
	0x24, 0xb7, 0x2c, 0x45, 0x4e, 0x89, 0x3c, 0x4f, 0x11, 0xf2, 0xea, 0x1d, 0x23, 0xbe, 0x17, 0xd9,
	0x6d, 0x61, 0xd6, 0x74, 0xce, 0x16, 0x3e, 0xcc, 0xcb, 0x8b, 0xe2, 0x1d, 0x4b, 0x8b, 0xfc, 0x14,
	0xe0, 0x3a, 0x66, 0x37, 0x21, 0xf6, 0xc8, 0x82, 0x2a, 0xee, 0x16, 0x34, 0xe8, 0x11, 0xb4, 0x57,
	0x0c, 0xb3, 0x38, 0x52, 0xd5, 0x29, 0x89, 0xa7, 0xe3, 0xe2, 0x9f, 0x27, 0x98, 0xe1, 0xb4, 0xfd,
	0x4a, 0x74, 0x0e, 0x2d, 0x78, 0xa8, 0x05, 0x52, 0x9d, 0x41, 0x60, 0xbd, 0xa0, 0x5e, 0xfa, 0x7d,
	0x88, 0x33, 0xa7, 0xdc, 0x77, 0xd1, 0x46, 0xb9, 0xe6, 0xc7, 0x52, 0x3e, 0x66, 0x5d, 0x3e, 0xdf,
	0xbb, 0xc2, 0x8f, 0xc4, 0x48, 0x49, 0xdc, 0xfb, 0x6a, 0xbb, 0xf1, 0x15, 0x36, 0xe2, 0x2c, 0x40,
	0xe5, 0xcf, 0x54, 0x01, 0x6d, 0x05, 0x6a, 0xae, 0xe2, 0x55, 0xa4, 0xa1, 0x8e, 0x64, 0x15, 0x69,
	0x9c, 0x52, 0x43, 0x3a, 0xd5, 0x86, 0x38, 0x70, 0xfc, 0x3c, 0x4e, 0x48, 0xf8, 0x92, 0x6e, 0xa8,
	0x3f, 0x9f, 0xd8, 0x5d, 0x09, 0x7b, 0x51, 0xe7, 0xfc, 0xd9, 0x82, 0x87, 0x33, 0xc2, 0x04, 0x1c,
	0x2f, 0xb7, 0x51, 0x86, 0xfa, 0x63, 0x18, 0x08, 0x9d, 0xa4, 0xc1, 0xf3, 0x24, 0xff, 0xee, 0x2a,
	0xfa, 0x3b, 0x28, 0xf6, 0x04, 0x1e, 0x08, 0xe1, 0x36, 0x23, 0x54, 0x46, 0xb2, 0xaa, 0x81, 0xa3,
	0xb4, 0xc4, 0x1b, 0xa2, 0xe6, 0x8a, 0x38, 0x4b, 0xe4, 0xf6, 0x44, 0x20, 0x67, 0xba, 0xe2, 0x5c,
	0xe8, 0x7a, 0x5b, 0xeb, 0xfa, 0x67, 0xd0, 0x17, 0x4e, 0x97, 0x3b, 0xcc, 0xa6, 0x34, 0x7c, 0xab,
	0x50, 0xd3, 0x95, 0x15, 0x42, 0x76, 0x6b, 0x08, 0xf9, 0xde, 0x54, 0x65, 0xf1, 0xef, 0xf0, 0x4e,
	0x16, 0x8e, 0xa0, 0x27, 0x2e, 0x6b, 0x54, 0x2c, 0xaa, 0xaa, 0x99, 0x99, 0x75, 0x99, 0x69, 0x58,
	0x5a, 0x65, 0x2c, 0xeb, 0xba, 0x22, 0xf9, 0x54, 0xed, 0x4a, 0x2d, 0xee, 0x12, 0xac, 0x1a, 0xdc,
	0xcb, 0x88, 0x1c, 0x55, 0x11, 0xc9, 0x6a, 0xd4, 0x19, 0x57, 0x50, 0xf1, 0xec, 0x65, 0x0a, 0xde,
	0x25, 0x13, 0xa0, 0x9a, 0x6e, 0xae, 0xe0, 0x5c, 0xbe, 0x7a, 0x17, 0x6c, 0x43, 0xe2, 0xd9, 0x30,
	0x32, 0xc6, 0x1d, 0x37, 0x15, 0x0b, 0xdf, 0x4c, 0xaf, 0xf8, 0xcd, 0x38, 0x5f, 0xa9, 0x1a, 0x24,
	0x33, 0xd5, 0x67, 0xea, 0x80, 0xc5, 0x65, 0x35, 0x75, 0xe5, 0xec, 0xcc, 0x1a, 0xe5, 0x0a, 0xdb,
	0xe3, 0x3d, 0x74, 0xb3, 0x71, 0x8a, 0x3a, 0x60, 0x2d, 0xa8, 0x4f, 0x06, 0xf7, 0xd0, 0x29, 0x9c,
	0xc8, 0xb9, 0xbc, 0xa0, 0x6c, 0x4a, 0x63, 0xdf, 0x1b, 0xbc, 0x3f, 0xec, 0xd1, 0xc7, 0x62, 0xf4,
	0xbc, 0xc6, 0xc9, 0x75, 0x40, 0x42, 0xcc, 0xb6, 0xd4, 0x9f, 0xe2, 0xed, 0x8e, 0x78, 0x83, 0x5f,
	0x0f, 0x7b, 0x74, 0x06, 0x0f, 0x64, 0x05, 0x22, 0x84, 0x32, 0xfc, 0x26, 0x0d, 0xeb, 0xc0, 0x2b,
	0x19, 0x7e, 0x3f, 0xec, 0x2f, 0xfe, 0xb2, 0xe0, 0x7e, 0x80, 0x93, 0xd5, 0x2b, 0xf4, 0x0c, 0x60,
	0x46, 0xd8, 0x12, 0x27, 0x82, 0x42, 0x7d, 0x91, 0x69, 0xfa, 0xcf, 0x30, 0x1c, 0x48, 0x31, 0xdf,
	0x28, 0xce, 0x3d, 0x34, 0x85, 0x41, 0x79, 0x7f, 0xa3, 0x73, 0x71, 0xaf, 0x61, 0xad, 0x0f, 0x91,
	0xb0, 0x6a, 0x1b, 0x46, 0xfa, 0x29, 0xaf, 0x62, 0xe5, 0xa7, 0x61, 0x43, 0x37, 0xf8, 0xf9, 0x06,
	0xfa, 0xda, 0x22, 0x46, 0x1f, 0xc9, 0x4d, 0x55, 0xb3, 0x9c, 0x1b, 0x3c, 0x2c, 0x52, 0xf8, 0x0a,
	0xeb, 0x0b, 0x7d, 0x52, 0x28, 0xa9, 0xba, 0xd6, 0x86, 0x76, 0xde, 0x52, 0x7d, 0x42, 0x0b, 0x7f,
	0xa7, 0x33, 0xc2, 0xb4, 0x47, 0xfc, 0x06, 0x1a, 0xa6, 0x2b, 0xb4, 0xba, 0x41, 0xfe, 0xd5, 0xdf,
	0xb7, 0x70, 0x26, 0xbb, 0xf8, 0xdf, 0x5c, 0x36, 0xc1, 0x75, 0x5c, 0x9c, 0xa5, 0x48, 0x06, 0xae,
	0x19, 0xaf, 0xc3, 0x47, 0x79, 0x4a, 0x45, 0x6e, 0xbf, 0x69, 0x8b, 0x1f, 0xcc, 0x2f, 0xfe, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x25, 0xcd, 0x78, 0x70, 0x71, 0x0a, 0x00, 0x00,
}
