// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search/search.proto

package search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 搜索类型
type SearchTypes int32

const (
	SearchTypes_NoneType SearchTypes = 0
	SearchTypes_Article  SearchTypes = 1
	SearchTypes_Author   SearchTypes = 2
)

var SearchTypes_name = map[int32]string{
	0: "NoneType",
	1: "Article",
	2: "Author",
}

var SearchTypes_value = map[string]int32{
	"NoneType": 0,
	"Article":  1,
	"Author":   2,
}

func (x SearchTypes) String() string {
	return proto.EnumName(SearchTypes_name, int32(x))
}

func (SearchTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{0}
}

// 错误类型
type SearchErrors int32

const (
	SearchErrors_NoneError         SearchErrors = 0
	SearchErrors_SearchCommonError SearchErrors = 4000001
)

var SearchErrors_name = map[int32]string{
	0:       "NoneError",
	4000001: "SearchCommonError",
}

var SearchErrors_value = map[string]int32{
	"NoneError":         0,
	"SearchCommonError": 4000001,
}

func (x SearchErrors) String() string {
	return proto.EnumName(SearchErrors_name, int32(x))
}

func (SearchErrors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{1}
}

// 搜索结果
type SearchResult struct {
	Results              []string `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResult) Reset()         { *m = SearchResult{} }
func (m *SearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()    {}
func (*SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{0}
}

func (m *SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResult.Unmarshal(m, b)
}
func (m *SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResult.Marshal(b, m, deterministic)
}
func (m *SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResult.Merge(m, src)
}
func (m *SearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchResult.Size(m)
}
func (m *SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResult proto.InternalMessageInfo

func (m *SearchResult) GetResults() []string {
	if m != nil {
		return m.Results
	}
	return nil
}

// 删除搜索
type DelSearchRequest struct {
	Collection           string   `protobuf:"bytes,1,opt,name=Collection,proto3" json:"Collection,omitempty"`
	Bucket               string   `protobuf:"bytes,2,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Object               string   `protobuf:"bytes,3,opt,name=Object,proto3" json:"Object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelSearchRequest) Reset()         { *m = DelSearchRequest{} }
func (m *DelSearchRequest) String() string { return proto.CompactTextString(m) }
func (*DelSearchRequest) ProtoMessage()    {}
func (*DelSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{1}
}

func (m *DelSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelSearchRequest.Unmarshal(m, b)
}
func (m *DelSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelSearchRequest.Marshal(b, m, deterministic)
}
func (m *DelSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelSearchRequest.Merge(m, src)
}
func (m *DelSearchRequest) XXX_Size() int {
	return xxx_messageInfo_DelSearchRequest.Size(m)
}
func (m *DelSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelSearchRequest proto.InternalMessageInfo

func (m *DelSearchRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *DelSearchRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *DelSearchRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

type ErrorResponse struct {
	ErrorInfo            SearchErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=search.SearchErrors" json:"ErrorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{2}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetErrorInfo() SearchErrors {
	if m != nil {
		return m.ErrorInfo
	}
	return SearchErrors_NoneError
}

// 插入搜索数据请求
type PostSearchSourceRequest struct {
	Collection           string   `protobuf:"bytes,1,opt,name=Collection,proto3" json:"Collection,omitempty"`
	Bucket               string   `protobuf:"bytes,2,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Object               string   `protobuf:"bytes,3,opt,name=Object,proto3" json:"Object,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostSearchSourceRequest) Reset()         { *m = PostSearchSourceRequest{} }
func (m *PostSearchSourceRequest) String() string { return proto.CompactTextString(m) }
func (*PostSearchSourceRequest) ProtoMessage()    {}
func (*PostSearchSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{3}
}

func (m *PostSearchSourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostSearchSourceRequest.Unmarshal(m, b)
}
func (m *PostSearchSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostSearchSourceRequest.Marshal(b, m, deterministic)
}
func (m *PostSearchSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostSearchSourceRequest.Merge(m, src)
}
func (m *PostSearchSourceRequest) XXX_Size() int {
	return xxx_messageInfo_PostSearchSourceRequest.Size(m)
}
func (m *PostSearchSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostSearchSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostSearchSourceRequest proto.InternalMessageInfo

func (m *PostSearchSourceRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *PostSearchSourceRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *PostSearchSourceRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *PostSearchSourceRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// 获取搜索结果
type GetSearchRequest struct {
	Collection           string   `protobuf:"bytes,1,opt,name=Collection,proto3" json:"Collection,omitempty"`
	Bucket               string   `protobuf:"bytes,2,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSearchRequest) Reset()         { *m = GetSearchRequest{} }
func (m *GetSearchRequest) String() string { return proto.CompactTextString(m) }
func (*GetSearchRequest) ProtoMessage()    {}
func (*GetSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c662bebbc5127a4, []int{4}
}

func (m *GetSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSearchRequest.Unmarshal(m, b)
}
func (m *GetSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSearchRequest.Marshal(b, m, deterministic)
}
func (m *GetSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSearchRequest.Merge(m, src)
}
func (m *GetSearchRequest) XXX_Size() int {
	return xxx_messageInfo_GetSearchRequest.Size(m)
}
func (m *GetSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSearchRequest proto.InternalMessageInfo

func (m *GetSearchRequest) GetCollection() string {
	if m != nil {
		return m.Collection
	}
	return ""
}

func (m *GetSearchRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetSearchRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterEnum("search.SearchTypes", SearchTypes_name, SearchTypes_value)
	proto.RegisterEnum("search.SearchErrors", SearchErrors_name, SearchErrors_value)
	proto.RegisterType((*SearchResult)(nil), "search.SearchResult")
	proto.RegisterType((*DelSearchRequest)(nil), "search.DelSearchRequest")
	proto.RegisterType((*ErrorResponse)(nil), "search.ErrorResponse")
	proto.RegisterType((*PostSearchSourceRequest)(nil), "search.PostSearchSourceRequest")
	proto.RegisterType((*GetSearchRequest)(nil), "search.GetSearchRequest")
}

func init() { proto.RegisterFile("search/search.proto", fileDescriptor_3c662bebbc5127a4) }

var fileDescriptor_3c662bebbc5127a4 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0xa5, 0x40, 0x0a, 0x1d, 0xe0, 0x47, 0x7f, 0xe3, 0xbf, 0x0d, 0x07, 0x25, 0x3d, 0x11, 0x0e,
	0x98, 0xa0, 0x89, 0x67, 0x40, 0x63, 0xf4, 0xa0, 0xa6, 0x10, 0x8f, 0x26, 0xd2, 0x8c, 0x01, 0x2d,
	0x5d, 0xdc, 0xdd, 0x26, 0x72, 0xf0, 0xe0, 0x57, 0xf0, 0xfb, 0xf9, 0x2d, 0xfc, 0x00, 0xa6, 0xbb,
	0x14, 0xb5, 0x91, 0x9b, 0x9e, 0xba, 0xef, 0xbd, 0xe9, 0xeb, 0xce, 0xbc, 0x29, 0x6c, 0x48, 0xba,
	0x15, 0xc1, 0x64, 0xdf, 0x3c, 0x3a, 0x73, 0xc1, 0x15, 0x47, 0xdb, 0x20, 0xaf, 0x05, 0xd5, 0xa1,
	0x3e, 0xf9, 0x24, 0xe3, 0x50, 0x21, 0x83, 0x92, 0x39, 0x49, 0x66, 0x35, 0x0b, 0x2d, 0xc7, 0x4f,
	0xa1, 0x37, 0x06, 0xf7, 0x98, 0xc2, 0xb4, 0xf8, 0x31, 0x26, 0xa9, 0x70, 0x17, 0x60, 0xc0, 0xc3,
	0x90, 0x02, 0x35, 0xe5, 0x11, 0xb3, 0x9a, 0x56, 0xcb, 0xf1, 0xbf, 0x30, 0xb8, 0x0d, 0x76, 0x3f,
	0x0e, 0x1e, 0x48, 0xb1, 0xbc, 0xd6, 0x96, 0x28, 0xe1, 0x2f, 0xc7, 0xf7, 0x14, 0x28, 0x56, 0x30,
	0xbc, 0x41, 0xde, 0x00, 0x6a, 0x27, 0x42, 0x70, 0xe1, 0x93, 0x9c, 0xf3, 0x48, 0x12, 0x76, 0xc1,
	0xd1, 0xc4, 0x59, 0x74, 0xc7, 0xb5, 0xff, 0xbf, 0xee, 0x66, 0x67, 0xd9, 0x88, 0xb9, 0x8a, 0x96,
	0xa5, 0xff, 0x59, 0xe6, 0x3d, 0xc3, 0xce, 0x15, 0x97, 0xca, 0xc8, 0x43, 0x1e, 0x8b, 0x80, 0xfe,
	0xe8, 0xbe, 0x88, 0x50, 0x1c, 0xd1, 0x93, 0x62, 0x45, 0xcd, 0xea, 0xb3, 0x77, 0x03, 0xee, 0x29,
	0xa9, 0xdf, 0x99, 0xd3, 0x0f, 0xfe, 0xed, 0x43, 0xa8, 0x18, 0xf3, 0xd1, 0x62, 0x4e, 0x12, 0xab,
	0x50, 0xbe, 0xe0, 0x11, 0x25, 0xc0, 0xcd, 0x61, 0x05, 0x4a, 0x3d, 0xa1, 0xa6, 0x41, 0x48, 0xae,
	0x85, 0x00, 0x76, 0x2f, 0x56, 0x13, 0x2e, 0xdc, 0x7c, 0xfb, 0x28, 0xcd, 0xd9, 0xcc, 0x0b, 0x6b,
	0xe0, 0x24, 0xaf, 0x69, 0xe4, 0xe6, 0x90, 0xc1, 0x7f, 0x23, 0x0f, 0xf8, 0x6c, 0xc6, 0x23, 0x43,
	0xbf, 0xbc, 0xbe, 0x5b, 0xdd, 0x37, 0x0b, 0xca, 0x66, 0xe0, 0xc3, 0x6b, 0xec, 0x41, 0x7d, 0xd5,
	0x5b, 0x7f, 0x91, 0x7c, 0x13, 0x59, 0x1a, 0x47, 0xb6, 0xe9, 0x46, 0x26, 0xa8, 0xe5, 0x82, 0xf5,
	0xa1, 0xbe, 0x5a, 0xa3, 0xac, 0x45, 0x76, 0xbf, 0x1a, 0x5b, 0xa9, 0xf2, 0x7d, 0x2b, 0xce, 0xc1,
	0xcd, 0x26, 0x8c, 0x7b, 0x69, 0xe9, 0x9a, 0xec, 0xd7, 0x78, 0x8d, 0x6d, 0xfd, 0x3f, 0x1c, 0x7c,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x65, 0x2f, 0x83, 0x89, 0x26, 0x03, 0x00, 0x00,
}
