version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/unliar/happysooner-proto
    steps:
      - add_ssh_keys:
          fingerprints:
            - "69:14:ea:fa:41:c7:01:64:99:d1:19:dc:25:11:83:81"
      - checkout      
      - run: echo "build start to run"
      - run: export
      - run: sudo apt install protobuf-compiler
      - run: go get github.com/golang/protobuf/protoc-gen-go
      - run: go get github.com/micro/protoc-gen-micro
      - run: protoc
      - run: protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./account/account.proto
      # - run: make      
      - run: echo "build done"
      - run: git config --global user.email "370732889@qq.com"
      - run: git config --global user.name "unliar"
      - run: git add . && git commit -m "build:' 'happy circleci." && git push
     