version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "ON"
    working_directory: /go/src/github.com/unliar/happysooner-proto
    steps:
      - checkout
      - run: echo "build start to run"
      - run: export GO111MODULE=on
      - run: go get
      - run: echo "build done"