version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
          PATH: $PATH:$GOPATH/bin
    working_directory: /go/src/github.com/unliar/happysooner-proto
    steps:
      - checkout
      - run: echo "build start to run"
      - run: go get -v -u github.com/golang/protobuf/protoc-gen-go
      - run: go install github.com/golang/protobuf/protoc-gen-go
      - run: sudo apt install protobuf-compiler
      - run: protoc
      - run: protoc --proto_path=$GOPATH/src:. --micro_out=. --go_out=. account/account.proto
      - run: echo "build done"