version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "auto"
    working_directory: /go/src/github.com/unliar/happysooner-proto
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cd:97:a2:cb:29:13:0e:7b:62:d7:c8:f0:1e:fc:2f:94"
      - run: echo "build start to run"
      - run: export
      - run: sudo apt install protobuf-compiler
      - run: go get github.com/golang/protobuf/protoc-gen-go
      - run: go get github.com/micro/protoc-gen-micro
      - run: protoc
      - run: protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./account/account.proto
      - run: echo "build done"
      - run: git add . && git commit -m "circle auto build" && git push
      - run: make
