// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_DefaultRole Role = 0
	Role_Admin       Role = 1
	Role_Author      Role = 2
	Role_Viewer      Role = 3
)

var Role_name = map[int32]string{
	0: "DefaultRole",
	1: "Admin",
	2: "Author",
	3: "Viewer",
}

var Role_value = map[string]int32{
	"DefaultRole": 0,
	"Admin":       1,
	"Author":      2,
	"Viewer":      3,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{0}
}

// 错误码定义 累计7位 账户服务使用 100 [第一位1表示账户模块，第二位表示子模块(表)] ，后四位自由发挥qaq
// 100
type AccountErrors int32

const (
	AccountErrors_None                           AccountErrors = 0
	AccountErrors_UserNotFound                   AccountErrors = 1000001
	AccountErrors_UserCreateFailed               AccountErrors = 1000002
	AccountErrors_UserUpdateFailed               AccountErrors = 1000003
	AccountErrors_UserNicknameExist              AccountErrors = 1000004
	AccountErrors_UserLoginNameExist             AccountErrors = 1000005
	AccountErrors_UserPhoneExist                 AccountErrors = 1000006
	AccountErrors_UserEmailExist                 AccountErrors = 1000007
	AccountErrors_UserPasswordCheckFailed        AccountErrors = 1000008
	AccountErrors_UserBindUserContactEmailFailed AccountErrors = 1000009
	AccountErrors_UserBindUserContactPhoneFailed AccountErrors = 1000010
)

var AccountErrors_name = map[int32]string{
	0:       "None",
	1000001: "UserNotFound",
	1000002: "UserCreateFailed",
	1000003: "UserUpdateFailed",
	1000004: "UserNicknameExist",
	1000005: "UserLoginNameExist",
	1000006: "UserPhoneExist",
	1000007: "UserEmailExist",
	1000008: "UserPasswordCheckFailed",
	1000009: "UserBindUserContactEmailFailed",
	1000010: "UserBindUserContactPhoneFailed",
}

var AccountErrors_value = map[string]int32{
	"None":                           0,
	"UserNotFound":                   1000001,
	"UserCreateFailed":               1000002,
	"UserUpdateFailed":               1000003,
	"UserNicknameExist":              1000004,
	"UserLoginNameExist":             1000005,
	"UserPhoneExist":                 1000006,
	"UserEmailExist":                 1000007,
	"UserPasswordCheckFailed":        1000008,
	"UserBindUserContactEmailFailed": 1000009,
	"UserBindUserContactPhoneFailed": 1000010,
}

func (x AccountErrors) String() string {
	return proto.EnumName(AccountErrors_name, int32(x))
}

func (AccountErrors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{1}
}

type UserInfo struct {
	Id                   int64       `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	LoginName            string      `protobuf:"bytes,2,opt,name=LoginName,proto3" json:"LoginName,omitempty"`
	Nickname             string      `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Age                  int64       `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	Gender               int64       `protobuf:"varint,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Avatar               string      `protobuf:"bytes,6,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Location             string      `protobuf:"bytes,7,opt,name=Location,proto3" json:"Location,omitempty"`
	Profession           string      `protobuf:"bytes,8,opt,name=Profession,proto3" json:"Profession,omitempty"`
	Status               int64       `protobuf:"varint,9,opt,name=Status,proto3" json:"Status,omitempty"`
	Brief                string      `protobuf:"bytes,12,opt,name=Brief,proto3" json:"Brief,omitempty"`
	Email                string      `protobuf:"bytes,13,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone                string      `protobuf:"bytes,14,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PhoneCode            string      `protobuf:"bytes,15,opt,name=PhoneCode,proto3" json:"PhoneCode,omitempty"`
	WeChatId             string      `protobuf:"bytes,16,opt,name=WeChatId,proto3" json:"WeChatId,omitempty"`
	QQId                 string      `protobuf:"bytes,17,opt,name=QQId,proto3" json:"QQId,omitempty"`
	Password             string      `protobuf:"bytes,18,opt,name=Password,proto3" json:"Password,omitempty"`
	Roles                []*RoleInfo `protobuf:"bytes,19,rep,name=Roles,proto3" json:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetGender() int64 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *UserInfo) GetProfession() string {
	if m != nil {
		return m.Profession
	}
	return ""
}

func (m *UserInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserInfo) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInfo) GetPhoneCode() string {
	if m != nil {
		return m.PhoneCode
	}
	return ""
}

func (m *UserInfo) GetWeChatId() string {
	if m != nil {
		return m.WeChatId
	}
	return ""
}

func (m *UserInfo) GetQQId() string {
	if m != nil {
		return m.QQId
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetRoles() []*RoleInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

type PutUserBaseRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=LoginName,proto3" json:"LoginName,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Age                  int64    `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	Gender               int64    `protobuf:"varint,5,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Location             string   `protobuf:"bytes,7,opt,name=Location,proto3" json:"Location,omitempty"`
	Profession           string   `protobuf:"bytes,8,opt,name=Profession,proto3" json:"Profession,omitempty"`
	Brief                string   `protobuf:"bytes,9,opt,name=Brief,proto3" json:"Brief,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUserBaseRequest) Reset()         { *m = PutUserBaseRequest{} }
func (m *PutUserBaseRequest) String() string { return proto.CompactTextString(m) }
func (*PutUserBaseRequest) ProtoMessage()    {}
func (*PutUserBaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{1}
}

func (m *PutUserBaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUserBaseRequest.Unmarshal(m, b)
}
func (m *PutUserBaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUserBaseRequest.Marshal(b, m, deterministic)
}
func (m *PutUserBaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUserBaseRequest.Merge(m, src)
}
func (m *PutUserBaseRequest) XXX_Size() int {
	return xxx_messageInfo_PutUserBaseRequest.Size(m)
}
func (m *PutUserBaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUserBaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutUserBaseRequest proto.InternalMessageInfo

func (m *PutUserBaseRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PutUserBaseRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *PutUserBaseRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *PutUserBaseRequest) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PutUserBaseRequest) GetGender() int64 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *PutUserBaseRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *PutUserBaseRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *PutUserBaseRequest) GetProfession() string {
	if m != nil {
		return m.Profession
	}
	return ""
}

func (m *PutUserBaseRequest) GetBrief() string {
	if m != nil {
		return m.Brief
	}
	return ""
}

type UserInfoWithToken struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	Token                string    `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoWithToken) Reset()         { *m = UserInfoWithToken{} }
func (m *UserInfoWithToken) String() string { return proto.CompactTextString(m) }
func (*UserInfoWithToken) ProtoMessage()    {}
func (*UserInfoWithToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{2}
}

func (m *UserInfoWithToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoWithToken.Unmarshal(m, b)
}
func (m *UserInfoWithToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoWithToken.Marshal(b, m, deterministic)
}
func (m *UserInfoWithToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoWithToken.Merge(m, src)
}
func (m *UserInfoWithToken) XXX_Size() int {
	return xxx_messageInfo_UserInfoWithToken.Size(m)
}
func (m *UserInfoWithToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoWithToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoWithToken proto.InternalMessageInfo

func (m *UserInfoWithToken) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *UserInfoWithToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 用户角色
type UserRoles struct {
	Roles                []*RoleInfo `protobuf:"bytes,11,rep,name=Roles,proto3" json:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserRoles) Reset()         { *m = UserRoles{} }
func (m *UserRoles) String() string { return proto.CompactTextString(m) }
func (*UserRoles) ProtoMessage()    {}
func (*UserRoles) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{3}
}

func (m *UserRoles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRoles.Unmarshal(m, b)
}
func (m *UserRoles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRoles.Marshal(b, m, deterministic)
}
func (m *UserRoles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoles.Merge(m, src)
}
func (m *UserRoles) XXX_Size() int {
	return xxx_messageInfo_UserRoles.Size(m)
}
func (m *UserRoles) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoles.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoles proto.InternalMessageInfo

func (m *UserRoles) GetRoles() []*RoleInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

// id查询用户信息
type UIDInput struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UIDInput) Reset()         { *m = UIDInput{} }
func (m *UIDInput) String() string { return proto.CompactTextString(m) }
func (*UIDInput) ProtoMessage()    {}
func (*UIDInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{4}
}

func (m *UIDInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UIDInput.Unmarshal(m, b)
}
func (m *UIDInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UIDInput.Marshal(b, m, deterministic)
}
func (m *UIDInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UIDInput.Merge(m, src)
}
func (m *UIDInput) XXX_Size() int {
	return xxx_messageInfo_UIDInput.Size(m)
}
func (m *UIDInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UIDInput.DiscardUnknown(m)
}

var xxx_messageInfo_UIDInput proto.InternalMessageInfo

func (m *UIDInput) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type RoleInfo struct {
	Role                 string   `protobuf:"bytes,1,opt,name=Role,proto3" json:"Role,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleInfo) Reset()         { *m = RoleInfo{} }
func (m *RoleInfo) String() string { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()    {}
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{5}
}

func (m *RoleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleInfo.Unmarshal(m, b)
}
func (m *RoleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleInfo.Marshal(b, m, deterministic)
}
func (m *RoleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleInfo.Merge(m, src)
}
func (m *RoleInfo) XXX_Size() int {
	return xxx_messageInfo_RoleInfo.Size(m)
}
func (m *RoleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoleInfo proto.InternalMessageInfo

func (m *RoleInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *RoleInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// 第三方登录请求
type OauthLoginRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OauthLoginRequest) Reset()         { *m = OauthLoginRequest{} }
func (m *OauthLoginRequest) String() string { return proto.CompactTextString(m) }
func (*OauthLoginRequest) ProtoMessage()    {}
func (*OauthLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{6}
}

func (m *OauthLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OauthLoginRequest.Unmarshal(m, b)
}
func (m *OauthLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OauthLoginRequest.Marshal(b, m, deterministic)
}
func (m *OauthLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OauthLoginRequest.Merge(m, src)
}
func (m *OauthLoginRequest) XXX_Size() int {
	return xxx_messageInfo_OauthLoginRequest.Size(m)
}
func (m *OauthLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OauthLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OauthLoginRequest proto.InternalMessageInfo

func (m *OauthLoginRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *OauthLoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ErrorResponse struct {
	ErrorInfo            AccountErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=account.AccountErrors" json:"ErrorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{7}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetErrorInfo() AccountErrors {
	if m != nil {
		return m.ErrorInfo
	}
	return AccountErrors_None
}

// 创建用户
type CreateUserInput struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Nickname             string   `protobuf:"bytes,7,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Extension            string   `protobuf:"bytes,4,opt,name=Extension,proto3" json:"Extension,omitempty"`
	IP                   string   `protobuf:"bytes,5,opt,name=IP,proto3" json:"IP,omitempty"`
	RegisterFrom         string   `protobuf:"bytes,6,opt,name=RegisterFrom,proto3" json:"RegisterFrom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserInput) Reset()         { *m = CreateUserInput{} }
func (m *CreateUserInput) String() string { return proto.CompactTextString(m) }
func (*CreateUserInput) ProtoMessage()    {}
func (*CreateUserInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{8}
}

func (m *CreateUserInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserInput.Unmarshal(m, b)
}
func (m *CreateUserInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserInput.Marshal(b, m, deterministic)
}
func (m *CreateUserInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserInput.Merge(m, src)
}
func (m *CreateUserInput) XXX_Size() int {
	return xxx_messageInfo_CreateUserInput.Size(m)
}
func (m *CreateUserInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserInput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserInput proto.InternalMessageInfo

func (m *CreateUserInput) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateUserInput) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CreateUserInput) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserInput) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateUserInput) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *CreateUserInput) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *CreateUserInput) GetRegisterFrom() string {
	if m != nil {
		return m.RegisterFrom
	}
	return ""
}

// 用户登录
type UserLoginRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Validate             bool     `protobuf:"varint,4,opt,name=Validate,proto3" json:"Validate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{9}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UserLoginRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserLoginRequest) GetValidate() bool {
	if m != nil {
		return m.Validate
	}
	return false
}

type UserToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{10}
}

func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (m *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(m, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 更新用户密码
type PutPassowrdRequest struct {
	UID                  int64    `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	FreshPassword        string   `protobuf:"bytes,3,opt,name=FreshPassword,proto3" json:"FreshPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutPassowrdRequest) Reset()         { *m = PutPassowrdRequest{} }
func (m *PutPassowrdRequest) String() string { return proto.CompactTextString(m) }
func (*PutPassowrdRequest) ProtoMessage()    {}
func (*PutPassowrdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{11}
}

func (m *PutPassowrdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPassowrdRequest.Unmarshal(m, b)
}
func (m *PutPassowrdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPassowrdRequest.Marshal(b, m, deterministic)
}
func (m *PutPassowrdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPassowrdRequest.Merge(m, src)
}
func (m *PutPassowrdRequest) XXX_Size() int {
	return xxx_messageInfo_PutPassowrdRequest.Size(m)
}
func (m *PutPassowrdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPassowrdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutPassowrdRequest proto.InternalMessageInfo

func (m *PutPassowrdRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *PutPassowrdRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PutPassowrdRequest) GetFreshPassword() string {
	if m != nil {
		return m.FreshPassword
	}
	return ""
}

// 获取用户密码是否是随机生成的
type PasswordRandomStatus struct {
	Random               int64    `protobuf:"varint,1,opt,name=Random,proto3" json:"Random,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordRandomStatus) Reset()         { *m = PasswordRandomStatus{} }
func (m *PasswordRandomStatus) String() string { return proto.CompactTextString(m) }
func (*PasswordRandomStatus) ProtoMessage()    {}
func (*PasswordRandomStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{12}
}

func (m *PasswordRandomStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordRandomStatus.Unmarshal(m, b)
}
func (m *PasswordRandomStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordRandomStatus.Marshal(b, m, deterministic)
}
func (m *PasswordRandomStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordRandomStatus.Merge(m, src)
}
func (m *PasswordRandomStatus) XXX_Size() int {
	return xxx_messageInfo_PasswordRandomStatus.Size(m)
}
func (m *PasswordRandomStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordRandomStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordRandomStatus proto.InternalMessageInfo

func (m *PasswordRandomStatus) GetRandom() int64 {
	if m != nil {
		return m.Random
	}
	return 0
}

type PutUserContactEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	UID                  int64    `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUserContactEmailRequest) Reset()         { *m = PutUserContactEmailRequest{} }
func (m *PutUserContactEmailRequest) String() string { return proto.CompactTextString(m) }
func (*PutUserContactEmailRequest) ProtoMessage()    {}
func (*PutUserContactEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{13}
}

func (m *PutUserContactEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUserContactEmailRequest.Unmarshal(m, b)
}
func (m *PutUserContactEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUserContactEmailRequest.Marshal(b, m, deterministic)
}
func (m *PutUserContactEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUserContactEmailRequest.Merge(m, src)
}
func (m *PutUserContactEmailRequest) XXX_Size() int {
	return xxx_messageInfo_PutUserContactEmailRequest.Size(m)
}
func (m *PutUserContactEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUserContactEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutUserContactEmailRequest proto.InternalMessageInfo

func (m *PutUserContactEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PutUserContactEmailRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type PutUserContactPhoneRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PhoneCode            string   `protobuf:"bytes,2,opt,name=PhoneCode,proto3" json:"PhoneCode,omitempty"`
	UID                  int64    `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUserContactPhoneRequest) Reset()         { *m = PutUserContactPhoneRequest{} }
func (m *PutUserContactPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*PutUserContactPhoneRequest) ProtoMessage()    {}
func (*PutUserContactPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{14}
}

func (m *PutUserContactPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUserContactPhoneRequest.Unmarshal(m, b)
}
func (m *PutUserContactPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUserContactPhoneRequest.Marshal(b, m, deterministic)
}
func (m *PutUserContactPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUserContactPhoneRequest.Merge(m, src)
}
func (m *PutUserContactPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_PutUserContactPhoneRequest.Size(m)
}
func (m *PutUserContactPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUserContactPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutUserContactPhoneRequest proto.InternalMessageInfo

func (m *PutUserContactPhoneRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PutUserContactPhoneRequest) GetPhoneCode() string {
	if m != nil {
		return m.PhoneCode
	}
	return ""
}

func (m *PutUserContactPhoneRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

type UserContact struct {
	Phone                string   `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PhoneCode            string   `protobuf:"bytes,2,opt,name=PhoneCode,proto3" json:"PhoneCode,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	WeChatId             string   `protobuf:"bytes,4,opt,name=WeChatId,proto3" json:"WeChatId,omitempty"`
	QQId                 string   `protobuf:"bytes,5,opt,name=QQId,proto3" json:"QQId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserContact) Reset()         { *m = UserContact{} }
func (m *UserContact) String() string { return proto.CompactTextString(m) }
func (*UserContact) ProtoMessage()    {}
func (*UserContact) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{15}
}

func (m *UserContact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserContact.Unmarshal(m, b)
}
func (m *UserContact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserContact.Marshal(b, m, deterministic)
}
func (m *UserContact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserContact.Merge(m, src)
}
func (m *UserContact) XXX_Size() int {
	return xxx_messageInfo_UserContact.Size(m)
}
func (m *UserContact) XXX_DiscardUnknown() {
	xxx_messageInfo_UserContact.DiscardUnknown(m)
}

var xxx_messageInfo_UserContact proto.InternalMessageInfo

func (m *UserContact) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserContact) GetPhoneCode() string {
	if m != nil {
		return m.PhoneCode
	}
	return ""
}

func (m *UserContact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserContact) GetWeChatId() string {
	if m != nil {
		return m.WeChatId
	}
	return ""
}

func (m *UserContact) GetQQId() string {
	if m != nil {
		return m.QQId
	}
	return ""
}

func init() {
	proto.RegisterEnum("account.Role", Role_name, Role_value)
	proto.RegisterEnum("account.AccountErrors", AccountErrors_name, AccountErrors_value)
	proto.RegisterType((*UserInfo)(nil), "account.UserInfo")
	proto.RegisterType((*PutUserBaseRequest)(nil), "account.PutUserBaseRequest")
	proto.RegisterType((*UserInfoWithToken)(nil), "account.UserInfoWithToken")
	proto.RegisterType((*UserRoles)(nil), "account.UserRoles")
	proto.RegisterType((*UIDInput)(nil), "account.UIDInput")
	proto.RegisterType((*RoleInfo)(nil), "account.RoleInfo")
	proto.RegisterType((*OauthLoginRequest)(nil), "account.OauthLoginRequest")
	proto.RegisterType((*ErrorResponse)(nil), "account.ErrorResponse")
	proto.RegisterType((*CreateUserInput)(nil), "account.CreateUserInput")
	proto.RegisterType((*UserLoginRequest)(nil), "account.UserLoginRequest")
	proto.RegisterType((*UserToken)(nil), "account.UserToken")
	proto.RegisterType((*PutPassowrdRequest)(nil), "account.PutPassowrdRequest")
	proto.RegisterType((*PasswordRandomStatus)(nil), "account.PasswordRandomStatus")
	proto.RegisterType((*PutUserContactEmailRequest)(nil), "account.PutUserContactEmailRequest")
	proto.RegisterType((*PutUserContactPhoneRequest)(nil), "account.PutUserContactPhoneRequest")
	proto.RegisterType((*UserContact)(nil), "account.UserContact")
}

func init() { proto.RegisterFile("account/account.proto", fileDescriptor_d66906c5773c9d08) }

var fileDescriptor_d66906c5773c9d08 = []byte{
	// 1145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0x59, 0x6f, 0xdb, 0x46,
	0x10, 0xb6, 0x2e, 0x5b, 0x1c, 0x5f, 0xf4, 0x56, 0xb5, 0x19, 0xc5, 0x09, 0x5c, 0x36, 0x40, 0x8d,
	0x00, 0x75, 0x01, 0x37, 0x79, 0xe8, 0x21, 0xa0, 0xbe, 0x2b, 0x20, 0xb0, 0x15, 0x3a, 0x76, 0xfa,
	0xca, 0x88, 0x6b, 0x8b, 0xb0, 0xc4, 0x55, 0xc9, 0x65, 0x1d, 0xbf, 0x0b, 0xe8, 0x4f, 0xe9, 0xcf,
	0x28, 0x7a, 0xa4, 0xd7, 0x2f, 0xe9, 0x73, 0x7f, 0x41, 0xb1, 0xb3, 0xcb, 0xe5, 0x21, 0x29, 0x6e,
	0xfc, 0xd8, 0x27, 0xed, 0xcc, 0xce, 0xcc, 0xce, 0xce, 0x7c, 0xf3, 0x2d, 0x05, 0xef, 0xbb, 0xdd,
	0x2e, 0x8b, 0x03, 0xfe, 0x89, 0xfa, 0xdd, 0x1a, 0x86, 0x8c, 0x33, 0x32, 0xa7, 0x44, 0xfb, 0xc7,
	0x0a, 0xd4, 0xcf, 0x22, 0x1a, 0xb6, 0x83, 0x0b, 0x46, 0x96, 0xa0, 0xdc, 0xf6, 0xac, 0xd2, 0x46,
	0x69, 0xb3, 0xe2, 0x94, 0xdb, 0x1e, 0x59, 0x07, 0xe3, 0x19, 0xbb, 0xf4, 0x83, 0x63, 0x77, 0x40,
	0xad, 0xf2, 0x46, 0x69, 0xd3, 0x70, 0x52, 0x05, 0x69, 0x42, 0xfd, 0xd8, 0xef, 0x5e, 0x05, 0x62,
	0xb3, 0x82, 0x9b, 0x5a, 0x26, 0x26, 0x54, 0x76, 0x2e, 0xa9, 0x55, 0xc5, 0x50, 0x62, 0x49, 0x56,
	0x61, 0xf6, 0x88, 0x06, 0x1e, 0x0d, 0xad, 0x1a, 0x2a, 0x95, 0x24, 0xf4, 0x3b, 0xdf, 0xb9, 0xdc,
	0x0d, 0xad, 0x59, 0x8c, 0xa1, 0x24, 0x11, 0xfd, 0x19, 0xeb, 0xba, 0xdc, 0x67, 0x81, 0x35, 0x27,
	0xa3, 0x27, 0x32, 0x79, 0x08, 0xd0, 0x09, 0xd9, 0x05, 0x8d, 0x22, 0xb1, 0x5b, 0xc7, 0xdd, 0x8c,
	0x46, 0xc4, 0x3c, 0xe5, 0x2e, 0x8f, 0x23, 0xcb, 0x90, 0x67, 0x49, 0x89, 0x34, 0xa0, 0xb6, 0x1b,
	0xfa, 0xf4, 0xc2, 0x5a, 0x40, 0x17, 0x29, 0x08, 0xed, 0xc1, 0xc0, 0xf5, 0xfb, 0xd6, 0xa2, 0xd4,
	0xa2, 0x20, 0xb4, 0x9d, 0x1e, 0x0b, 0xa8, 0xb5, 0x24, 0xb5, 0x28, 0x88, 0x8a, 0xe0, 0x62, 0x8f,
	0x79, 0xd4, 0x5a, 0x96, 0x15, 0xd1, 0x0a, 0x91, 0xf3, 0x4b, 0xba, 0xd7, 0x73, 0x79, 0xdb, 0xb3,
	0x4c, 0x99, 0x73, 0x22, 0x13, 0x02, 0xd5, 0xe7, 0xcf, 0xdb, 0x9e, 0xb5, 0x82, 0x7a, 0x5c, 0x0b,
	0xfb, 0x8e, 0x1b, 0x45, 0xd7, 0x2c, 0xf4, 0x2c, 0x22, 0xed, 0x13, 0x99, 0x7c, 0x04, 0x35, 0x87,
	0xf5, 0x69, 0x64, 0xbd, 0xb7, 0x51, 0xd9, 0x9c, 0xdf, 0x5e, 0xd9, 0x4a, 0x1a, 0x28, 0xb4, 0xa2,
	0x5b, 0x8e, 0xdc, 0xb7, 0xff, 0x29, 0x01, 0xe9, 0xc4, 0x5c, 0x34, 0x71, 0xd7, 0x8d, 0xa8, 0x43,
	0xbf, 0x8d, 0x69, 0xc4, 0xff, 0x37, 0xbd, 0xd4, 0x3d, 0x33, 0x32, 0x3d, 0xb3, 0xbf, 0x81, 0x95,
	0x04, 0xb5, 0x2f, 0x7d, 0xde, 0x7b, 0xc1, 0xae, 0x68, 0x40, 0x3e, 0x4e, 0xa1, 0x8c, 0x17, 0xcf,
	0x56, 0x2d, 0xd9, 0x70, 0x52, 0xb4, 0x37, 0xa0, 0x86, 0x7e, 0xaa, 0x1a, 0x52, 0xb0, 0x9f, 0x80,
	0x21, 0x2c, 0xb0, 0xb6, 0x69, 0x13, 0xe6, 0x6f, 0x69, 0xc2, 0x3a, 0xd4, 0xcf, 0xda, 0xfb, 0xed,
	0x60, 0x18, 0x73, 0x51, 0xaf, 0xb3, 0xf6, 0xbe, 0x2a, 0xbd, 0x58, 0xda, 0x5f, 0x41, 0x3d, 0x71,
	0x10, 0x38, 0x10, 0x6b, 0xdc, 0x36, 0x1c, 0x5c, 0x93, 0x0d, 0x98, 0xdf, 0xa7, 0x51, 0x37, 0xf4,
	0x87, 0x58, 0x22, 0x99, 0x4f, 0x56, 0x65, 0x7f, 0x01, 0x2b, 0x27, 0x6e, 0xcc, 0x7b, 0xd8, 0xb1,
	0xa4, 0xc5, 0x04, 0xaa, 0x2f, 0x6e, 0x86, 0x3a, 0x94, 0x58, 0x0b, 0x1d, 0x62, 0x53, 0xc6, 0xc0,
	0xb5, 0x7d, 0x00, 0x8b, 0x07, 0x61, 0xc8, 0x42, 0x87, 0x46, 0x43, 0x16, 0x44, 0x94, 0x3c, 0x01,
	0x03, 0x15, 0xba, 0x52, 0x4b, 0xdb, 0xab, 0xfa, 0x6a, 0x3b, 0xf2, 0x17, 0x0d, 0x22, 0x27, 0x35,
	0xb4, 0xdf, 0x94, 0x60, 0x79, 0x2f, 0xa4, 0x2e, 0xa7, 0xb2, 0x84, 0xe2, 0xae, 0x93, 0x52, 0x68,
	0x40, 0xed, 0xdc, 0xed, 0xc7, 0x49, 0x0e, 0x52, 0xc8, 0x61, 0xbd, 0x52, 0xc0, 0x7a, 0x16, 0x7d,
	0x73, 0x05, 0xf4, 0xad, 0x83, 0x71, 0xf0, 0x9a, 0xd3, 0x00, 0xe1, 0x51, 0x95, 0xb8, 0xd5, 0x0a,
	0x44, 0x79, 0x07, 0x51, 0x68, 0x38, 0xe5, 0x76, 0x87, 0xd8, 0xb0, 0xe0, 0xd0, 0x4b, 0x3f, 0xe2,
	0x34, 0x3c, 0x0c, 0xd9, 0x40, 0xe1, 0x30, 0xa7, 0xb3, 0x39, 0x98, 0xe2, 0x02, 0xb7, 0x96, 0xf2,
	0x4e, 0xf7, 0x38, 0x77, 0xfb, 0xbe, 0xe7, 0x72, 0x39, 0x2e, 0x75, 0x47, 0xcb, 0xf6, 0x07, 0x12,
	0x57, 0x12, 0xa9, 0x1a, 0x7a, 0xa5, 0x2c, 0xf4, 0x7a, 0x38, 0xc8, 0x22, 0x1a, 0xbb, 0x0e, 0xbd,
	0x24, 0xb5, 0x31, 0x38, 0xe5, 0x52, 0x28, 0x17, 0x52, 0x78, 0x04, 0x8b, 0x87, 0x21, 0x8d, 0x7a,
	0x85, 0x1c, 0xf3, 0x4a, 0x7b, 0x0b, 0x1a, 0xc9, 0xda, 0x71, 0x03, 0x8f, 0x0d, 0x14, 0x41, 0xae,
	0xc2, 0xac, 0x94, 0xd5, 0x71, 0x4a, 0xb2, 0xf7, 0xa1, 0xa9, 0x28, 0x66, 0x8f, 0x05, 0xdc, 0xed,
	0x72, 0xe4, 0xc8, 0x24, 0x43, 0x4d, 0xa0, 0xa5, 0x2c, 0x81, 0xaa, 0xbc, 0xcb, 0xe9, 0x18, 0xbc,
	0x2a, 0x46, 0x41, 0xe6, 0xcc, 0x44, 0x91, 0x84, 0x5b, 0x9a, 0x4a, 0xb8, 0xe5, 0x22, 0xe1, 0xaa,
	0x33, 0x2a, 0xe9, 0x19, 0xdf, 0x97, 0x60, 0x3e, 0x73, 0xc2, 0x9d, 0xa2, 0xea, 0xfb, 0x54, 0xb2,
	0xf7, 0xc9, 0x92, 0x7b, 0x75, 0x0a, 0xb9, 0xd7, 0x52, 0x72, 0x7f, 0xfc, 0xb9, 0x1c, 0x74, 0xb2,
	0x2c, 0x86, 0xfb, 0xc2, 0x8d, 0xfb, 0x5c, 0x88, 0xe6, 0x0c, 0x31, 0xa0, 0xb6, 0xe3, 0x0d, 0xfc,
	0xc0, 0x2c, 0x11, 0x80, 0xd9, 0x9d, 0x98, 0xf7, 0x58, 0x68, 0x96, 0xc5, 0xfa, 0xdc, 0xa7, 0xd7,
	0x34, 0x34, 0x2b, 0x8f, 0x7f, 0x28, 0xc3, 0x62, 0x6e, 0x0e, 0x49, 0x1d, 0xaa, 0xc7, 0x2c, 0x10,
	0xee, 0x04, 0x16, 0xc4, 0x05, 0x8f, 0x19, 0x3f, 0x64, 0x71, 0xe0, 0x99, 0x3f, 0x8d, 0x5a, 0x64,
	0x55, 0x42, 0x5a, 0x4e, 0xe7, 0xa1, 0xeb, 0xf7, 0xa9, 0x67, 0xfe, 0x9c, 0xea, 0xcf, 0x86, 0x5e,
	0xaa, 0xff, 0x65, 0xd4, 0x22, 0x6b, 0x92, 0x3e, 0x93, 0x21, 0x3b, 0x78, 0xed, 0x47, 0xdc, 0xfc,
	0x75, 0xd4, 0x22, 0x16, 0x10, 0x3d, 0x1b, 0xc7, 0x7a, 0xe7, 0xcd, 0xa8, 0x45, 0x1a, 0xb0, 0x24,
	0x76, 0xb0, 0x4a, 0x52, 0xfb, 0x5b, 0xaa, 0xc5, 0x0a, 0x49, 0xed, 0xef, 0xa3, 0x16, 0x79, 0x00,
	0x6b, 0x68, 0xab, 0x20, 0xb6, 0xd7, 0xa3, 0xdd, 0x2b, 0x75, 0xfa, 0x1f, 0xa3, 0x16, 0x79, 0x04,
	0x0f, 0xf1, 0xb5, 0xf2, 0x03, 0xaf, 0x08, 0x29, 0x65, 0xf5, 0xe7, 0x54, 0x2b, 0x3c, 0x5f, 0x59,
	0xfd, 0x35, 0x6a, 0x6d, 0xff, 0x5d, 0x07, 0x43, 0x55, 0xea, 0xf4, 0x9c, 0x3c, 0x85, 0xf9, 0x23,
	0xca, 0x35, 0xc3, 0x67, 0xe8, 0x5f, 0x91, 0x73, 0x73, 0xfc, 0x45, 0xb0, 0x67, 0x48, 0x0b, 0x48,
	0xc6, 0x6d, 0xf7, 0x46, 0x0e, 0x29, 0xc9, 0x99, 0xa2, 0x6e, 0xb2, 0xfb, 0x09, 0xdc, 0xcb, 0xf2,
	0xa2, 0x88, 0x90, 0xbe, 0xac, 0x96, 0xf6, 0x28, 0x70, 0x67, 0x33, 0xa5, 0xdc, 0x1c, 0x3b, 0xdb,
	0x33, 0xe4, 0x08, 0x16, 0x54, 0x3e, 0x32, 0x93, 0x7b, 0xb9, 0x53, 0xb3, 0xc4, 0xd5, 0x6c, 0x8e,
	0x25, 0xa4, 0xdf, 0x43, 0x7b, 0x86, 0x7c, 0x09, 0x8b, 0x58, 0x7c, 0xcd, 0xa6, 0xe3, 0xf9, 0xbf,
	0x25, 0x8d, 0xcf, 0x00, 0xd0, 0x5b, 0xce, 0xcc, 0x9d, 0x5c, 0xe5, 0xe8, 0xbc, 0x93, 0x6b, 0x0b,
	0x96, 0xd0, 0x35, 0x2d, 0xe1, 0x3b, 0xb9, 0x7f, 0x0d, 0xcb, 0x8a, 0x64, 0x34, 0x27, 0xde, 0xd7,
	0xc6, 0xe3, 0xf4, 0xfa, 0x9f, 0x22, 0x89, 0xef, 0x2a, 0x04, 0x54, 0x2e, 0x52, 0xe1, 0x8b, 0xeb,
	0x2d, 0x91, 0x4e, 0x61, 0x2d, 0xdb, 0xcf, 0xdd, 0x1b, 0x7c, 0xcb, 0xe5, 0x27, 0xa3, 0x76, 0x1a,
	0x7b, 0xdf, 0x6f, 0xe9, 0xed, 0x09, 0xdc, 0x57, 0x41, 0x27, 0x52, 0xf9, 0x04, 0xec, 0x3f, 0x48,
	0xb3, 0x9f, 0xe4, 0x71, 0x0a, 0x8d, 0x49, 0x23, 0x49, 0x3e, 0x2c, 0x5e, 0x7a, 0xc2, 0x1b, 0x30,
	0xed, 0xf2, 0x13, 0x82, 0x4a, 0x34, 0x4d, 0x0b, 0x9a, 0x7d, 0x12, 0xa6, 0x06, 0x4d, 0xe7, 0x55,
	0x79, 0x4d, 0x9b, 0xf6, 0x46, 0xae, 0x82, 0xc9, 0x9b, 0xf0, 0x54, 0x8f, 0x97, 0xfc, 0xca, 0x9b,
	0xe0, 0x98, 0x9f, 0x7d, 0x34, 0x7b, 0x35, 0x8b, 0x7f, 0x9d, 0x3e, 0xfd, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x8c, 0x83, 0x1e, 0xb0, 0x53, 0x0d, 0x00, 0x00,
}
