// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: file/file.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FileSV service

func NewFileSVEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FileSV service

type FileSVService interface {
	// 获取用户支付数据信息
	PostImage(ctx context.Context, in *PostFileRequest, opts ...client.CallOption) (*PostFileResponse, error)
}

type fileSVService struct {
	c    client.Client
	name string
}

func NewFileSVService(name string, c client.Client) FileSVService {
	return &fileSVService{
		c:    c,
		name: name,
	}
}

func (c *fileSVService) PostImage(ctx context.Context, in *PostFileRequest, opts ...client.CallOption) (*PostFileResponse, error) {
	req := c.c.NewRequest(c.name, "FileSV.PostImage", in)
	out := new(PostFileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileSV service

type FileSVHandler interface {
	// 获取用户支付数据信息
	PostImage(context.Context, *PostFileRequest, *PostFileResponse) error
}

func RegisterFileSVHandler(s server.Server, hdlr FileSVHandler, opts ...server.HandlerOption) error {
	type fileSV interface {
		PostImage(ctx context.Context, in *PostFileRequest, out *PostFileResponse) error
	}
	type FileSV struct {
		fileSV
	}
	h := &fileSVHandler{hdlr}
	return s.Handle(s.NewHandler(&FileSV{h}, opts...))
}

type fileSVHandler struct {
	FileSVHandler
}

func (h *fileSVHandler) PostImage(ctx context.Context, in *PostFileRequest, out *PostFileResponse) error {
	return h.FileSVHandler.PostImage(ctx, in, out)
}
