// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: counter/counter.proto

package counter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CounterSV service

type CounterSVService interface {
	// 获取文章计数
	GetArticleCountInfo(ctx context.Context, in *IntRequest, opts ...client.CallOption) (*ArticleCountInfo, error)
}

type counterSVService struct {
	c    client.Client
	name string
}

func NewCounterSVService(name string, c client.Client) CounterSVService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "counter"
	}
	return &counterSVService{
		c:    c,
		name: name,
	}
}

func (c *counterSVService) GetArticleCountInfo(ctx context.Context, in *IntRequest, opts ...client.CallOption) (*ArticleCountInfo, error) {
	req := c.c.NewRequest(c.name, "CounterSV.GetArticleCountInfo", in)
	out := new(ArticleCountInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CounterSV service

type CounterSVHandler interface {
	// 获取文章计数
	GetArticleCountInfo(context.Context, *IntRequest, *ArticleCountInfo) error
}

func RegisterCounterSVHandler(s server.Server, hdlr CounterSVHandler, opts ...server.HandlerOption) error {
	type counterSV interface {
		GetArticleCountInfo(ctx context.Context, in *IntRequest, out *ArticleCountInfo) error
	}
	type CounterSV struct {
		counterSV
	}
	h := &counterSVHandler{hdlr}
	return s.Handle(s.NewHandler(&CounterSV{h}, opts...))
}

type counterSVHandler struct {
	CounterSVHandler
}

func (h *counterSVHandler) GetArticleCountInfo(ctx context.Context, in *IntRequest, out *ArticleCountInfo) error {
	return h.CounterSVHandler.GetArticleCountInfo(ctx, in, out)
}
