// Code generated by protoc-gen-go. DO NOT EDIT.
// source: counter/counter.proto

package counter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CounterErrors int32

const (
	CounterErrors_None         CounterErrors = 0
	CounterErrors_UpdateFailed CounterErrors = 4000001
)

var CounterErrors_name = map[int32]string{
	0:       "None",
	4000001: "UpdateFailed",
}

var CounterErrors_value = map[string]int32{
	"None":         0,
	"UpdateFailed": 4000001,
}

func (x CounterErrors) String() string {
	return proto.EnumName(CounterErrors_name, int32(x))
}

func (CounterErrors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_189c0686f57a5de6, []int{0}
}

type IntRequest struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntRequest) Reset()         { *m = IntRequest{} }
func (m *IntRequest) String() string { return proto.CompactTextString(m) }
func (*IntRequest) ProtoMessage()    {}
func (*IntRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_189c0686f57a5de6, []int{0}
}

func (m *IntRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntRequest.Unmarshal(m, b)
}
func (m *IntRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntRequest.Marshal(b, m, deterministic)
}
func (m *IntRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntRequest.Merge(m, src)
}
func (m *IntRequest) XXX_Size() int {
	return xxx_messageInfo_IntRequest.Size(m)
}
func (m *IntRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IntRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IntRequest proto.InternalMessageInfo

func (m *IntRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ErrorResponse struct {
	ErrorInfo            CounterErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=counter.CounterErrors" json:"ErrorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_189c0686f57a5de6, []int{1}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetErrorInfo() CounterErrors {
	if m != nil {
		return m.ErrorInfo
	}
	return CounterErrors_None
}

type ArticleCountInfo struct {
	Comment              uint64   `protobuf:"varint,1,opt,name=Comment,proto3" json:"Comment,omitempty"`
	Like                 uint64   `protobuf:"varint,2,opt,name=Like,proto3" json:"Like,omitempty"`
	Collect              uint64   `protobuf:"varint,3,opt,name=Collect,proto3" json:"Collect,omitempty"`
	DisLike              uint64   `protobuf:"varint,4,opt,name=DisLike,proto3" json:"DisLike,omitempty"`
	PageView             uint64   `protobuf:"varint,5,opt,name=PageView,proto3" json:"PageView,omitempty"`
	RewardTimes          uint64   `protobuf:"varint,6,opt,name=RewardTimes,proto3" json:"RewardTimes,omitempty"`
	RewardTotal          float64  `protobuf:"fixed64,7,opt,name=RewardTotal,proto3" json:"RewardTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleCountInfo) Reset()         { *m = ArticleCountInfo{} }
func (m *ArticleCountInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleCountInfo) ProtoMessage()    {}
func (*ArticleCountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_189c0686f57a5de6, []int{2}
}

func (m *ArticleCountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleCountInfo.Unmarshal(m, b)
}
func (m *ArticleCountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleCountInfo.Marshal(b, m, deterministic)
}
func (m *ArticleCountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleCountInfo.Merge(m, src)
}
func (m *ArticleCountInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleCountInfo.Size(m)
}
func (m *ArticleCountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleCountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleCountInfo proto.InternalMessageInfo

func (m *ArticleCountInfo) GetComment() uint64 {
	if m != nil {
		return m.Comment
	}
	return 0
}

func (m *ArticleCountInfo) GetLike() uint64 {
	if m != nil {
		return m.Like
	}
	return 0
}

func (m *ArticleCountInfo) GetCollect() uint64 {
	if m != nil {
		return m.Collect
	}
	return 0
}

func (m *ArticleCountInfo) GetDisLike() uint64 {
	if m != nil {
		return m.DisLike
	}
	return 0
}

func (m *ArticleCountInfo) GetPageView() uint64 {
	if m != nil {
		return m.PageView
	}
	return 0
}

func (m *ArticleCountInfo) GetRewardTimes() uint64 {
	if m != nil {
		return m.RewardTimes
	}
	return 0
}

func (m *ArticleCountInfo) GetRewardTotal() float64 {
	if m != nil {
		return m.RewardTotal
	}
	return 0
}

type UserCountInfo struct {
	Articles             uint64   `protobuf:"varint,1,opt,name=Articles,proto3" json:"Articles,omitempty"`
	Comments             uint64   `protobuf:"varint,2,opt,name=Comments,proto3" json:"Comments,omitempty"`
	Commented            uint64   `protobuf:"varint,3,opt,name=Commented,proto3" json:"Commented,omitempty"`
	RewardTimes          uint64   `protobuf:"varint,4,opt,name=RewardTimes,proto3" json:"RewardTimes,omitempty"`
	RewardTotal          float64  `protobuf:"fixed64,5,opt,name=RewardTotal,proto3" json:"RewardTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCountInfo) Reset()         { *m = UserCountInfo{} }
func (m *UserCountInfo) String() string { return proto.CompactTextString(m) }
func (*UserCountInfo) ProtoMessage()    {}
func (*UserCountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_189c0686f57a5de6, []int{3}
}

func (m *UserCountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCountInfo.Unmarshal(m, b)
}
func (m *UserCountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCountInfo.Marshal(b, m, deterministic)
}
func (m *UserCountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCountInfo.Merge(m, src)
}
func (m *UserCountInfo) XXX_Size() int {
	return xxx_messageInfo_UserCountInfo.Size(m)
}
func (m *UserCountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserCountInfo proto.InternalMessageInfo

func (m *UserCountInfo) GetArticles() uint64 {
	if m != nil {
		return m.Articles
	}
	return 0
}

func (m *UserCountInfo) GetComments() uint64 {
	if m != nil {
		return m.Comments
	}
	return 0
}

func (m *UserCountInfo) GetCommented() uint64 {
	if m != nil {
		return m.Commented
	}
	return 0
}

func (m *UserCountInfo) GetRewardTimes() uint64 {
	if m != nil {
		return m.RewardTimes
	}
	return 0
}

func (m *UserCountInfo) GetRewardTotal() float64 {
	if m != nil {
		return m.RewardTotal
	}
	return 0
}

type UpdateRequest struct {
	Field                string   `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	ID                   uint64   `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_189c0686f57a5de6, []int{4}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *UpdateRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *UpdateRequest) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterEnum("counter.CounterErrors", CounterErrors_name, CounterErrors_value)
	proto.RegisterType((*IntRequest)(nil), "counter.IntRequest")
	proto.RegisterType((*ErrorResponse)(nil), "counter.ErrorResponse")
	proto.RegisterType((*ArticleCountInfo)(nil), "counter.ArticleCountInfo")
	proto.RegisterType((*UserCountInfo)(nil), "counter.UserCountInfo")
	proto.RegisterType((*UpdateRequest)(nil), "counter.UpdateRequest")
}

func init() { proto.RegisterFile("counter/counter.proto", fileDescriptor_189c0686f57a5de6) }

var fileDescriptor_189c0686f57a5de6 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdf, 0xee, 0xd2, 0x30,
	0x18, 0x75, 0xfb, 0x8d, 0x3f, 0xfb, 0x64, 0x40, 0x8a, 0x9a, 0x49, 0xbc, 0x20, 0xbb, 0x22, 0x5e,
	0x60, 0x82, 0xde, 0x79, 0x45, 0x18, 0x90, 0x45, 0x63, 0x4c, 0x15, 0xee, 0x27, 0xfb, 0x34, 0x8b,
	0x63, 0xc5, 0xb6, 0x84, 0x6b, 0x5f, 0xc1, 0xf8, 0x12, 0xbe, 0x8f, 0x8f, 0xe2, 0x03, 0x18, 0xda,
	0xb2, 0x75, 0x62, 0x62, 0xbc, 0x6a, 0xcf, 0xf9, 0x4e, 0xdb, 0xef, 0xb4, 0xa7, 0xf0, 0x70, 0xcf,
	0x4e, 0xa5, 0x44, 0xfe, 0xcc, 0x8c, 0xb3, 0x23, 0x67, 0x92, 0x91, 0x8e, 0x81, 0x51, 0x04, 0x90,
	0x94, 0x92, 0xe2, 0x97, 0x13, 0x0a, 0x49, 0x1e, 0x40, 0x6b, 0x97, 0x16, 0x27, 0x0c, 0x9d, 0x89,
	0x33, 0xbd, 0xa3, 0x1a, 0x44, 0x2b, 0x08, 0x56, 0x9c, 0x33, 0x4e, 0x51, 0x1c, 0x59, 0x29, 0x90,
	0xbc, 0x00, 0x5f, 0x11, 0x49, 0xf9, 0x91, 0x29, 0x69, 0x7f, 0xfe, 0x68, 0x76, 0x3d, 0x60, 0xa9,
	0x47, 0x25, 0x10, 0xb4, 0x16, 0x46, 0x3f, 0x1d, 0x18, 0x2e, 0xb8, 0xcc, 0xf7, 0x05, 0x2a, 0xcd,
	0x85, 0x24, 0x21, 0x74, 0x96, 0xec, 0x70, 0xc0, 0x52, 0xaa, 0x8d, 0x3c, 0x7a, 0x85, 0x84, 0x80,
	0xf7, 0x3a, 0xff, 0x8c, 0xa1, 0xab, 0x68, 0x35, 0xd7, 0xea, 0xa2, 0xc0, 0xbd, 0x0c, 0xef, 0xae,
	0x6a, 0x05, 0x2f, 0x95, 0x38, 0x17, 0x6a, 0x81, 0xa7, 0x2b, 0x06, 0x92, 0x31, 0x74, 0xdf, 0xa6,
	0x9f, 0x70, 0x97, 0xe3, 0x39, 0x6c, 0xa9, 0x52, 0x85, 0xc9, 0x04, 0xee, 0x53, 0x3c, 0xa7, 0x3c,
	0x7b, 0x9f, 0x1f, 0x50, 0x84, 0x6d, 0x55, 0xb6, 0x29, 0x4b, 0xc1, 0x64, 0x5a, 0x84, 0x9d, 0x89,
	0x33, 0x75, 0xa8, 0x4d, 0x45, 0x3f, 0x1c, 0x08, 0xb6, 0x02, 0x79, 0xed, 0x69, 0x0c, 0x5d, 0xe3,
	0x53, 0x18, 0x53, 0x15, 0xbe, 0xd4, 0x8c, 0x41, 0x61, 0x9c, 0x55, 0x98, 0x3c, 0x01, 0xdf, 0xcc,
	0x31, 0x33, 0xfe, 0x6a, 0xe2, 0xcf, 0x5e, 0xbd, 0x7f, 0xf6, 0xda, 0xba, 0xed, 0xf5, 0x15, 0x04,
	0xdb, 0x63, 0x96, 0x4a, 0xb4, 0x1e, 0x7c, 0x9d, 0x63, 0x91, 0xa9, 0x3e, 0x7d, 0xaa, 0x41, 0x1d,
	0x03, 0x57, 0xb3, 0x0a, 0x90, 0x3e, 0xb8, 0x49, 0x6c, 0xfa, 0x72, 0x93, 0xf8, 0xe9, 0x0c, 0x82,
	0xc6, 0x5b, 0x93, 0x2e, 0x78, 0x6f, 0x58, 0x89, 0xc3, 0x7b, 0x64, 0x04, 0x3d, 0x7d, 0xce, 0x3a,
	0xcd, 0x0b, 0xcc, 0x86, 0x5f, 0xbf, 0xfd, 0x72, 0xe6, 0xdf, 0x5d, 0xf0, 0x4d, 0x48, 0xde, 0xed,
	0xc8, 0x02, 0x06, 0x1b, 0x94, 0x76, 0x1e, 0xc8, 0xa8, 0xca, 0x50, 0x1d, 0xc9, 0xf1, 0xe3, 0x8a,
	0xbc, 0xc9, 0xce, 0x4b, 0xe8, 0x6d, 0x50, 0x56, 0x77, 0xff, 0xf7, 0xf5, 0x75, 0x30, 0x9b, 0x8f,
	0xb4, 0x80, 0x81, 0x6e, 0xb1, 0x5e, 0x6f, 0x49, 0xed, 0x4b, 0xb2, 0xb6, 0x68, 0x7e, 0x83, 0x18,
	0x88, 0x16, 0x36, 0x5c, 0xfc, 0xe7, 0x2e, 0x1f, 0xda, 0xea, 0x47, 0x3e, 0xff, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0xe3, 0x20, 0x2d, 0xaa, 0x03, 0x00, 0x00,
}
