// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: push/push.proto

package push

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendType int32

const (
	SendType_NoneSendType SendType = 0 // 默认值
	SendType_Mail         SendType = 1 // 邮箱
	SendType_Phone        SendType = 2 // 手机
)

// Enum value maps for SendType.
var (
	SendType_name = map[int32]string{
		0: "NoneSendType",
		1: "Mail",
		2: "Phone",
	}
	SendType_value = map[string]int32{
		"NoneSendType": 0,
		"Mail":         1,
		"Phone":        2,
	}
)

func (x SendType) Enum() *SendType {
	p := new(SendType)
	*p = x
	return p
}

func (x SendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendType) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_proto_enumTypes[0].Descriptor()
}

func (SendType) Type() protoreflect.EnumType {
	return &file_push_push_proto_enumTypes[0]
}

func (x SendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendType.Descriptor instead.
func (SendType) EnumDescriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

type PushErrors int32

const (
	PushErrors_None            PushErrors = 0       // 默认值
	PushErrors_PushCommonError PushErrors = 4000001 // 通用error
)

// Enum value maps for PushErrors.
var (
	PushErrors_name = map[int32]string{
		0:       "None",
		4000001: "PushCommonError",
	}
	PushErrors_value = map[string]int32{
		"None":            0,
		"PushCommonError": 4000001,
	}
)

func (x PushErrors) Enum() *PushErrors {
	p := new(PushErrors)
	*p = x
	return p
}

func (x PushErrors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushErrors) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_proto_enumTypes[1].Descriptor()
}

func (PushErrors) Type() protoreflect.EnumType {
	return &file_push_push_proto_enumTypes[1]
}

func (x PushErrors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushErrors.Descriptor instead.
func (PushErrors) EnumDescriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{1}
}

type CommonMessageType int32

const (
	CommonMessageType_NoneMessageType       CommonMessageType = 0 // 默认值
	CommonMessageType_Email                 CommonMessageType = 1 // 邮箱消息
	CommonMessageType_SMS                   CommonMessageType = 2 // 短信消息
	CommonMessageType_Chat                  CommonMessageType = 3 // 聊天消息
	CommonMessageType_Bot                   CommonMessageType = 4 // 机器人消息  - 企业微信 + 钉钉 + TG + 飞书
	CommonMessageType_WechatTemplateMessage CommonMessageType = 5 // 微信模板消息
)

// Enum value maps for CommonMessageType.
var (
	CommonMessageType_name = map[int32]string{
		0: "NoneMessageType",
		1: "Email",
		2: "SMS",
		3: "Chat",
		4: "Bot",
		5: "WechatTemplateMessage",
	}
	CommonMessageType_value = map[string]int32{
		"NoneMessageType":       0,
		"Email":                 1,
		"SMS":                   2,
		"Chat":                  3,
		"Bot":                   4,
		"WechatTemplateMessage": 5,
	}
)

func (x CommonMessageType) Enum() *CommonMessageType {
	p := new(CommonMessageType)
	*p = x
	return p
}

func (x CommonMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_proto_enumTypes[2].Descriptor()
}

func (CommonMessageType) Type() protoreflect.EnumType {
	return &file_push_push_proto_enumTypes[2]
}

func (x CommonMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonMessageType.Descriptor instead.
func (CommonMessageType) EnumDescriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{2}
}

// 机器人消息类型
type BotNotificationType int32

const (
	BotNotificationType_BotNotificationTypeNoneType BotNotificationType = 0 // 初始值 v2
	BotNotificationType_WechatWork                  BotNotificationType = 1 // 微信机器人消息  1
	BotNotificationType_FeiShu                      BotNotificationType = 2 // 飞书机器人消息  2
	BotNotificationType_DingTalk                    BotNotificationType = 3 // 钉钉机器人消息  4
	BotNotificationType_GoTify                      BotNotificationType = 4 // gotify 消息    - Android
	BotNotificationType_Bark                        BotNotificationType = 5 // Bark   消息    - iOS
)

// Enum value maps for BotNotificationType.
var (
	BotNotificationType_name = map[int32]string{
		0: "BotNotificationTypeNoneType",
		1: "WechatWork",
		2: "FeiShu",
		3: "DingTalk",
		4: "GoTify",
		5: "Bark",
	}
	BotNotificationType_value = map[string]int32{
		"BotNotificationTypeNoneType": 0,
		"WechatWork":                  1,
		"FeiShu":                      2,
		"DingTalk":                    3,
		"GoTify":                      4,
		"Bark":                        5,
	}
)

func (x BotNotificationType) Enum() *BotNotificationType {
	p := new(BotNotificationType)
	*p = x
	return p
}

func (x BotNotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotNotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_proto_enumTypes[3].Descriptor()
}

func (BotNotificationType) Type() protoreflect.EnumType {
	return &file_push_push_proto_enumTypes[3]
}

func (x BotNotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotNotificationType.Descriptor instead.
func (BotNotificationType) EnumDescriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{3}
}

type PushCaptchaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`                     // 验证码
	Sender     string   `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"`                 // 发送人
	Type       SendType `protobuf:"varint,3,opt,name=Type,proto3,enum=push.SendType" json:"Type,omitempty"` // 发送类型
	UID        int64    `protobuf:"varint,4,opt,name=UID,proto3" json:"UID,omitempty"`                      // 被发送人的UID
	Account    string   `protobuf:"bytes,5,opt,name=Account,proto3" json:"Account,omitempty"`               // 被发送人的账户
	NationCode string   `protobuf:"bytes,6,opt,name=NationCode,proto3" json:"NationCode,omitempty"`         // 手机号区号
}

func (x *PushCaptchaRequest) Reset() {
	*x = PushCaptchaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCaptchaRequest) ProtoMessage() {}

func (x *PushCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCaptchaRequest.ProtoReflect.Descriptor instead.
func (*PushCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushCaptchaRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PushCaptchaRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PushCaptchaRequest) GetType() SendType {
	if x != nil {
		return x.Type
	}
	return SendType_NoneSendType
}

func (x *PushCaptchaRequest) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *PushCaptchaRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PushCaptchaRequest) GetNationCode() string {
	if x != nil {
		return x.NationCode
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorInfo PushErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=push.PushErrors" json:"ErrorInfo,omitempty"` // 错误信息
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResponse) GetErrorInfo() PushErrors {
	if x != nil {
		return x.ErrorInfo
	}
	return PushErrors_None
}

type PushEmailNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To      string `protobuf:"bytes,1,opt,name=To,proto3" json:"To,omitempty"`           // 发送到
	Html    string `protobuf:"bytes,2,opt,name=Html,proto3" json:"Html,omitempty"`       // 发送内容
	Subject string `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"` // 主题内容
}

func (x *PushEmailNotificationRequest) Reset() {
	*x = PushEmailNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushEmailNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEmailNotificationRequest) ProtoMessage() {}

func (x *PushEmailNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEmailNotificationRequest.ProtoReflect.Descriptor instead.
func (*PushEmailNotificationRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{2}
}

func (x *PushEmailNotificationRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PushEmailNotificationRequest) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *PushEmailNotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type GetCaptchaVerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`                     // 验证码
	Account string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`               // 被发送人的账户
	UID     int64    `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`                      // 被发送人的UID
	Type    SendType `protobuf:"varint,4,opt,name=Type,proto3,enum=push.SendType" json:"Type,omitempty"` // 验证类型
}

func (x *GetCaptchaVerifyRequest) Reset() {
	*x = GetCaptchaVerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaptchaVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaVerifyRequest) ProtoMessage() {}

func (x *GetCaptchaVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaVerifyRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaVerifyRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{3}
}

func (x *GetCaptchaVerifyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetCaptchaVerifyRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetCaptchaVerifyRequest) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *GetCaptchaVerifyRequest) GetType() SendType {
	if x != nil {
		return x.Type
	}
	return SendType_NoneSendType
}

type StoreOrderMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID  string `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`   // 来源订单
	HTML     string `protobuf:"bytes,2,opt,name=HTML,proto3" json:"HTML,omitempty"`         // 邮件信息
	ExpireIn string `protobuf:"bytes,3,opt,name=ExpireIn,proto3" json:"ExpireIn,omitempty"` // 有效时间
}

func (x *StoreOrderMailRequest) Reset() {
	*x = StoreOrderMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreOrderMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOrderMailRequest) ProtoMessage() {}

func (x *StoreOrderMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOrderMailRequest.ProtoReflect.Descriptor instead.
func (*StoreOrderMailRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{4}
}

func (x *StoreOrderMailRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *StoreOrderMailRequest) GetHTML() string {
	if x != nil {
		return x.HTML
	}
	return ""
}

func (x *StoreOrderMailRequest) GetExpireIn() string {
	if x != nil {
		return x.ExpireIn
	}
	return ""
}

type PushWechatWorkGroupRobotNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"` // 内容信息
	Retry   int64  `protobuf:"varint,2,opt,name=Retry,proto3" json:"Retry,omitempty"`    // 重试次数
}

func (x *PushWechatWorkGroupRobotNotificationRequest) Reset() {
	*x = PushWechatWorkGroupRobotNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushWechatWorkGroupRobotNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushWechatWorkGroupRobotNotificationRequest) ProtoMessage() {}

func (x *PushWechatWorkGroupRobotNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushWechatWorkGroupRobotNotificationRequest.ProtoReflect.Descriptor instead.
func (*PushWechatWorkGroupRobotNotificationRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{5}
}

func (x *PushWechatWorkGroupRobotNotificationRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushWechatWorkGroupRobotNotificationRequest) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

type PushWechatTemplateMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUser string `protobuf:"bytes,1,opt,name=ToUser,proto3" json:"ToUser,omitempty"` // 用户的OpenID
	Type   string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`     // 默认微信 mp
	URL    string `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`       // 模板消息地址
	Data   string `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`     // 数据消息
}

func (x *PushWechatTemplateMessageRequest) Reset() {
	*x = PushWechatTemplateMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushWechatTemplateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushWechatTemplateMessageRequest) ProtoMessage() {}

func (x *PushWechatTemplateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushWechatTemplateMessageRequest.ProtoReflect.Descriptor instead.
func (*PushWechatTemplateMessageRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{6}
}

func (x *PushWechatTemplateMessageRequest) GetToUser() string {
	if x != nil {
		return x.ToUser
	}
	return ""
}

func (x *PushWechatTemplateMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PushWechatTemplateMessageRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *PushWechatTemplateMessageRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type SenderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP          string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`                   // 发送方IP
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"` // 发送方名称
}

func (x *SenderInfo) Reset() {
	*x = SenderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderInfo) ProtoMessage() {}

func (x *SenderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderInfo.ProtoReflect.Descriptor instead.
func (*SenderInfo) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{7}
}

func (x *SenderInfo) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *SenderInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// 邮件消息
type EmailNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To      string `protobuf:"bytes,1,opt,name=To,proto3" json:"To,omitempty"`           // 目标邮箱
	Html    string `protobuf:"bytes,2,opt,name=Html,proto3" json:"Html,omitempty"`       // 发送内容
	Subject string `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"` // 标题
}

func (x *EmailNotification) Reset() {
	*x = EmailNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailNotification) ProtoMessage() {}

func (x *EmailNotification) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailNotification.ProtoReflect.Descriptor instead.
func (*EmailNotification) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{8}
}

func (x *EmailNotification) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EmailNotification) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *EmailNotification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

// 手机短信消息
type SMSNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateID     string   `protobuf:"bytes,1,opt,name=TemplateID,proto3" json:"TemplateID,omitempty"`         // 短信模板ID
	PhoneNumber    string   `protobuf:"bytes,2,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`       // 手机号
	NationCode     string   `protobuf:"bytes,3,opt,name=NationCode,proto3" json:"NationCode,omitempty"`         // 手机号区号
	TemplateParams []string `protobuf:"bytes,4,rep,name=TemplateParams,proto3" json:"TemplateParams,omitempty"` // 短信模板参数
}

func (x *SMSNotification) Reset() {
	*x = SMSNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMSNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSNotification) ProtoMessage() {}

func (x *SMSNotification) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSNotification.ProtoReflect.Descriptor instead.
func (*SMSNotification) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{9}
}

func (x *SMSNotification) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *SMSNotification) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SMSNotification) GetNationCode() string {
	if x != nil {
		return x.NationCode
	}
	return ""
}

func (x *SMSNotification) GetTemplateParams() []string {
	if x != nil {
		return x.TemplateParams
	}
	return nil
}

// 机器人消息
type BotNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string              `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`                          // 消息内容 markdown
	Type    BotNotificationType `protobuf:"varint,2,opt,name=Type,proto3,enum=push.BotNotificationType" json:"Type,omitempty"` // 消息类型
}

func (x *BotNotification) Reset() {
	*x = BotNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotNotification) ProtoMessage() {}

func (x *BotNotification) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotNotification.ProtoReflect.Descriptor instead.
func (*BotNotification) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{10}
}

func (x *BotNotification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BotNotification) GetType() BotNotificationType {
	if x != nil {
		return x.Type
	}
	return BotNotificationType_BotNotificationTypeNoneType
}

// 机器人消息v2
// 消息类型 1 企业🤖 2 飞书🤖 4 钉钉🤖 8 PushPlus🤖
type BotNotificationV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"` // 消息内容 markdown
	Type    uint64 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *BotNotificationV2) Reset() {
	*x = BotNotificationV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotNotificationV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotNotificationV2) ProtoMessage() {}

func (x *BotNotificationV2) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotNotificationV2.ProtoReflect.Descriptor instead.
func (*BotNotificationV2) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{11}
}

func (x *BotNotificationV2) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BotNotificationV2) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type TemplateMessageDataObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"` // 数值
	Color string `protobuf:"bytes,2,opt,name=Color,proto3" json:"Color,omitempty"` // 文本色号
}

func (x *TemplateMessageDataObject) Reset() {
	*x = TemplateMessageDataObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateMessageDataObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateMessageDataObject) ProtoMessage() {}

func (x *TemplateMessageDataObject) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateMessageDataObject.ProtoReflect.Descriptor instead.
func (*TemplateMessageDataObject) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{12}
}

func (x *TemplateMessageDataObject) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TemplateMessageDataObject) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Miniprogram struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppID    string `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`       // 小程序应用ID
	PagePath string `protobuf:"bytes,2,opt,name=PagePath,proto3" json:"PagePath,omitempty"` // 小程序应用路径
}

func (x *Miniprogram) Reset() {
	*x = Miniprogram{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Miniprogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Miniprogram) ProtoMessage() {}

func (x *Miniprogram) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Miniprogram.ProtoReflect.Descriptor instead.
func (*Miniprogram) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{13}
}

func (x *Miniprogram) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *Miniprogram) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

// 微信模板消息
type WechatTemplateMessageNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUser      string                                `protobuf:"bytes,1,opt,name=ToUser,proto3" json:"ToUser,omitempty"`                                                                                     // 用户openID
	TemplateID  string                                `protobuf:"bytes,2,opt,name=TemplateID,proto3" json:"TemplateID,omitempty"`                                                                             // 模板ID
	URL         string                                `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`                                                                                           // 模板消息详情URL
	Data        map[string]*TemplateMessageDataObject `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 模板填充值
	Miniprogram *Miniprogram                          `protobuf:"bytes,5,opt,name=Miniprogram,proto3" json:"Miniprogram,omitempty"`                                                                           // 小程序配置
}

func (x *WechatTemplateMessageNotification) Reset() {
	*x = WechatTemplateMessageNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatTemplateMessageNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatTemplateMessageNotification) ProtoMessage() {}

func (x *WechatTemplateMessageNotification) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatTemplateMessageNotification.ProtoReflect.Descriptor instead.
func (*WechatTemplateMessageNotification) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{14}
}

func (x *WechatTemplateMessageNotification) GetToUser() string {
	if x != nil {
		return x.ToUser
	}
	return ""
}

func (x *WechatTemplateMessageNotification) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *WechatTemplateMessageNotification) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *WechatTemplateMessageNotification) GetData() map[string]*TemplateMessageDataObject {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WechatTemplateMessageNotification) GetMiniprogram() *Miniprogram {
	if x != nil {
		return x.Miniprogram
	}
	return nil
}

type PushCommonMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType                       CommonMessageType                  `protobuf:"varint,1,opt,name=MessageType,proto3,enum=push.CommonMessageType" json:"MessageType,omitempty"` // 消息类型
	SenderInfo                        *SenderInfo                        `protobuf:"bytes,2,opt,name=SenderInfo,proto3" json:"SenderInfo,omitempty"`                                // 推送方信息
	EmailNotification                 *EmailNotification                 `protobuf:"bytes,3,opt,name=EmailNotification,proto3" json:"EmailNotification,omitempty"`                  // 邮件消息结构
	SMSNotification                   *SMSNotification                   `protobuf:"bytes,4,opt,name=SMSNotification,proto3" json:"SMSNotification,omitempty"`                      // 短信消息结构
	BotNotification                   *BotNotification                   `protobuf:"bytes,5,opt,name=BotNotification,proto3" json:"BotNotification,omitempty"`                      // 机器人消息结构
	WechatTemplateMessageNotification *WechatTemplateMessageNotification `protobuf:"bytes,6,opt,name=WechatTemplateMessageNotification,proto3" json:"WechatTemplateMessageNotification,omitempty"`
	BotNotificationV2                 *BotNotificationV2                 `protobuf:"bytes,7,opt,name=BotNotificationV2,proto3" json:"BotNotificationV2,omitempty"` // 机器人消息v2
}

func (x *PushCommonMessageRequest) Reset() {
	*x = PushCommonMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushCommonMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCommonMessageRequest) ProtoMessage() {}

func (x *PushCommonMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCommonMessageRequest.ProtoReflect.Descriptor instead.
func (*PushCommonMessageRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{15}
}

func (x *PushCommonMessageRequest) GetMessageType() CommonMessageType {
	if x != nil {
		return x.MessageType
	}
	return CommonMessageType_NoneMessageType
}

func (x *PushCommonMessageRequest) GetSenderInfo() *SenderInfo {
	if x != nil {
		return x.SenderInfo
	}
	return nil
}

func (x *PushCommonMessageRequest) GetEmailNotification() *EmailNotification {
	if x != nil {
		return x.EmailNotification
	}
	return nil
}

func (x *PushCommonMessageRequest) GetSMSNotification() *SMSNotification {
	if x != nil {
		return x.SMSNotification
	}
	return nil
}

func (x *PushCommonMessageRequest) GetBotNotification() *BotNotification {
	if x != nil {
		return x.BotNotification
	}
	return nil
}

func (x *PushCommonMessageRequest) GetWechatTemplateMessageNotification() *WechatTemplateMessageNotification {
	if x != nil {
		return x.WechatTemplateMessageNotification
	}
	return nil
}

func (x *PushCommonMessageRequest) GetBotNotificationV2() *BotNotificationV2 {
	if x != nil {
		return x.BotNotificationV2
	}
	return nil
}

var File_push_push_proto protoreflect.FileDescriptor

var file_push_push_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x75, 0x73, 0x68, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x70, 0x75, 0x73, 0x68, 0x22, 0xb0, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x73, 0x68,
	0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3f, 0x0a, 0x0d, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5c, 0x0a, 0x1c, 0x50,
	0x75, 0x73, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x54,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x74, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x74, 0x6d, 0x6c, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x7d, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x55, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x61, 0x0a, 0x15, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x54, 0x4d, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x54, 0x4d, 0x4c, 0x12,
	0x1a, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x22, 0x5d, 0x0a, 0x2b, 0x50,
	0x75, 0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x52, 0x65, 0x74, 0x72, 0x79, 0x22, 0x74, 0x0a, 0x20, 0x50, 0x75,
	0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52,
	0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x3e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x20,
	0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x51, 0x0a, 0x11, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x74, 0x6d, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x74, 0x6d, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x0f, 0x53, 0x4d, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x22, 0x5a, 0x0a, 0x0f, 0x42, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2d,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x2e, 0x42, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x41, 0x0a,
	0x11, 0x42, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x56, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x47, 0x0a, 0x19, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x3f, 0x0a, 0x0b, 0x4d, 0x69, 0x6e,
	0x69, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0xc3, 0x02, 0x0a, 0x21, 0x57,
	0x65, 0x63, 0x68, 0x61, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x45, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x33, 0x0a, 0x0b, 0x4d, 0x69, 0x6e, 0x69, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x4d, 0x69,
	0x6e, 0x69, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x0b, 0x4d, 0x69, 0x6e, 0x69, 0x70,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x1a, 0x58, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x8e, 0x04, 0x0a, 0x18, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a,
	0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x45, 0x0a, 0x11, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x3f, 0x0a, 0x0f, 0x53, 0x4d, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x75, 0x73,
	0x68, 0x2e, 0x53, 0x4d, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0f, 0x53, 0x4d, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x0f, 0x42, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x75,
	0x73, 0x68, 0x2e, 0x42, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0f, 0x42, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x75, 0x0a, 0x21, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x21, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x11, 0x42, 0x6f,
	0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x32, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x42, 0x6f, 0x74,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x32, 0x52, 0x11,
	0x42, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56,
	0x32, 0x2a, 0x31, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a,
	0x0c, 0x4e, 0x6f, 0x6e, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x10, 0x02, 0x2a, 0x2e, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x0f,
	0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10,
	0x81, 0x92, 0xf4, 0x01, 0x2a, 0x6a, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x4e, 0x6f, 0x6e,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x4d, 0x53,
	0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03,
	0x42, 0x6f, 0x74, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x05,
	0x2a, 0x76, 0x0a, 0x13, 0x42, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x42, 0x6f, 0x74, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x6f,
	0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x65, 0x63, 0x68,
	0x61, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x65, 0x69, 0x53,
	0x68, 0x75, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x6c, 0x6b,
	0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x6f, 0x54, 0x69, 0x66, 0x79, 0x10, 0x04, 0x12, 0x08,
	0x0a, 0x04, 0x42, 0x61, 0x72, 0x6b, 0x10, 0x05, 0x32, 0xfb, 0x04, 0x0a, 0x06, 0x70, 0x75, 0x73,
	0x68, 0x53, 0x56, 0x12, 0x3c, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x43, 0x61, 0x70, 0x74, 0x63,
	0x68, 0x61, 0x12, 0x18, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x43, 0x61,
	0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x46, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x1d, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x15, 0x50, 0x75, 0x73,
	0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x2e,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73,
	0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x0d, 0x50, 0x6f, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c,
	0x12, 0x1b, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6e, 0x0a, 0x24, 0x50, 0x75, 0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x2e, 0x70, 0x75, 0x73,
	0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x57, 0x6f, 0x72, 0x6b,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x58, 0x0a, 0x19, 0x50, 0x75, 0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x26, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x11,
	0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x70, 0x75, 0x73, 0x68,
	0x3b, 0x70, 0x75, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_push_push_proto_rawDescOnce sync.Once
	file_push_push_proto_rawDescData = file_push_push_proto_rawDesc
)

func file_push_push_proto_rawDescGZIP() []byte {
	file_push_push_proto_rawDescOnce.Do(func() {
		file_push_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_push_push_proto_rawDescData)
	})
	return file_push_push_proto_rawDescData
}

var file_push_push_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_push_push_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_push_push_proto_goTypes = []interface{}{
	(SendType)(0),                                       // 0: push.SendType
	(PushErrors)(0),                                     // 1: push.PushErrors
	(CommonMessageType)(0),                              // 2: push.CommonMessageType
	(BotNotificationType)(0),                            // 3: push.BotNotificationType
	(*PushCaptchaRequest)(nil),                          // 4: push.PushCaptchaRequest
	(*ErrorResponse)(nil),                               // 5: push.ErrorResponse
	(*PushEmailNotificationRequest)(nil),                // 6: push.PushEmailNotificationRequest
	(*GetCaptchaVerifyRequest)(nil),                     // 7: push.GetCaptchaVerifyRequest
	(*StoreOrderMailRequest)(nil),                       // 8: push.StoreOrderMailRequest
	(*PushWechatWorkGroupRobotNotificationRequest)(nil), // 9: push.PushWechatWorkGroupRobotNotificationRequest
	(*PushWechatTemplateMessageRequest)(nil),            // 10: push.PushWechatTemplateMessageRequest
	(*SenderInfo)(nil),                                  // 11: push.SenderInfo
	(*EmailNotification)(nil),                           // 12: push.EmailNotification
	(*SMSNotification)(nil),                             // 13: push.SMSNotification
	(*BotNotification)(nil),                             // 14: push.BotNotification
	(*BotNotificationV2)(nil),                           // 15: push.BotNotificationV2
	(*TemplateMessageDataObject)(nil),                   // 16: push.TemplateMessageDataObject
	(*Miniprogram)(nil),                                 // 17: push.Miniprogram
	(*WechatTemplateMessageNotification)(nil),           // 18: push.WechatTemplateMessageNotification
	(*PushCommonMessageRequest)(nil),                    // 19: push.PushCommonMessageRequest
	nil,                                                 // 20: push.WechatTemplateMessageNotification.DataEntry
}
var file_push_push_proto_depIdxs = []int32{
	0,  // 0: push.PushCaptchaRequest.Type:type_name -> push.SendType
	1,  // 1: push.ErrorResponse.ErrorInfo:type_name -> push.PushErrors
	0,  // 2: push.GetCaptchaVerifyRequest.Type:type_name -> push.SendType
	3,  // 3: push.BotNotification.Type:type_name -> push.BotNotificationType
	20, // 4: push.WechatTemplateMessageNotification.Data:type_name -> push.WechatTemplateMessageNotification.DataEntry
	17, // 5: push.WechatTemplateMessageNotification.Miniprogram:type_name -> push.Miniprogram
	2,  // 6: push.PushCommonMessageRequest.MessageType:type_name -> push.CommonMessageType
	11, // 7: push.PushCommonMessageRequest.SenderInfo:type_name -> push.SenderInfo
	12, // 8: push.PushCommonMessageRequest.EmailNotification:type_name -> push.EmailNotification
	13, // 9: push.PushCommonMessageRequest.SMSNotification:type_name -> push.SMSNotification
	14, // 10: push.PushCommonMessageRequest.BotNotification:type_name -> push.BotNotification
	18, // 11: push.PushCommonMessageRequest.WechatTemplateMessageNotification:type_name -> push.WechatTemplateMessageNotification
	15, // 12: push.PushCommonMessageRequest.BotNotificationV2:type_name -> push.BotNotificationV2
	16, // 13: push.WechatTemplateMessageNotification.DataEntry.value:type_name -> push.TemplateMessageDataObject
	4,  // 14: push.pushSV.PushCaptcha:input_type -> push.PushCaptchaRequest
	7,  // 15: push.pushSV.GetCaptchaVerify:input_type -> push.GetCaptchaVerifyRequest
	6,  // 16: push.pushSV.PushEmailNotification:input_type -> push.PushEmailNotificationRequest
	8,  // 17: push.pushSV.StoreOrderMail:input_type -> push.StoreOrderMailRequest
	8,  // 18: push.pushSV.PostOrderMail:input_type -> push.StoreOrderMailRequest
	9,  // 19: push.pushSV.PushWechatWorkGroupRobotNotification:input_type -> push.PushWechatWorkGroupRobotNotificationRequest
	10, // 20: push.pushSV.PushWechatTemplateMessage:input_type -> push.PushWechatTemplateMessageRequest
	19, // 21: push.pushSV.PushCommonMessage:input_type -> push.PushCommonMessageRequest
	5,  // 22: push.pushSV.PushCaptcha:output_type -> push.ErrorResponse
	5,  // 23: push.pushSV.GetCaptchaVerify:output_type -> push.ErrorResponse
	5,  // 24: push.pushSV.PushEmailNotification:output_type -> push.ErrorResponse
	5,  // 25: push.pushSV.StoreOrderMail:output_type -> push.ErrorResponse
	5,  // 26: push.pushSV.PostOrderMail:output_type -> push.ErrorResponse
	5,  // 27: push.pushSV.PushWechatWorkGroupRobotNotification:output_type -> push.ErrorResponse
	5,  // 28: push.pushSV.PushWechatTemplateMessage:output_type -> push.ErrorResponse
	5,  // 29: push.pushSV.PushCommonMessage:output_type -> push.ErrorResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_push_push_proto_init() }
func file_push_push_proto_init() {
	if File_push_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_push_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushCaptchaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushEmailNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaptchaVerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreOrderMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushWechatWorkGroupRobotNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushWechatTemplateMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMSNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotNotificationV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateMessageDataObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Miniprogram); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatTemplateMessageNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushCommonMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_push_push_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_push_proto_goTypes,
		DependencyIndexes: file_push_push_proto_depIdxs,
		EnumInfos:         file_push_push_proto_enumTypes,
		MessageInfos:      file_push_push_proto_msgTypes,
	}.Build()
	File_push_push_proto = out.File
	file_push_push_proto_rawDesc = nil
	file_push_push_proto_goTypes = nil
	file_push_push_proto_depIdxs = nil
}
