// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: push/push.proto

package push

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SendType int32

const (
	SendType_NoneSendType SendType = 0 // 默认值
	SendType_Mail         SendType = 1 // 邮箱
	SendType_Phone        SendType = 2 // 手机
)

// Enum value maps for SendType.
var (
	SendType_name = map[int32]string{
		0: "NoneSendType",
		1: "Mail",
		2: "Phone",
	}
	SendType_value = map[string]int32{
		"NoneSendType": 0,
		"Mail":         1,
		"Phone":        2,
	}
)

func (x SendType) Enum() *SendType {
	p := new(SendType)
	*p = x
	return p
}

func (x SendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendType) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_proto_enumTypes[0].Descriptor()
}

func (SendType) Type() protoreflect.EnumType {
	return &file_push_push_proto_enumTypes[0]
}

func (x SendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendType.Descriptor instead.
func (SendType) EnumDescriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

type PushErrors int32

const (
	PushErrors_None            PushErrors = 0       // 默认值
	PushErrors_PushCommonError PushErrors = 2000001 // 通用error
)

// Enum value maps for PushErrors.
var (
	PushErrors_name = map[int32]string{
		0:       "None",
		2000001: "PushCommonError",
	}
	PushErrors_value = map[string]int32{
		"None":            0,
		"PushCommonError": 2000001,
	}
)

func (x PushErrors) Enum() *PushErrors {
	p := new(PushErrors)
	*p = x
	return p
}

func (x PushErrors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushErrors) Descriptor() protoreflect.EnumDescriptor {
	return file_push_push_proto_enumTypes[1].Descriptor()
}

func (PushErrors) Type() protoreflect.EnumType {
	return &file_push_push_proto_enumTypes[1]
}

func (x PushErrors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushErrors.Descriptor instead.
func (PushErrors) EnumDescriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{1}
}

type PushCaptchaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`                     // 验证码
	Sender     string   `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"`                 // 发送人
	Type       SendType `protobuf:"varint,3,opt,name=Type,proto3,enum=push.SendType" json:"Type,omitempty"` // 发送类型
	UID        int64    `protobuf:"varint,4,opt,name=UID,proto3" json:"UID,omitempty"`                      // 被发送人的UID
	Account    string   `protobuf:"bytes,5,opt,name=Account,proto3" json:"Account,omitempty"`               // 被发送人的账户
	NationCode string   `protobuf:"bytes,6,opt,name=NationCode,proto3" json:"NationCode,omitempty"`         // 手机号区号
}

func (x *PushCaptchaRequest) Reset() {
	*x = PushCaptchaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushCaptchaRequest) ProtoMessage() {}

func (x *PushCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushCaptchaRequest.ProtoReflect.Descriptor instead.
func (*PushCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushCaptchaRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PushCaptchaRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PushCaptchaRequest) GetType() SendType {
	if x != nil {
		return x.Type
	}
	return SendType_NoneSendType
}

func (x *PushCaptchaRequest) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *PushCaptchaRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PushCaptchaRequest) GetNationCode() string {
	if x != nil {
		return x.NationCode
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorInfo PushErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=push.PushErrors" json:"ErrorInfo,omitempty"` // 错误信息
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResponse) GetErrorInfo() PushErrors {
	if x != nil {
		return x.ErrorInfo
	}
	return PushErrors_None
}

type PushEmailNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To      string `protobuf:"bytes,1,opt,name=To,proto3" json:"To,omitempty"`           // 发送到
	Html    string `protobuf:"bytes,2,opt,name=Html,proto3" json:"Html,omitempty"`       // 发送内容
	Subject string `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"` // 主题内容
}

func (x *PushEmailNotificationRequest) Reset() {
	*x = PushEmailNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushEmailNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushEmailNotificationRequest) ProtoMessage() {}

func (x *PushEmailNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushEmailNotificationRequest.ProtoReflect.Descriptor instead.
func (*PushEmailNotificationRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{2}
}

func (x *PushEmailNotificationRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *PushEmailNotificationRequest) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *PushEmailNotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type GetCaptchaVerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`                     // 验证码
	Account string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`               // 被发送人的账户
	UID     int64    `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`                      // 被发送人的UID
	Type    SendType `protobuf:"varint,4,opt,name=Type,proto3,enum=push.SendType" json:"Type,omitempty"` // 验证类型
}

func (x *GetCaptchaVerifyRequest) Reset() {
	*x = GetCaptchaVerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCaptchaVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaVerifyRequest) ProtoMessage() {}

func (x *GetCaptchaVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaVerifyRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaVerifyRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{3}
}

func (x *GetCaptchaVerifyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetCaptchaVerifyRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *GetCaptchaVerifyRequest) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *GetCaptchaVerifyRequest) GetType() SendType {
	if x != nil {
		return x.Type
	}
	return SendType_NoneSendType
}

type StoreOrderMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID  string `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`   // 来源订单
	HTML     string `protobuf:"bytes,2,opt,name=HTML,proto3" json:"HTML,omitempty"`         // 邮件信息
	ExpireIn string `protobuf:"bytes,3,opt,name=ExpireIn,proto3" json:"ExpireIn,omitempty"` // 有效时间
}

func (x *StoreOrderMailRequest) Reset() {
	*x = StoreOrderMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreOrderMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreOrderMailRequest) ProtoMessage() {}

func (x *StoreOrderMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreOrderMailRequest.ProtoReflect.Descriptor instead.
func (*StoreOrderMailRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{4}
}

func (x *StoreOrderMailRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *StoreOrderMailRequest) GetHTML() string {
	if x != nil {
		return x.HTML
	}
	return ""
}

func (x *StoreOrderMailRequest) GetExpireIn() string {
	if x != nil {
		return x.ExpireIn
	}
	return ""
}

type PushWechatWorkGroupRobotNotificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"` // 内容信息
	Retry   int64  `protobuf:"varint,2,opt,name=Retry,proto3" json:"Retry,omitempty"`    // 重试次数
}

func (x *PushWechatWorkGroupRobotNotificationRequest) Reset() {
	*x = PushWechatWorkGroupRobotNotificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushWechatWorkGroupRobotNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushWechatWorkGroupRobotNotificationRequest) ProtoMessage() {}

func (x *PushWechatWorkGroupRobotNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushWechatWorkGroupRobotNotificationRequest.ProtoReflect.Descriptor instead.
func (*PushWechatWorkGroupRobotNotificationRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{5}
}

func (x *PushWechatWorkGroupRobotNotificationRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushWechatWorkGroupRobotNotificationRequest) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

type PushWechatTemplateMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUser string `protobuf:"bytes,1,opt,name=ToUser,proto3" json:"ToUser,omitempty"` // 用户的OpenID
	Type   string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`     // 默认微信 mp
	URL    string `protobuf:"bytes,3,opt,name=URL,proto3" json:"URL,omitempty"`       // 模板消息地址
	Data   string `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`     // 数据消息
}

func (x *PushWechatTemplateMessageRequest) Reset() {
	*x = PushWechatTemplateMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_push_push_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushWechatTemplateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushWechatTemplateMessageRequest) ProtoMessage() {}

func (x *PushWechatTemplateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushWechatTemplateMessageRequest.ProtoReflect.Descriptor instead.
func (*PushWechatTemplateMessageRequest) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{6}
}

func (x *PushWechatTemplateMessageRequest) GetToUser() string {
	if x != nil {
		return x.ToUser
	}
	return ""
}

func (x *PushWechatTemplateMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PushWechatTemplateMessageRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *PushWechatTemplateMessageRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_push_push_proto protoreflect.FileDescriptor

var file_push_push_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x75, 0x73, 0x68, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x70, 0x75, 0x73, 0x68, 0x22, 0xb0, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x73, 0x68,
	0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3f, 0x0a, 0x0d, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5c, 0x0a, 0x1c, 0x50,
	0x75, 0x73, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x54,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x74, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x74, 0x6d, 0x6c, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x7d, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x55, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x61, 0x0a, 0x15, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x54, 0x4d, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x54, 0x4d, 0x4c, 0x12,
	0x1a, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x22, 0x5d, 0x0a, 0x2b, 0x50,
	0x75, 0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x52, 0x65, 0x74, 0x72, 0x79, 0x22, 0x74, 0x0a, 0x20, 0x50, 0x75,
	0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52,
	0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x2a, 0x31, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c,
	0x4e, 0x6f, 0x6e, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x10, 0x02, 0x2a, 0x2d, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x0f, 0x50,
	0x75, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x81,
	0x89, 0x7a, 0x32, 0xb1, 0x04, 0x0a, 0x06, 0x70, 0x75, 0x73, 0x68, 0x53, 0x56, 0x12, 0x3c, 0x0a,
	0x0b, 0x50, 0x75, 0x73, 0x68, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x12, 0x18, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68, 0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12,
	0x1d, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x74, 0x63, 0x68,
	0x61, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x15, 0x50, 0x75, 0x73, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x70,
	0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0d, 0x50, 0x6f, 0x73,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x2e, 0x70, 0x75, 0x73,
	0x68, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6e, 0x0a, 0x24,
	0x50, 0x75, 0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x19,
	0x50, 0x75, 0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x2e, 0x70, 0x75, 0x73, 0x68,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_push_push_proto_rawDescOnce sync.Once
	file_push_push_proto_rawDescData = file_push_push_proto_rawDesc
)

func file_push_push_proto_rawDescGZIP() []byte {
	file_push_push_proto_rawDescOnce.Do(func() {
		file_push_push_proto_rawDescData = protoimpl.X.CompressGZIP(file_push_push_proto_rawDescData)
	})
	return file_push_push_proto_rawDescData
}

var file_push_push_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_push_push_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_push_push_proto_goTypes = []interface{}{
	(SendType)(0),                                       // 0: push.SendType
	(PushErrors)(0),                                     // 1: push.PushErrors
	(*PushCaptchaRequest)(nil),                          // 2: push.PushCaptchaRequest
	(*ErrorResponse)(nil),                               // 3: push.ErrorResponse
	(*PushEmailNotificationRequest)(nil),                // 4: push.PushEmailNotificationRequest
	(*GetCaptchaVerifyRequest)(nil),                     // 5: push.GetCaptchaVerifyRequest
	(*StoreOrderMailRequest)(nil),                       // 6: push.StoreOrderMailRequest
	(*PushWechatWorkGroupRobotNotificationRequest)(nil), // 7: push.PushWechatWorkGroupRobotNotificationRequest
	(*PushWechatTemplateMessageRequest)(nil),            // 8: push.PushWechatTemplateMessageRequest
}
var file_push_push_proto_depIdxs = []int32{
	0,  // 0: push.PushCaptchaRequest.Type:type_name -> push.SendType
	1,  // 1: push.ErrorResponse.ErrorInfo:type_name -> push.PushErrors
	0,  // 2: push.GetCaptchaVerifyRequest.Type:type_name -> push.SendType
	2,  // 3: push.pushSV.PushCaptcha:input_type -> push.PushCaptchaRequest
	5,  // 4: push.pushSV.GetCaptchaVerify:input_type -> push.GetCaptchaVerifyRequest
	4,  // 5: push.pushSV.PushEmailNotification:input_type -> push.PushEmailNotificationRequest
	6,  // 6: push.pushSV.StoreOrderMail:input_type -> push.StoreOrderMailRequest
	6,  // 7: push.pushSV.PostOrderMail:input_type -> push.StoreOrderMailRequest
	7,  // 8: push.pushSV.PushWechatWorkGroupRobotNotification:input_type -> push.PushWechatWorkGroupRobotNotificationRequest
	8,  // 9: push.pushSV.PushWechatTemplateMessage:input_type -> push.PushWechatTemplateMessageRequest
	3,  // 10: push.pushSV.PushCaptcha:output_type -> push.ErrorResponse
	3,  // 11: push.pushSV.GetCaptchaVerify:output_type -> push.ErrorResponse
	3,  // 12: push.pushSV.PushEmailNotification:output_type -> push.ErrorResponse
	3,  // 13: push.pushSV.StoreOrderMail:output_type -> push.ErrorResponse
	3,  // 14: push.pushSV.PostOrderMail:output_type -> push.ErrorResponse
	3,  // 15: push.pushSV.PushWechatWorkGroupRobotNotification:output_type -> push.ErrorResponse
	3,  // 16: push.pushSV.PushWechatTemplateMessage:output_type -> push.ErrorResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_push_push_proto_init() }
func file_push_push_proto_init() {
	if File_push_push_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_push_push_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushCaptchaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushEmailNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCaptchaVerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreOrderMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushWechatWorkGroupRobotNotificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_push_push_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushWechatTemplateMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_push_push_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_push_proto_goTypes,
		DependencyIndexes: file_push_push_proto_depIdxs,
		EnumInfos:         file_push_push_proto_enumTypes,
		MessageInfos:      file_push_push_proto_msgTypes,
	}.Build()
	File_push_push_proto = out.File
	file_push_push_proto_rawDesc = nil
	file_push_push_proto_goTypes = nil
	file_push_push_proto_depIdxs = nil
}
