// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push/push.proto

package push

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendType int32

const (
	SendType_NoneSendType SendType = 0
	SendType_Mail         SendType = 1
	SendType_Phone        SendType = 2
)

var SendType_name = map[int32]string{
	0: "NoneSendType",
	1: "Mail",
	2: "Phone",
}

var SendType_value = map[string]int32{
	"NoneSendType": 0,
	"Mail":         1,
	"Phone":        2,
}

func (x SendType) String() string {
	return proto.EnumName(SendType_name, int32(x))
}

func (SendType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae0042da44e9a7a7, []int{0}
}

type PushErrors int32

const (
	PushErrors_None            PushErrors = 0
	PushErrors_PushCommonError PushErrors = 2000001
)

var PushErrors_name = map[int32]string{
	0:       "None",
	2000001: "PushCommonError",
}

var PushErrors_value = map[string]int32{
	"None":            0,
	"PushCommonError": 2000001,
}

func (x PushErrors) String() string {
	return proto.EnumName(PushErrors_name, int32(x))
}

func (PushErrors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae0042da44e9a7a7, []int{1}
}

type PushCaptchaRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Sender               string   `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Type                 SendType `protobuf:"varint,3,opt,name=Type,proto3,enum=push.SendType" json:"Type,omitempty"`
	UID                  int64    `protobuf:"varint,4,opt,name=UID,proto3" json:"UID,omitempty"`
	Account              string   `protobuf:"bytes,5,opt,name=Account,proto3" json:"Account,omitempty"`
	NationCode           string   `protobuf:"bytes,6,opt,name=NationCode,proto3" json:"NationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushCaptchaRequest) Reset()         { *m = PushCaptchaRequest{} }
func (m *PushCaptchaRequest) String() string { return proto.CompactTextString(m) }
func (*PushCaptchaRequest) ProtoMessage()    {}
func (*PushCaptchaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae0042da44e9a7a7, []int{0}
}

func (m *PushCaptchaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushCaptchaRequest.Unmarshal(m, b)
}
func (m *PushCaptchaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushCaptchaRequest.Marshal(b, m, deterministic)
}
func (m *PushCaptchaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushCaptchaRequest.Merge(m, src)
}
func (m *PushCaptchaRequest) XXX_Size() int {
	return xxx_messageInfo_PushCaptchaRequest.Size(m)
}
func (m *PushCaptchaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushCaptchaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushCaptchaRequest proto.InternalMessageInfo

func (m *PushCaptchaRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PushCaptchaRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *PushCaptchaRequest) GetType() SendType {
	if m != nil {
		return m.Type
	}
	return SendType_NoneSendType
}

func (m *PushCaptchaRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *PushCaptchaRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PushCaptchaRequest) GetNationCode() string {
	if m != nil {
		return m.NationCode
	}
	return ""
}

type ErrorResponse struct {
	ErrorInfo            PushErrors `protobuf:"varint,1,opt,name=ErrorInfo,proto3,enum=push.PushErrors" json:"ErrorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae0042da44e9a7a7, []int{1}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetErrorInfo() PushErrors {
	if m != nil {
		return m.ErrorInfo
	}
	return PushErrors_None
}

type PushEmailNotificationRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=To,proto3" json:"To,omitempty"`
	Html                 string   `protobuf:"bytes,2,opt,name=Html,proto3" json:"Html,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=Subject,proto3" json:"Subject,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushEmailNotificationRequest) Reset()         { *m = PushEmailNotificationRequest{} }
func (m *PushEmailNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*PushEmailNotificationRequest) ProtoMessage()    {}
func (*PushEmailNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae0042da44e9a7a7, []int{2}
}

func (m *PushEmailNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushEmailNotificationRequest.Unmarshal(m, b)
}
func (m *PushEmailNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushEmailNotificationRequest.Marshal(b, m, deterministic)
}
func (m *PushEmailNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushEmailNotificationRequest.Merge(m, src)
}
func (m *PushEmailNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_PushEmailNotificationRequest.Size(m)
}
func (m *PushEmailNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushEmailNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushEmailNotificationRequest proto.InternalMessageInfo

func (m *PushEmailNotificationRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *PushEmailNotificationRequest) GetHtml() string {
	if m != nil {
		return m.Html
	}
	return ""
}

func (m *PushEmailNotificationRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type GetCaptchaVerifyRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	UID                  int64    `protobuf:"varint,3,opt,name=UID,proto3" json:"UID,omitempty"`
	Type                 SendType `protobuf:"varint,4,opt,name=Type,proto3,enum=push.SendType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCaptchaVerifyRequest) Reset()         { *m = GetCaptchaVerifyRequest{} }
func (m *GetCaptchaVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*GetCaptchaVerifyRequest) ProtoMessage()    {}
func (*GetCaptchaVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae0042da44e9a7a7, []int{3}
}

func (m *GetCaptchaVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCaptchaVerifyRequest.Unmarshal(m, b)
}
func (m *GetCaptchaVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCaptchaVerifyRequest.Marshal(b, m, deterministic)
}
func (m *GetCaptchaVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCaptchaVerifyRequest.Merge(m, src)
}
func (m *GetCaptchaVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_GetCaptchaVerifyRequest.Size(m)
}
func (m *GetCaptchaVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCaptchaVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCaptchaVerifyRequest proto.InternalMessageInfo

func (m *GetCaptchaVerifyRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GetCaptchaVerifyRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetCaptchaVerifyRequest) GetUID() int64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *GetCaptchaVerifyRequest) GetType() SendType {
	if m != nil {
		return m.Type
	}
	return SendType_NoneSendType
}

type StoreOrderMailRequest struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	HTML                 string   `protobuf:"bytes,2,opt,name=HTML,proto3" json:"HTML,omitempty"`
	ExpireIn             string   `protobuf:"bytes,3,opt,name=ExpireIn,proto3" json:"ExpireIn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreOrderMailRequest) Reset()         { *m = StoreOrderMailRequest{} }
func (m *StoreOrderMailRequest) String() string { return proto.CompactTextString(m) }
func (*StoreOrderMailRequest) ProtoMessage()    {}
func (*StoreOrderMailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae0042da44e9a7a7, []int{4}
}

func (m *StoreOrderMailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreOrderMailRequest.Unmarshal(m, b)
}
func (m *StoreOrderMailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreOrderMailRequest.Marshal(b, m, deterministic)
}
func (m *StoreOrderMailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreOrderMailRequest.Merge(m, src)
}
func (m *StoreOrderMailRequest) XXX_Size() int {
	return xxx_messageInfo_StoreOrderMailRequest.Size(m)
}
func (m *StoreOrderMailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreOrderMailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreOrderMailRequest proto.InternalMessageInfo

func (m *StoreOrderMailRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *StoreOrderMailRequest) GetHTML() string {
	if m != nil {
		return m.HTML
	}
	return ""
}

func (m *StoreOrderMailRequest) GetExpireIn() string {
	if m != nil {
		return m.ExpireIn
	}
	return ""
}

type PushWechatWorkGroupRobotNotificationRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	Retry                int64    `protobuf:"varint,2,opt,name=Retry,proto3" json:"Retry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushWechatWorkGroupRobotNotificationRequest) Reset() {
	*m = PushWechatWorkGroupRobotNotificationRequest{}
}
func (m *PushWechatWorkGroupRobotNotificationRequest) String() string {
	return proto.CompactTextString(m)
}
func (*PushWechatWorkGroupRobotNotificationRequest) ProtoMessage() {}
func (*PushWechatWorkGroupRobotNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae0042da44e9a7a7, []int{5}
}

func (m *PushWechatWorkGroupRobotNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushWechatWorkGroupRobotNotificationRequest.Unmarshal(m, b)
}
func (m *PushWechatWorkGroupRobotNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushWechatWorkGroupRobotNotificationRequest.Marshal(b, m, deterministic)
}
func (m *PushWechatWorkGroupRobotNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushWechatWorkGroupRobotNotificationRequest.Merge(m, src)
}
func (m *PushWechatWorkGroupRobotNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_PushWechatWorkGroupRobotNotificationRequest.Size(m)
}
func (m *PushWechatWorkGroupRobotNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushWechatWorkGroupRobotNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushWechatWorkGroupRobotNotificationRequest proto.InternalMessageInfo

func (m *PushWechatWorkGroupRobotNotificationRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PushWechatWorkGroupRobotNotificationRequest) GetRetry() int64 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func init() {
	proto.RegisterEnum("push.SendType", SendType_name, SendType_value)
	proto.RegisterEnum("push.PushErrors", PushErrors_name, PushErrors_value)
	proto.RegisterType((*PushCaptchaRequest)(nil), "push.PushCaptchaRequest")
	proto.RegisterType((*ErrorResponse)(nil), "push.ErrorResponse")
	proto.RegisterType((*PushEmailNotificationRequest)(nil), "push.PushEmailNotificationRequest")
	proto.RegisterType((*GetCaptchaVerifyRequest)(nil), "push.GetCaptchaVerifyRequest")
	proto.RegisterType((*StoreOrderMailRequest)(nil), "push.StoreOrderMailRequest")
	proto.RegisterType((*PushWechatWorkGroupRobotNotificationRequest)(nil), "push.PushWechatWorkGroupRobotNotificationRequest")
}

func init() {
	proto.RegisterFile("push/push.proto", fileDescriptor_ae0042da44e9a7a7)
}

var fileDescriptor_ae0042da44e9a7a7 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x63, 0xe7, 0x6b, 0xa0, 0xa9, 0x35, 0x10, 0xb0, 0xca, 0x87, 0x22, 0x8b, 0x43, 0x54,
	0x44, 0x50, 0xc3, 0x15, 0x09, 0x95, 0xb4, 0x94, 0x48, 0x4d, 0x88, 0x9c, 0xd0, 0x5e, 0xe0, 0xe0,
	0x38, 0x1b, 0xc5, 0x90, 0xec, 0x98, 0xf5, 0x5a, 0x22, 0x48, 0x1c, 0x38, 0xf2, 0x6f, 0xf8, 0x37,
	0xfc, 0x1d, 0xb4, 0x1b, 0xbb, 0x49, 0x90, 0x83, 0x2a, 0x71, 0xb1, 0xe6, 0xcd, 0xac, 0x67, 0xe6,
	0xbd, 0x7d, 0x36, 0x1c, 0x44, 0x49, 0x3c, 0x7b, 0xae, 0x1e, 0xad, 0x48, 0x90, 0x24, 0xb4, 0x54,
	0xec, 0xfe, 0x32, 0x00, 0x07, 0x49, 0x3c, 0xeb, 0xf8, 0x91, 0x0c, 0x66, 0xbe, 0xc7, 0xbe, 0x24,
	0x2c, 0x96, 0x88, 0x60, 0x75, 0x68, 0xc2, 0x1c, 0xa3, 0x61, 0x34, 0xab, 0x9e, 0x8e, 0xf1, 0x1e,
	0x94, 0x86, 0x8c, 0x4f, 0x98, 0x70, 0x0a, 0x3a, 0x9b, 0x22, 0x74, 0xc1, 0x1a, 0x2d, 0x23, 0xe6,
	0x98, 0x0d, 0xa3, 0x59, 0x6b, 0xd7, 0x5a, 0x7a, 0x86, 0xaa, 0xa9, 0xac, 0xa7, 0x6b, 0x68, 0x83,
	0xf9, 0xbe, 0x7b, 0xea, 0x58, 0x0d, 0xa3, 0x69, 0x7a, 0x2a, 0x44, 0x07, 0xca, 0x27, 0x41, 0x40,
	0x09, 0x97, 0x4e, 0x51, 0xb7, 0xcb, 0x20, 0x3e, 0x06, 0xe8, 0xfb, 0x32, 0x24, 0xae, 0x37, 0x28,
	0xe9, 0xe2, 0x46, 0xc6, 0x7d, 0x05, 0xfb, 0x67, 0x42, 0x90, 0xf0, 0x58, 0x1c, 0x11, 0x8f, 0x19,
	0xb6, 0xa0, 0xaa, 0x13, 0x5d, 0x3e, 0x25, 0xbd, 0x71, 0xad, 0x6d, 0xaf, 0xb6, 0x50, 0xcc, 0x74,
	0x29, 0xf6, 0xd6, 0x47, 0xdc, 0x0f, 0xf0, 0x50, 0x17, 0x16, 0x7e, 0x38, 0xef, 0x93, 0x0c, 0xa7,
	0x61, 0xa0, 0xbb, 0x67, 0xe4, 0x6b, 0x50, 0x18, 0x51, 0x4a, 0xbd, 0x30, 0x22, 0x25, 0xc6, 0x5b,
	0xb9, 0x98, 0xa7, 0xb4, 0x75, 0xac, 0xd6, 0x1f, 0x26, 0xe3, 0x4f, 0x2c, 0x90, 0x9a, 0x77, 0xd5,
	0xcb, 0xa0, 0xfb, 0x1d, 0xee, 0x9f, 0x33, 0x99, 0xea, 0x79, 0xc9, 0x44, 0x38, 0x5d, 0xfe, 0x4b,
	0xd5, 0x0d, 0x1d, 0x0a, 0xdb, 0x3a, 0xa4, 0x9a, 0x99, 0x6b, 0xcd, 0x32, 0xa5, 0xad, 0xdd, 0x4a,
	0xbb, 0x3e, 0xd4, 0x87, 0x92, 0x04, 0x7b, 0x27, 0x26, 0x4c, 0xf4, 0xfc, 0x70, 0x9e, 0x0d, 0x77,
	0xa0, 0xac, 0x73, 0xdd, 0xd3, 0x74, 0x7e, 0x06, 0x35, 0xbf, 0x51, 0xef, 0xe2, 0x9a, 0xdf, 0xa8,
	0x77, 0x81, 0x87, 0x50, 0x39, 0xfb, 0x1a, 0x85, 0x82, 0x75, 0x79, 0x4a, 0xf0, 0x1a, 0xbb, 0x1f,
	0xe1, 0xa9, 0xd2, 0xef, 0x8a, 0x05, 0x33, 0x5f, 0x5e, 0x91, 0xf8, 0x7c, 0x2e, 0x28, 0x89, 0x3c,
	0x1a, 0x93, 0xcc, 0x93, 0xd3, 0x81, 0x72, 0x87, 0xb8, 0x64, 0x5c, 0x66, 0x83, 0x53, 0x88, 0x77,
	0xa1, 0xe8, 0x31, 0x29, 0x96, 0x7a, 0xb2, 0xe9, 0xad, 0xc0, 0xd1, 0x31, 0x54, 0x32, 0x4e, 0x68,
	0xc3, 0xed, 0x3e, 0x71, 0x96, 0x61, 0x7b, 0x0f, 0x2b, 0x60, 0x29, 0x56, 0xb6, 0x81, 0x55, 0x28,
	0x0e, 0x66, 0xc4, 0x99, 0x5d, 0x38, 0x7a, 0x06, 0xb0, 0xbe, 0x6a, 0x75, 0x44, 0xbd, 0x64, 0xef,
	0x61, 0x1d, 0x0e, 0xb4, 0xb9, 0x69, 0xb1, 0x20, 0xae, 0xab, 0xf6, 0x8f, 0x9f, 0xdf, 0xda, 0xbf,
	0x4d, 0x28, 0x29, 0xed, 0x86, 0x97, 0xf8, 0x12, 0x6e, 0x6d, 0xd8, 0x1f, 0x9d, 0xb5, 0x6f, 0xb6,
	0xbf, 0x88, 0xc3, 0x3b, 0xab, 0xca, 0xb6, 0xf3, 0xde, 0x80, 0xfd, 0xf7, 0x5d, 0xe3, 0xa3, 0xd5,
	0xc1, 0x1d, 0x1e, 0xc8, 0xef, 0x33, 0x80, 0x7a, 0xae, 0x23, 0xd1, 0xdd, 0xf0, 0xf1, 0x0e, 0xbb,
	0xe6, 0x77, 0x7c, 0x0d, 0xb5, 0x6d, 0x1b, 0xe0, 0x83, 0xd4, 0x2e, 0x79, 0xe6, 0xc8, 0xef, 0x71,
	0x02, 0xfb, 0x03, 0x8a, 0xe5, 0xff, 0xb4, 0xe0, 0xf0, 0xe4, 0x26, 0x56, 0xc1, 0xe3, 0x35, 0xcf,
	0x1b, 0xda, 0x2a, 0x77, 0xde, 0xb8, 0xa4, 0xff, 0x6d, 0x2f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x99, 0x41, 0x84, 0xd0, 0xee, 0x04, 0x00, 0x00,
}
