name: protoc

on: [push]

env:
  GO111MODULE: "on"
  #GOPROXY: "https://goproxy.io"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'get-previous-tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14.0"
      - name: proto-compiler-go
        id: protocgo
        run: |
          sudo apt install protobuf-compiler
          protoc --version
          go get -u github.com/golang/protobuf/protoc-gen-go
          # go get -u github.com/asim/go-micro/cmd/protoc-gen-micro/v3@latest
          go get -u github.com/micro/micro/v2/cmd/protoc-gen-micro@master
          sh build.sh
          git config --global user.name "unliar"
          git config --global user.email "370732889@qq.com"
          git add .
          git commit -am "github action auto-commit" && git push && echo ::set-output name=commited::1 || echo ::set-output name=commited::0
      - name: wechat-work-bot-success-commited
        if: ${{steps.protocgo.outputs.commited == 1}}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ✅ [happysooner-proto 编译成功](https://github.com/${{github.repository}}) \n
          > link: [项目地址](https://github.com/${{github.repository}})   \n  
          > desc: 最新TAG=${{ steps.previoustag.outputs.tag }} 文件变动 快去新增 TAG 吧
          "
      - name: wechat-work-bot-success-nocommited
        if: ${{steps.protocgo.outputs.commited == 0}}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ✅ [happysooner-proto 编译成功](https://github.com/${{github.repository}}) \n
          > link: [项目地址](https://github.com/${{github.repository}})   \n  
          > desc: 最新TAG=${{ steps.previoustag.outputs.tag }} 文件无变动 无需新增 TAG
          "    
      - name: wechat-work-bot-failed-build
        if: ${{ failure() }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ❌ ${{ github.event.repository.name }} 构建文件失败 \n
          > link: [项目地址](https://github.com/${{github.repository}})   \n 
          "
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./pay/pay.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./push/push.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./writing/writing.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./counter/counter.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./search/search.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./file/file.proto
