name: protoc

on: [push]

env:
  GO111MODULE: "on"
  GOPROXY: "https://goproxy.cn"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14.0"
      - run: |
          sudo apt install protobuf-compiler
          protoc --version
          go get -u github.com/golang/protobuf/protoc-gen-go
          go get -u github.com/micro/protoc-gen-micro/v2
          protoc --micro_out=. --go_out=. ./account/account.proto
          protoc --micro_out=. --go_out=. ./pay/pay.proto
          protoc --micro_out=. --go_out=. ./push/push.proto
          protoc --micro_out=. --go_out=. ./writing/writing.proto
          protoc --micro_out=. --go_out=. ./counter/counter.proto
          protoc --micro_out=. --go_out=. ./search/search.proto
          protoc --micro_out=. --go_out=. ./file/file.proto
          ls
          git status
          git config --global user.name "unliar"
          git config --global user.email "370732889@qq.com"
          git commit -am "github action auto-commit" && git push || echo "nothing commit"
      - name: wechat-work-bot-success-build
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ✅ [proto文件构建成功](https://github.com/${{github.repository}}) \n
          > link: [项目地址](https://github.com/${{github.repository}})   \n  
          > 快去打 TAG 吧
          "
      - name: wechat-work-bot-failed-build
        if: ${{ failure() }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "#### ${{ github.event.repository.name }} ❎ proto文件构建失败 \n
          > link: [项目地址](https://github.com/${{github.repository}})   \n  
          "    
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./pay/pay.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./push/push.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./writing/writing.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./counter/counter.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./search/search.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./file/file.proto
