name: protoc

on: [push]

env:
  GO111MODULE: "on"
  #GOPROXY: "https://goproxy.io"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'get-previous-tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14.0"
      - name: proto-compiler-go
        id: protocgo
        run: |
          sudo apt install protobuf-compiler
          protoc --version
          go install github.com/golang/protobuf/protoc-gen-go
          go install go-micro.dev/v4/cmd/protoc-gen-micro@v4
          sh build.sh
          git config --global user.name "unliar"
          git config --global user.email "370732889@qq.com"
          git add .
          git commit -am "github action auto-commit" && git push && echo ::set-output name=commited::1 || echo ::set-output name=commited::0
      - name: feishu-bot-message-change
        if: ${{steps.protocgo.outputs.commited == 1}}
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              🐳 构建状态 - From Github Action 
              
              repository: https://github.com/${{ github.repository }}

              committer: https://github.com/${{ github.actor }}
              
              compare: ${{ github.event.compare }}

              job status: ${{ job.status }}

              desc: 最新TAG=${{ steps.previoustag.outputs.tag }} 文件变动 快去新增 TAG 吧

      - name: feishu-bot-message-unchange
        if: ${{steps.protocgo.outputs.commited == 0}}
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              🐳 构建状态 - From Github Action 
              
              repository: https://github.com/${{ github.repository }}

              committer: https://github.com/${{ github.actor }}
              
              compare: ${{ github.event.compare }}

              job status: ${{ job.status }}

              desc: 最新TAG=${{ steps.previoustag.outputs.tag }} 文件无变动 无需新增 TAG
   
      - name: feishu-bot-message
        if: always()
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          msg_type: text
          content: |
            text: |
              🐳 构建状态 - From Github Action 
              
              repository: https://github.com/${{ github.repository }}

              committer: https://github.com/${{ github.actor }}
              
              compare: ${{ github.event.compare }}

              job status: ${{ job.status }}

  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./pay/pay.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./push/push.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./writing/writing.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./counter/counter.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./search/search.proto
  #        protoc --plugin=protoc-gen-go=$GOPATH/bin/protoc-gen-go --plugin=protoc-gen-micro=$GOPATH/bin/protoc-gen-micro --proto_path=$GOPATH/src:. --micro_out=. --go_out=. ./file/file.proto
